<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Laravel PHP Framework'); ?>
        <p><strong>Laravel</strong> is a free, open-source <?php echo $this->stencil->addLink('PHP', 'L'); ?> web application framework, created by Taylor Otwell and intended for the development of web applications following the <?php echo $this->stencil->addLink('Model View Controller', 'SDA'); ?> (MVC) architectural pattern. Prominent Laravel features include its expressive syntax, a modular packaging system with a dedicated dependency manager, different ways for accessing relational databases, and various utilities that aid in application deployment and maintenance.</p>
        <p>According to a March 2015 developers survey on PHP frameworks popularity, Laravel was listed as the most popular PHP framework of 2015, followed by <?php echo $this->stencil->addLink('Symfony2', 'PHP'); ?>, <?php echo $this->stencil->addLink('Nette', 'PHP'); ?>, <?php echo $this->stencil->addLink('CodeIgniter', 'PHP'); ?>, <?php echo $this->stencil->addLink('Yii', 'L'); ?> and others.</p>
        <p>Laravel was created by Taylor Otwell as a more feature-rich alternative to the CodeIgniter framework, which did not provide various advanced features such as support for user authentication and authorization. Laravel's first beta release was made available on 9 June 2011, followed by the Laravel 1 release later in the same month. Laravel 1 includes built-in support for authentication, localisation, models, views, sessions, routing and other mechanisms, but lacks support for controllers that prevents it from being a true MVC framework.</p>
        <p></p>Laravel 2 was released in September 2011, bringing various improvements from the author and community. Major new features include the support for controllers, which made Laravel 2 a fully MVC-compliant framework, built-in support for the <?php echo $this->stencil->addLink('inversion of control', 'SD'); ?> (IoC) principle, and the so-called "Blade" templating system. As a downside, support for third-party packages was removed in Laravel 2.</p>
        <p></p>Laravel 3 was released in February 2012 with a set of new features including the <?php echo $this->stencil->addLink('Command Line Interface', 'IT'); ?> (CLI) named "<em>Artisan</em>", built-in support for more database management systems, database migrations as a form of version control for database layouts, support for handling events, and a packaging system called "Bundles". A significant increase of the Laravel's userbase and popularity lined up with the release of Laravel 3.</p>
        <p>Laravel 4, codenamed "<em>Illuminate</em>", was released in May 2013. It was made as a complete rewrite of the Laravel framework, migrating its layout into a set of separate packages distributed through <?php echo $this->stencil->addLink('Composer', 'PHP'); ?>, which serves as an application-level package manager. Such a layout allowed much better extendibility of Laravel 4, paired with its official regular release schedule spanning six months between minor point releases. Other new features in the Laravel 4 release include database seeding for the initial population of databases, support for message queues, built-in support for sending different types of email, and support for delayed deletion of database records called "soft deletion".</p>
        <p>Laravel 5 was released in February 2015 as a result of significant changes that ended up in renumbering the then future Laravel 4.3 release. Beside bringing various new features and improvements to already existing ones, Laravel 5 also introduced a new internal directory tree structure for developed applications. New features in the Laravel 5 release include support for scheduling periodically executed tasks through a package called "Scheduler", an abstraction layer called "Flysystem" that allows remote storage to be used in the same way as local file systems, improved handling of package assets through "Elixir", and simplified externally handled authentication through the optional "Socialite" package.</p>
        <p>Laravel 5.1, released in June 2015, is the first release of Laravel to receive long-term support (LTS), with planned availability of bug fixes for two years and security patches for three years. LTS releases of Laravel are planned to be released every two years.</p>
    </div>
</div>
