<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Bitmap'); ?>
        <p>In computing, a <strong>bitmap</strong> is a mapping from some domain (for example, a range of integers) to bits, that is, values which are zero or one. It is also called a bit array or bitmap index.</p>
        <p>In computer graphics, when the domain is a rectangle (indexed by two coordinates) a bitmap gives a way to store a binary image, that is, an image in which each pixel is either black or white (or any two colours).</p>
        <p>The more general term pixmap refers to a map of pixels, where each one may store more than two colors, thus using more than one bit per pixel. Often bitmap is used for this as well. In some contexts, the term bitmap implies one bit per pixel, while pixmap is used for images with multiple bits per pixel.</p>
        <p>A bitmap is a type of memory organisation or image file format used to store digital images. The term bitmap comes from the computer programming terminology, meaning just a map of bits, a spatially mapped array of bits. Now, along with pixmap, it commonly refers to the similar concept of a spatially mapped array of pixels. Raster images in general may be referred to as bitmaps or pixmaps, whether synthetic or photographic, in files or memory.</p>
        <p>Many graphical user interfaces use bitmaps in their built-in graphics subsystems; for example, the <?php echo $this->stencil->addLink('Microsoft Windows', 'OS'); ?> and <?php echo $this->stencil->addLink('OS/2', 'OS'); ?> platforms' <?php echo $this->stencil->addLink('GDI', 'IT'); ?> subsystem, where the specific format used is the Windows and OS/2 bitmap file format, usually named with the file extension of <code>.BMP</code> (or <code>.DIB</code> for device-independent bitmap). Besides BMP, other file formats that store literal bitmaps include InterLeaved Bitmap (ILBM), Portable Bitmap (PBM), X Bitmap (XBM), and Wireless Application Protocol Bitmap (WBMP). Similarly, most other image file formats, such as <?php echo $this->stencil->addLink('JPEG', 'IT'); ?>, <?php echo $this->stencil->addLink('TIFF', 'IT'); ?>, <?php echo $this->stencil->addLink('PNG', 'IT'); ?>, and <?php echo $this->stencil->addLink('GIF', 'IT'); ?>, also store bitmap images (as opposed to <?php echo $this->stencil->addLink('vector graphics', 'IT'); ?>), but they are not usually referred to as bitmaps, since they use compressed formats internally.</p>
    </div>
</div>