<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Daemon'); ?>
        <p>In multitasking computer operating systems, a <strong>daemon</strong> is a computer program that runs as a background process, rather than being under the direct control of an interactive user. Traditionally daemon names end with the letter <code>d</code>. For example, <code>syslogd</code> is the daemon that implements the system logging facility and <code>sshd</code> is a daemon that services incoming <?php echo $this->stencil->addLink('SSH', 'IPA'); ?> connections.</p>
        <p>In a <?php echo $this->stencil->addLink('Unix', 'OS'); ?> environment, the parent process of a daemon is often, but not always, the init process. A daemon is usually either created by a process forking a child process and then immediately exiting, thus causing init to adopt the child process, or by the init process directly launching the daemon. In addition, a daemon launched by forking and exiting typically must perform other operations, such as dissociating the process from any controlling terminal (<code>tty</code>). Such procedures are often implemented in various convenience routines such as daemon in Unix.</p>
        <p>Systems often start daemons at boot time and serve the function of responding to network requests, hardware activity, or other programs by performing some task. Daemons can also configure hardware (like <code>udevd</code> on some <?php echo $this->stencil->addLink('Linux', 'OS'); ?> systems), run scheduled tasks (like <?php echo $this->stencil->addLink('cron', 'IT'); ?>), and perform a variety of other tasks.</p>
        <p>The term was coined by the programmers of <?php echo $this->stencil->addLink('MIT', 'C'); ?>'s <strong>Project MAC</strong>. They took the name from <strong>Maxwell's demon</strong>, an imaginary being from a thought experiment that constantly works in the background, sorting molecules. Unix systems inherited this terminology. Maxwell's Demon is consistent with Greek mythology's interpretation of a daemon as a supernatural being working in the background, with no particular bias towards good or evil.</p>
        <p>The word daemon is an alternative spelling of demon. Alternate terms for daemon are service (<?php echo $this->stencil->addLink('Microsoft Windows NT', 'WIN'); ?>), started task (<strong>IBM z/OS</strong>), and ghost job (<strong>XDS UTS</strong>).</p>
    </div>
</div>