<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('The Dot Com Bubble'); ?>
        <p>The <strong>dot com bubble</strong> (also referred to as the <strong>dot com boom</strong>, and the <strong>Internet bubble</strong>) was a historic speculative bubble covering roughly 1997 - 2000 (with a climax on 10 March 2000, with the NASDAQ peaking at 5,408.60 in intraday trading before closing at 5,048.62) during which stock markets in industrialized nations saw their equity value rise rapidly from growth in the Internet sector and related fields.</p>
        <p>While the latter part was a boom and bust cycle, the Internet boom is sometimes meant to refer to the steady commercial growth of the Internet with the advent of the <?php echo $this->stencil->addLink('World Wide Web', 'WD'); ?>, as exemplified by the first release of the <?php echo $this->stencil->addLink('Mosaic', 'WB'); ?> web browser in 1993, and continuing through the 1990s.</p>
        <p>The period was marked by the founding (and, in many cases, spectacular failure) of a group of new Internet based companies commonly referred to as <em>dot coms</em>.</p>
        <p>Companies could cause their stock prices to increase by simply adding an "e-" prefix to their name or a ".com" to the end, which one author called "prefix investing."</p>
        <p>A combination of rapidly increasing stock prices, market confidence that the companies would turn future profits, individual speculation in stocks, and widely available venture capital created an environment in which many investors were willing to overlook traditional metrics, such as P/E ratio, in favour of basing confidence on technological advancements.</p>
        <p>The collapse of the bubble took place during 1999 - 2001. Some companies failed completely. Others lost a large portion of their market capitalization but remained stable and profitable, some later recovered and surpassed their dot com bubble peaks.</p>
    </div>
</div>