<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Microsoft Agent'); ?>
        <p><strong>Microsoft Agent</strong> is a technology developed by <?php echo $this->stencil->addLink('Microsoft', 'c'); ?> which employs animated characters, text-to-speech engines, and speech recognition software to enhance interaction with computer users. Thus it is an example of an embodied agent. It comes preinstalled as part of <?php echo $this->stencil->addLink('Microsoft Windows 2000', 'WIN'); ?> through <?php echo $this->stencil->addLink('Windows Vista', 'WIN'); ?>. Microsoft Agent functionality is exposed as an <?php echo $this->stencil->addLink('ActiveX', 'IT'); ?> control that can be used by web pages.</p>
        <p>The theory behind this software came from work on social interfaces by Clifford Nass and Byron Reeves at Stanford's Center for the Study of Language and Information.</p>
        <p>Interactive character technology was first introduced in <strong>Microsoft Bob</strong>, which used an early version of Agent technology internally referred to as "Microsoft Actor." It was the code used in initial version of the Office Assistant in <?php echo $this->stencil->addLink('Office 97', 'SW'); ?>. Microsoft Agent was subsequently created by Tandy Trower in an attempt to offer technology that was more flexible and available to third-party developers to include in their applications and web pages. The software release also included four interactive characters as well as a utility that enables developers to assemble their own characters and interactions.</p>
        <p>Microsoft Agent replaced the original Microsoft Bob code in <?php echo $this->stencil->addLink('Office 2000', 'SW'); ?>, although this use did not include Agent's much-touted speech synthesis or recognition capabilities or any of the four Microsoft Agent characters. Instead the Office team created their own characters including one dubbed "Clippit" or "Clippy". However, Bob Actors or Office 97 assistants are incompatible with Office 2000 and later versions, and vice versa. The current version of Microsoft Agent was quietly released on <?php echo $this->stencil->addLink('MSDN', 'c'); ?> in 1998. Microsoft recently announced that "Microsoft has decided to discontinue development of Microsoft Agent technologies. Beginning with <?php echo $this->stencil->addLink('Windows 7', 'WIN'); ?>, Microsoft Agent will not be included or supported in future versions of the Microsoft Windows operating system. We encourage Microsoft Agent application developers and redistributes to evaluate their activities in light of this decision". Microsoft is no longer offering licenses and no longer distributes the SDK. (Due to customer feedback, Microsoft has decided to provide an installation package of the Microsoft Agent core components for use on Windows 7).</p>
        <p>Microsoft Agent characters are stored in files of the <code>.ACS</code> extension, and can be stored in a number of compressed <code>.ACF</code> files for better <?php echo $this->stencil->addLink('World Wide Web', 'WD'); ?> distribution. Microsoft Office 97 and Microsoft Bob Actor characters are stored in files of the <code>.ACT</code> extension.</p>
        <p>The speech engine itself is driven by the <strong>Microsoft Speech API (SAPI)</strong>, version 4 and above. Microsoft SAPI provides a control panel for easily installing and switching between various available Text to Speech and Speech to Text engines, as well as voice training and scoring systems to improve the quality and accuracy of both engines.</p>
        <p>Microsoft provides four agent characters for free, which can be downloaded from the Microsoft Agent website. These are called Peedy, Merlin, Genie, and Robby. Some characters also shipped with Microsoft Office up to version 2003 as the Office Assistants and with <?php echo $this->stencil->addLink('Windows XP', 'WIN'); ?> as search assistants. New Agent characters can also be created using Microsoft's development tools, including the Agent Character Editor. Agents can be embedded in software with <?php echo $this->stencil->addLink('Visual Basic for Applications', 'languages/basic'); ?> and in web pages with <?php echo $this->stencil->addLink('VBScript', 'languages/basic'); ?>, and automated tools for the purpose of simplifying this exist. However, web page agents are only compatible with <?php echo $this->stencil->addLink('Internet Explorer', 'WB'); ?>, since alternative browsers like <?php echo $this->stencil->addLink('Opera', 'WB'); ?> or <?php echo $this->stencil->addLink('Mozilla Firefox', 'WB'); ?> do not support <?php echo $this->stencil->addLink('ActiveX', 'IT'); ?>. Additionally, users of <?php echo $this->stencil->addLink('Windows Me', 'WIN'); ?>, <?php echo $this->stencil->addLink('Windows 2000', 'WIN'); ?>, <?php echo $this->stencil->addLink('Windows XP', 'WIN'); ?>, and above or owners of <?php echo $this->stencil->addLink('Microsoft Office 2000', 'SW'); ?> and up are the only ones who have Agent software pre-loaded on their computers; others have to download the software and install it manually.</p>
    </div>
</div>