<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('JScript.NET'); ?>
        <p><strong>JScript NET</strong> is a <?php echo $this->stencil->addLink('.NET', 'L'); ?> programming language developed by <?php echo $this->stencil->addLink('Microsoft', 'C'); ?>.</p>
        <p>The primary differences between <?php echo $this->stencil->addLink('JScript', 'JS'); ?> and JScript.NET can be summarised as follows:</p>
        <p>Firstly, JScript is a scripting language, and as such programs (or more suggestively, scripts) can be executed without the need to compile the code first. This is not the case with the JScript.NET command-line compiler, since this next-generation version relies on the .NET Common Language Runtime (CLR) for execution, which requires that the code be compiled to Common Intermediate Language (CIL), formerly called Microsoft Intermediate Language (MSIL), code before it can be run. Nevertheless, JScript .NET still provides full support for interpreting code at runtime (e.g., via the Function constructor or the eval function) and indeed the interpreter can be exposed by custom applications hosting the JScript .NET engine via the VSA interfaces.</p>
        <p></p>Secondly, JScript has a strong foundation in Microsoft's ActiveX / COM technologies, and relies primarily on ActiveX components to provide much of its functionality (including database access via [ADO], file handling, etc.), whereas JScript.NET uses the <?php echo $this->stencil->addLink('.NET Framework', 'L'); ?> to provide equivalent functionality. For backwards-compatibility (or for where no .NET equivalent library exists), JScript.NET still provides full access to ActiveX objects via .NET / COM interop using both the ActiveXObject constructor and the standard methods of the .NET Type class.</p>
        <p>Although the .NET Framework and .NET languages such as <?php echo $this->stencil->addLink('C#', 'L'); ?> and <?php echo $this->stencil->addLink('Visual Basic.NET', 'L'); ?> have seen widespread adoption, JScript.NET has never received much attention, by the media or by developers. It is not supported in Microsoft's premier development tool, Visual Studio .NET. However, ASP.NET supports JScript.NET.</p>
    </div>
</div>
