<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('PHPDocumentor'); ?>
        <p><strong>phpDocumentor</strong> is an open source documentation generator written in <?php echo $this->stencil->addLink('PHP', 'L'); ?>.</p>
        <p>It automatically parses PHP source code and produces readable API and source code documentation in a variety of formats. phpDocumentor generates documentation based on <strong>PHPDoc-formatted</strong> comments and the structure of the source code itself. It supports documentation of both object-oriented and procedural code. phpDocumentor can create documentation in <?php echo $this->stencil->addLink('HTML', 'WD'); ?>, <?php echo $this->stencil->addLink('PDF', 'IT'); ?>, <strong>CHM</strong> or <strong>Docbook</strong> formats. It can be used from the command line or via a web interface. It has support for linking between documentation, incorporating user level documents like tutorials, and creation of highlighted source code with cross referencing to PHP general documentation. phpDocumentor is able to parse all PHP syntax and supports PHP4 and PHP5, although legacy phpDocumentor 1.4.4 does not support all features of PHP 5.3. It is an open source project and is distributed under the terms of the GNU Lesser General Public License (LGPL).</p>
        <p>In March 2012, it was revealed that the <strong>DocBlox</strong> project was merged with the 1.x branch of phpDocumentor, resulting in a new major version release of phpDocumentor; phpDocumentor 2. The first alpha was released on 16 March 2012. Unlike its version 1 predecessor, phpDocumentor 2 supports syntax for PHP 5.3 and newer. It also includes several speed and performance improvements.</p>
        <br />
        <p><strong>The PHPDocumentor website:</strong> <?php echo $this->stencil->addExternalLink('phpdoc.org', 'http://www.phpdoc.org'); ?></p>
    </div>
</div>