<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Adium'); ?>
        <p><strong>Adium</strong> is a free and open source <?php echo $this->stencil->addLink('instant messaging', 'ITS'); ?> client for <?php echo $this->stencil->addLink('OS X', 'OS'); ?> that supports multiple IM networks, including <?php echo $this->stencil->addLink('Windows Live Messenger', 'IM'); ?>, <?php echo $this->stencil->addLink('Yahoo1 Messenger', 'IM'); ?>, <?php echo $this->stencil->addLink('Google Talk', 'IM'); ?>, <?php echo $this->stencil->addLink('AIM', 'IM'); ?>, <?php echo $this->stencil->addLink('ICQ', 'IM'); ?> and <?php echo $this->stencil->addLink('XMPP', 'IM'); ?>. It is written using OS X's <?php echo $this->stencil->addLink('Cocoa', 'MD'); ?> API, and it is released under the <?php echo $this->stencil->addLink('GNU General Public License', 'LIC'); ?> and many other licenses for components that are distributed with Adium.</p>
        <p>Adium was created by college student <strong>Adam Iser</strong>, and the first version, "Adium 1.0", was released in September 2001 and supported only AIM. The version numbers of Adium since then have followed a somewhat unusual pattern. There were several upgrades to Adium 1.0, ending with Adium 1.6.2c.</p>
        <p>At this point, the Adium team began a complete rewrite of the Adium code, expanding it into a multiprotocol messaging program. <?php echo $this->stencil->addLink('Pidgin', 'IM'); ?>'s (formerly "<strong>Gaim</strrong>") <code>libpurple</code> (then called "<code>libgaim</code>") library was implemented to add support for IM protocols other than AIM - since then, the Adium team mostly works on the GUI. The Adium team originally intended to release these changes as "Adium 2.0". However, Adium was eventually renamed to "Adium X" and released at version 0.50, being considered "halfway to a 1.0 product". Adium X 0.88 was the first version compiled as a universal binary, allowing it to run natively on Intel-based Macs.</p>
        <p>After version Adium X 0.89.1, however, the team finally decided to change the name back to "Adium", and, as such, "Adium 1.0" was released on 2 February 2007.</p>
        <p><?php echo $this->stencil->addLink('Apple Inc', 'C'); ?> used Adium X 0.89.1's build time in <?php echo $this->stencil->addLink('Xcode', 'IDE'); ?> 2.3 as a benchmark for comparing the performance of the Mac Pro and Power Mac G5 Quad, and Adium 1.2's build time in Xcode 3.0 as a benchmark for comparing the performance of the eight-core Mac Pro and Power Mac G5 Quad.</p>
        <p></p>On 4 November 2014, Adium scored 6 out of 7 points on the Electronic Frontier Foundation's secure messaging scorecard. It lost a point because there has not been a recent independent code audit.</p>
    </div>
</div>