<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Trillian'); ?>
        <p><strong>Trillian</strong> is a proprietary multiprotocol <?php echo $this->stencil->addLink('instant messaging', 'ITS'); ?> application for <?php echo $this->stencil->addLink('Microsoft Windows', 'OS'); ?>, <?php echo $this->stencil->addLink('Mac OS X', 'OS'); ?>, <?php echo $this->stencil->addLink('Linux', 'OS'); ?>, <?php echo $this->stencil->addLink('Android', 'OS'); ?>, <?php echo $this->stencil->addLink('iOS', 'OS'); ?>, <?php echo $this->stencil->addLink('BlackBerry OS', 'OS'); ?>, and the <?php echo $this->stencil->addLink('Web', 'WD'); ?>, created by <strong>Cerulean Studios</strong>. It can connect to multiple IM services, such as <?php echo $this->stencil->addLink('AIM', 'IM'); ?>, <?php echo $this->stencil->addLink('ICQ', 'IM'); ?>, <?php echo $this->stencil->addLink('Windows Live Messenger', 'IM'); ?>, <?php echo $this->stencil->addLink('Yahoo! Messenger', 'IM'); ?>, <?php echo $this->stencil->addLink('IRC', 'IPA'); ?>, <?php echo $this->stencil->addLink('Bonjour', 'IM'); ?>, <?php echo $this->stencil->addLink('XMPP', 'IM'); ?>, and <?php echo $this->stencil->addLink('Skype', 'ITS'); ?> networks; as well as social networking sites, such as <?php echo $this->stencil->addLink('Facebook', 'URL'); ?>, <?php echo $this->stencil->addLink('Twitter', 'URL'); ?> and <?php echo $this->stencil->addLink('MySpace', 'URL'); ?>; and email services, such as <?php echo $this->stencil->addLink('POP3', 'IPA'); ?>, <?php echo $this->stencil->addLink('IMAP', 'IPA'); ?>, <?php echo $this->stencil->addLink('Gmail', 'URL'); ?>, <?php echo $this->stencil->addLink('Hotmail', 'URL'); ?> and <?php echo $this->stencil->addLink('Yahoo! Mail', 'URL'); ?>.</p>
        <p>Initially released 1 July 2000, as a freeware IRC client, the first commercial version (Trillian Pro 1.0) was published on 10 September 2002. The program was named after Trillian, a fictional character in <strong>The Hitchhiker's Guide to the Galaxy</strong> by <strong>Douglas Adams</strong>. A previous version of the official web site even had a tribute to Douglas Adams on its front page.</p>
        <p></p>On 14 August 2009, Trillian Astra (4.0) for Windows was released, along with its own Astra network. Trillian Astra has a free version, and a premium version with extra features.</p>
        <p></p>On 18 November 2009, the first mobile version of Trillian was launched for <?php echo $this->stencil->addLink('iPhone', 'ITH'); ?>. As of 2010, final builds for Android, BlackBerry, and Apple iOS were available for their markets (Market, App World and App Store respectively).</p>
        <p></p>Trillian 5 for Windows was released in May 2011.</p>
    </div>
</div>