<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Dynamic Systems Development Method (DSDM)'); ?>
        <p><strong>Dynamic Systems Development Method (DSDM)</strong> is an <?php echo $this->stencil->addLink('agile', 'PM'); ?> project delivery framework, primarily used as a software development method. First released in 1994, DSDM originally sought to provide some discipline to the <?php echo $this->stencil->addLink('Rapis Application Development', 'PMM'); ?> (RAD) method. In 2007 DSDM became a generic approach to project management and solution delivery. DSDM is an iterative and incremental approach that embraces principles of Agile development, including continuous user / customer involvement.</p>
        <p>DSDM fixes cost, quality and time at the outset and uses the <?php echo $this->stencil->addLink('MoSCoW', 'PM'); ?> prioritisation of scope into musts, shoulds, coulds and won't haves to adjust the project deliverable to meet the stated time constraint. DSDM is one of a number of Agile methods for developing software and non-IT solutions, and it forms a part of the <?php echo $this->stencil->addLink('Agile Alliance', 'C'); ?>.</p>
        <p>In 2007, DSDM was rebranded '<strong><em>DSDM Atern</em></strong>'. The name Atern was a shortening of Arctic tern - a collaborative bird that can travel vast distances and epitomises many facets of the method which are natural ways of working e.g. prioritisation and collaboration.</p>
        <p>In 2014, DSDM dropped the branding 'Atern' and reverted to its original name in the latest version of the method in the 'DSDM Agile Project Framework' positioned as "an ideal wrapper for more limited Agile frameworks... DSDM is often used to provide the full 'project' focus to compliment Scrum's team focussed product development process.". At the same time the new DSDM manual recognised the need to operate alongside other frameworks for service delivery (esp. <?php echo $this->stencil->addLink('ITIL', 'PM'); ?>) <?php echo $this->stencil->addLink('PRINCE2', 'Pm'); ?>, Managing Successful Programmes, and <?php echo $this->stencil->addLink('PMI-BOK', 'PM'); ?>. The previous version (DSDM 4.2) had only contained guidance on how to use DSDM with <?php echo $this->stencil->addLink('Extreme Programming', 'PMA'); ?>.</p>
    </div>
</div>
