<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Windows 2000'); ?>
        <p><?php echo $this->stencil->addLink('Microsoft', 'C'); ?> released various editions of Windows 2000 for different markets and business needs: Professional, Server, Advanced Server and Datacenter Server. Each was packaged separately.</p>
        <p><strong></p>Windows 2000 Professional</strong> was designed as the desktop operating system for businesses and power users. It is the client version of Windows 2000. It offers greater security and stability than many of the previous Windows desktop operating systems. It supports up to two processors, and can address up to 4GB of RAM. The system requirements are a Pentium processor (or equivalent) of 133 MHz or greater, at least 32MB of RAM, 650MB of hard drive space, and a CD-ROM drive (recommended: Pentium II, 128MB of RAM, 2GB of hard drive space, and CD-ROM drive).</p>
        <p><strong>Windows 2000 Server</strong> shares the same user interface with Windows 2000 Professional, but contains additional components for the computer to perform server roles and run infrastructure and application software. A significant new component introduced in the server versions is Active Directory, which is an enterprise-wide directory service based on LDAP (Lightweight Directory Access Protocol). Additionally, Microsoft integrated Kerberos network authentication, replacing the often-criticised NTLM (NT LAN Manager) authentication system used in previous versions. This also provided a purely transitive-trust relationship between Windows 2000 domains in a forest (a collection of one or more Windows 2000 domains that share a common schema, configuration, and global catalog, being linked with two-way transitive trusts). Furthermore, Windows 2000 introduced a Domain Name Server which allows dynamic registration of IP addresses. Windows 2000 Server supports up to 4 processors and 4GB of RAM, with a minimum requirement of 128MB of RAM and 1GB hard disk space, however requirements may be higher depending on installed components.</p>
        <p><strong>Windows 2000 Advanced Server</strong> is a variant of Windows 2000 Server operating system designed for medium-to-large businesses. It offers clustering infrastructure for high availability and scalability of applications and services, including support for up to 8 CPUs, a main memory amount of up to 8GB on Physical Address Extension (PAE) systems and the ability to do 8-way SMP. It supports TCP/IP load balancing and enhanced two-node server clusters based on the Microsoft Cluster Server (MSCS) in <?php echo $this->stencil->addLink('Windows NT Server 4.0', 'WIS'); ?> Enterprise Edition. System requirements are similar to those of Windows 2000 Server, however they may need to be higher to scale to larger infrastructure.</p>
        <p><strong>Windows 2000 Datacenter Server</strong> is a variant of Windows 2000 Server designed for large businesses that move large quantities of confidential or sensitive data frequently via a central server. Like Advanced Server, it supports clustering, failover and load balancing. Its minimum system requirements are normal, but it was designed to be capable of handing advanced, fault-tolerant and scalable hardware—for instance computers with up to 32 CPUs and 32GB RAM, with rigorous system testing and qualification, hardware partitioning, coordinated maintenance and change control. System requirements are similar to those of Windows 2000 Advanced Server, however they may need to be higher to scale to larger infrastructure. Windows 2000 Datacenter Server was released to manufacturing on 11 August 2000 and launched on 26 September 2000. This edition was based on Windows 2000 with Service Pack 1 and was not available at retail.</p>
    </div>
</div>