<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Lean Project Management'); ?>
        <p><strong>Lean Project Management</strong> is the comprehensive adoption of other lean concepts like lean construction, <?php echo $this->stencil->addLink('lean manufacturing', 'PML'); ?> and lean thinking into a Project Management context. Lean Project Management has many ideas in common with other lean concepts; however, the main principle of Lean Project Management is delivering more value with less waste in a project context. Lean project management has many techniques that can be applied to projects and one of main methods is standardisation. Key techniques are those "inherited" from <?php echo $this->stencil->addLink('Agile software development', 'PM'); ?> like: blame free employee involvement, the need for a strong facilitator, pipelining, etc.</p>
        <p>Lean Project Management is the method used to plan and execute a lean (improvement) project. The are many ways to do this, but the two most prevalent are to use <?php echo $this->stencil->addLink('6 Sigma', 'PM'); ?> DMAIC method or use the Deming Cycle (Called the "A3" since the steps are recorded on an A3 size paper). Some companies are 6 Sigma Companies and used 6 Sigma Black Belts to take an improvement project through the steps of Define, Measure, Analyse, Improve, and Control. Other companies use the A3 Problem solving Process which includes the statement of the problem, the current situation, the root cause of the problem, suggest alternative solutions, suggest a recommended solution and have a cost benefit analysis. This information would fit all on one A3 size sheet of paper.</p>
        <p>Generally, these methods allow the project team to follow a disciplined method to measure the current state, define the future state, and put into place countermeasures to improve the process. Associated with the project are metrics that are measured, as well as foundational lean elements that are implemented to improve those metrics. Either method is helpful in achieving better results for the project outcome.</p>
        <p>One of the main goals of lean project management is creation and removal of bottlenecks in the production process in order to push process along and accelerate growth. In this way, company teams become more productive. A type of lean project management is called Kanban. Kanban, like other facets of lean project management, makes you more productive by limiting multitasking, keeping your work uninterrupted, urging you to plan ahead, encouraging you to tackle larger tasks first, and to stop just starting and actually finish the projects you've begun.</p>
    </div>
</div>
