<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('iPad 3'); ?>
        <p>The third generation iPad (originally marketed as <strong>The new iPad</strong>, retrospectively marketed as the <strong>iPad 3</strong>) is a tablet computer, developed and marketed by <?php echo $this->stencil->addLink('Apple Inc', 'C'); ?>. The third device in the <?php echo $this->stencil->addLink('iPad', 'ITH'); ?> line of tablets, it added a <?php echo $this->stencil->addLink('Retina display', 'ITH'); ?>, the new Apple A5X chip with a quad-core graphics processor, a 5 megapixel camera, HD 1080p video recording, voice dictation, and support for LTE networks in North America. It shipped with [iOS 5.1], which also provides a platform for audio-visual media, including electronic books, periodicals, films, music, computer games, presentations and web content.</p>
        <p>In the US and Canada, nine variations of the third generation iPad were offered, compared to six in the rest of the world, although some countries had only the Wi-Fi only model. Each variation was available with black or white front glass panels, with options for 16, 32, or 64 GB of storage. In North America, connectivity options were Wi-Fi only, Wi-Fi + 4G (LTE) on Verizon, AT&amp;T, Telus, Rogers, or Bell. For the rest of the world outside North America, connectivity options are Wi-Fi only (on the Wi-Fi model) or Wi-Fi + 3G (on the Wi-Fi + Cellular model), with the latter unavailable in some countries, as 4G (LTE) connectivity for the device is not available outside North America. The Wi-Fi + Cellular model includes GPS capability.</p>
        <p>Initially, the cellular version was titled and marketed worldwide as the "Wi-Fi + 4G" model, but due to lack of 4G (LTE) connectivity outside of North America, Apple later rebranded and altered their marketing to call this the "Wi-Fi + Cellular" model.</p>
        <p>The tablet was released in ten countries on 16 March 2012. It gained mostly positive reviews, earning praise for its <?php echo $this->stencil->addLink('Retina display', 'ITH'); ?>, processor and 4G (LTE) capabilities. However, controversy arose when the LTE incompatibilities became known. Three million units were sold in the first three days.</p>
        <p>After only 221 days of official availability, the third generation iPad was discontinued on 23 October 2012, following the announcement of the [fourth generation] iPad.</p>
    </div>
</div>