<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Mac OS X Leopard'); ?>
        <p><strong>Mac OS X Leopard</strong> (version 10.5) is the sixth major release of <?php echo $this->stencil->addLink('Mac OS X', 'OS'); ?>, <?php echo $this->stencil->addLink('Apple', 'C'); ?>'s desktop and server operating system for <?php echo $this->stencil->addLink('Macintosh', 'ITH'); ?> computers. Leopard was released on 26 October 2007 as the successor of <?php echo $this->stencil->addLink('Mac OS X Tiger', 'OSX'); ?> (version 10.4), and is available in two editions: a desktop version suitable for personal computers, and a server version, <?php echo $this->stencil->addLink('Mac OS X Server', 'OSS'); ?>. It retailed for $129 for the desktop version and $499 for Server. Leopard was superseded by <?php echo $this->stencil->addLink('Mac OS X Snow Leopard', 'OSX'); ?> (version 10.6). Leopard is the final version of Mac OS X to support the <?php echo $this->stencil->addLink('PowerPC', 'ITH'); ?> architecture as Snow Leopard functions solely on <?php echo $this->stencil->addLink('Intel', 'C'); ?> based Macs.</p>
        <p>According to Apple, Leopard contains over 300 changes and enhancements over its predecessor, <?php echo $this->stencil->addLink('Mac OS X Tiger', 'OSX'); ?>, covering core operating system components as well as included applications and developer tools. Leopard introduces a significantly revised desktop, with a redesigned Dock, Stacks, a semitransparent menu bar, and an updated Finder that incorporates the Cover Flow visual navigation interface first seen in iTunes. Other notable features include support for writing 64-bit graphical user interface applications, an automated backup utility called Time Machine, support for Spotlight searches across multiple machines, and the inclusion of Front Row and Photo Booth, which were previously included with only some Mac models.</p>
        <p>Apple missed Leopard's release time frame as originally announced by Apple's CEO <?php echo $this->stencil->addLink('Steve Jobs', 'P'); ?>. When first discussed in June 2005, Jobs had stated that Apple intended to release Leopard at the end of 2006 or early 2007. A year later, this was amended to Spring 2007 however on 12 April 2007, Apple issued a statement that its release would be delayed until October 2007 because of the development of the <?php echo $this->stencil->addLink('iPhone', 'ITH'); ?>.</p>

        <p>Apple advertised that Mac OS X Leopard has 300+ new features, including:</p>
        <ul>
            <li>A new and improved Automator, with easy starting points to easily start a workflow. It also can quickly create or edit workflows with new interface improvements. Now it can use a new action called "Watch Me Do" that lets you record a user action (like pressing a button or controlling an application without built-in Automator support) and replay as an action in a workflow. It can create more useful Automator workflows with actions for RSS feeds, iSight camera video snapshots, PDF manipulation, and much more.</li>
            <li>Back to My Mac, a feature for MobileMe users that allows users to access files on their home computer while away from home via the internet.</li>
            <li>Boot Camp, a software assistant allowing for the installation of other operating systems, such as Windows XP (SP2 or later) or Windows Vista, on a separate partition (or separate internal drive) on Intel-based Macs.</li>
            <li>Dashboard enhancements, including Web Clip, a feature that allows users to turn a part of any Web page displayed in Safari into a live Dashboard widget, and Dashcode to help developers code widgets.</li>
            <li>New Desktop, comprises a redesigned 3-D dock with a new grouping feature called Stacks, which displays files in either a "fan" style, "grid" style, or (since 10.5.2) a "list" style. R.L. Prior, on the ThinkMac blog, criticized the shelf-like Dock along with a number of other changes to the user interface.</li>
            <li>Dictionary can now search Wikipedia, and a dictionary of Apple terminology as well. Also included is the Japanese-language dictionary Daijisen, Progressive E-J and Progressive J-E dictionaries, and the 25,000-word thesaurus Tsukaikata no Wakaru Ruigo Reikai Jiten, all of which are provided by the Japanese publisher Shogakukan.</li>
            <li>A redesigned Finder, with features similar to those seen in iTunes 7, including Cover Flow and a Source list-like sidebar.</li>
            <li>Front Row has been reworked to closely resemble the interface of the original Apple TV.</li>
            <li>iCal calendar sharing and group scheduling as well as syncing event invitations from Mail. The icon also reflects the current date even when the application is not running. In previous versions of Mac OS X, the icon would show July 17 in the icon any time the application was not running but the current date when the application was running.</li>
            <li>iChat enhancements, including multiple logins, invisibility, animated icons, and tabbed chats, similar to features present in Pidgin, Adium and the iChat plugin Chax; iChat Theater, allowing users to incorporate images from iPhoto, presentations from Keynote, videos from QuickTime, and other Quick Look features into video chats; and Backdrops, which are similar to chroma keys, but use a real-time difference matte technique which does not require a green or blue screen. iChat also implements screen sharing, a feature previously available with Apple Remote Desktop.</li>
            <li>Mail enhancements including the additions of RSS feeds, Stationery, Notes, and to-dos. To-dos use a system-wide service that is available to all applications.</li>
            <li>Network file sharing improvements include more granular control over permissions, consolidation of AFP, FTP and SMB sharing into one control panel, and the ability to share individual folders, a feature that had not been available since Mac OS 9.</li>
            <li>Parental controls now include the ability to place restrictions on use of the Internet and to set parental controls from anywhere using remote setup.</li>
            <li>Photo Booth enhancements, including video recording with real-time filters and blue/green-screen technology.</li>
            <li>Podcast Capture, an application allowing users to record and distribute podcasts. It requires access to a computer running Mac OS X Server with Podcast Producer.</li>
            <li>Preview adds support for annotation, graphics, extraction, search, markup, Instant Alpha and size adjustment tools.</li>
            <li>Quick Look, a framework allowing documents to be viewed without opening them in an external application and can preview it in full screen. Plug-ins are available for Quick Look so that you can also view other files, such as Installer Packages.</li>
            <li>Safari 3, which includes Web Clip.</li>
            <li>Spaces, an implementation of virtual desktops (individually called "Spaces"), allows multiple desktops per user, with certain applications and windows in each desktop. Users can organize certain Spaces for certain applications (e.g., one for work-related tasks and one for entertainment) and switch between them. Exposé works inside Spaces, allowing the user to see at a glance all desktops on one screen.) Users can create and control up to 16 spaces, and applications can be switched between each one, creating a very large workspace. The auto-switching feature in Spaces has annoyed some of its users. Apple added a new preference in 10.5.2 which disabled this feature, but there were still bugs found while switching windows. In 10.5.3, this problem was addressed and was no longer an issue.</li>
            <li>Spotlight incorporates additional search capabilities such as Boolean operators, as well as the ability to search other computers (with permissions).</li>
            <li>Time Machine, an automated backup utility which allows the user to restore files that have been deleted or replaced by another version of a file. Though generally lauded in the press as a step forward for data recovery, Time Machine has been criticized in multiple publications for lacking the capabilities of third-party backup software. Analyzing the feature for TidBITS, Joe Kissell pointed out that Time Machine does not create bootable copies of backed-up volumes, does not back up to AirPort Disk hard drives and will not back up FileVault encrypted home directories until the user logs out, concluding that the feature is "pretty good at what it does" but he will only use it as part of a "broader backup strategy". One of these issues has been resolved, however; On March 19, 2008, updates were released for AirPort and Time Machine, allowing for Time Machine to use a USB hard disk which has been connected to an AirPort Extreme Base Station.</li>
            <li>Universal Access enhancements: significant improvements to applications including VoiceOver, along with increased support for Braille, closed captioning and a new high‐quality Speech synthesis voice.</li>
            <li>Many changes to the user interface, such as a transparent menu bar, new icons, and a 3D Dock. As well as this, the Apple icon is now black instead of blue. R.L. Prior, on the ThinkMac blog, criticized a number of changes to Leopard's user interface, including the transparent menu bar and the new folder icons. Decreased transparency of the menu bar, along with the ability to disable the menu bar transparency were added with the 10.5.2 release on February 11, 2008.</li>
            <li>Russian language support, bringing the total to 18 languages.</li>
            <li>Leopard removes support for Classic applications.</li>
            <li>Introduced the Alex voice to VoiceOver. It is the most natural and understandable voice yet, says Apple.</li>
        </ul>
    </div>
</div>