<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Mac OS X Lion'); ?>
        <p><strong>Mac OS X Lion (version 10.7)</strong>, marketed as <strong>OS X Lion</strong> is the eighth major release of <?php echo $this->stencil->addLink('Mac OS X', 'OS'); ?>, <?php echo $this->stencil->addLink('Apple', 'C'); ?>'s desktop and server operating system for <?php echo $this->stencil->addLink('Macintosh', 'ITH'); ?> computers.</p>
        <p>A preview of Lion was publicly unveiled at the "Back to the Mac" Apple Special Event on 20 October 2010. It brings many developments made in Apple's <?php echo $this->stencil->addLink('iOS', 'OS'); ?>, such as an easily navigable display of installed applications, to the Mac, and includes support for the Mac App Store, as introduced in <?php echo $this->stencil->addLink('Mac OS X Snow Leopard', 'OSX'); ?> version 10.6.6. On 24 February 2011, the first developer's preview of Lion (11A390) was released to subscribers to the Apple Developer program. Other developer previews were subsequently released, with Lion Preview 4 (11A480b) being released at WWDC 2011.</p>
        <p>Lion was released to manufacturing on 1 July 2011, followed by its final release via the Mac App Store on 20 July 2011. Apple reported over one million Lion sales on the first day of its release. As of October 2011, Mac OS X Lion has sold over six million copies worldwide.</p>

        <p>Some new features were announced at the "Back to the Mac" keynote in October 2010, and the Apple website was updated in February 2011, with more details. Other features were announced at the WWDC 2011 keynote or on Apple's Mac OS X Lion Web site after the keynote. Apple states that there are over 250 new or changed features in Lion, including:</p>
        <ul>
            <li>Address Book uses an iPad-like user interface. It also includes improved Yahoo support and FaceTime calling.</li>
            <li>AirDrop - Lion-to-Lion direct file sharing via Wi-Fi Direct. No wireless access point required.</li>
            <li>Address space layout randomization – Address space layout randomization (ASLR), a security technique that puts important data in unpredictable locations, making it harder to target known weaknesses, is available for 32-bit applications, and "has been improved for all applications", in Lion.</li>
            <li>Apple Push Notification Service – Send over-the-air alerts, such as news updates or social networking status changes, using Apple's Push Notification service to applications that support APNS. APNS allows Mac OS X Lion and iOS clients to receive push changes to items such as mail, calendar and contacts from a configured OS X Lion Server.</li>
            <li>Auto-correction behaves much like on iOS devices, displaying an iOS-like popup box.</li>
            <li>Auto Save - As in iOS, documents in applications written to use Auto Save are saved automatically so users do not have to worry about manually managing their documents. The Auto Save feature significantly alters traditional workflow patterns and is a controversial addition to the system.</li>
            <li>Emoji support - Apple has added a new Emoji font commonly used in chat to express ideograms.</li>
            <li>Exposé in the Dock, a way of activating Exposé for a single application from the Dock, a feature added in Mac OS X 10.6, is altered. One must double-tap with two fingers on a dock icon to initiate single application exposé, or simply right-click or control-click and select Show All Windows.</li>
            <li>FaceTime comes bundled with Lion.</li>
            <li>FileVault offers full disk encryption and added security with XTS-AES 128 data encryption. Support for FileVault on external hard drives has also been added.</li>
            <li>Finder improvements – Finder search allows multiple search criteria to be specified without creating a smart folder, Finder search offers suggestions, files can be grouped by various attributes, and one can merge files under two folders with the same name – a prompt appears asking to replace or keep both files. The navigation sidebar lost the ability to show the specific icon of a map or volume (by default; there is a hack to still add the old ability), instead it shows a grey standard map icon.</li>
            <li>Font Book 3-Font Book 3 provides more flexible displays of character glyphs supplied by a particular font face. Duplicate font files are flagged with a warning icon, and can be fixed automatically or resolved manually.</li>
            <li>Full-screen apps – Native, system-wide support for full-screen applications running in their own space. Supporting applications display a new button at the top right of application window, this button opens applications in full-screen mode. However, full screen mode is not supported for dual screen setups.</li>
            <li>High-quality multilingual speech voices – users can download new high-quality voices in more than forty languages and dialects.</li>
            <li>iCal has an updated user interface, an annual view, and support for a full-screen view.</li>
            <li>iChat has support for logging into Yahoo! Messenger. Users can audio- and video-chat with other iChat users using their Yahoo! accounts.</li>
            <li>Languages/Localization – Arabic, Czech, Turkish and Hungarian are added as full system languages, to make the total number of twenty-two languages available in Mac OS X.</li>
            <li>Launchpad - An application launcher that displays an iOS-like icon grid of installed applications. It features the ability to make multiple pages and group apps into folders that function the same as folders in iOS.</li>
            <li>Mac App Store - An application store built in the image of the iOS App Store. Like in iOS, it provides ways for shoppers to discover apps, one-click installation of apps, and one-click updates of all or selected installed applications. Despite being announced as a future feature of Lion, the Mac App Store was released for Mac OS X Snow Leopard on 6 January 2011, as it was bundled with the Mac OS X 10.6.6 update.</li>
            <li>Mail 5 - Uses an iPad-like user interface, has a fullscreen-optimized view, uses chronological "Conversations" to organize messages, and supports Exchange 2010 (but not through the Exchange ActiveSync protocol, as iOS).</li>
            <li>Mission Control replaces the "All windows" Exposé feature. It gives an overview of all running applications just like "All windows" but groups windows from the same application. At the top of the screen it gives quick access to the Dashboard, Spaces, and running full-screen applications.</li>
            <li>Multi-touch gestures – Similar to iOS, additional gestures performed using a multi-touch input device (e.g. Magic Mouse, Magic Trackpad) allow the user to scroll, swipe to different pages, and enter Mission Control. While this is not the first official multi-touch support for Mac OS X, it has been expanded; other frameworks, such as Lux, have already created multi-touch support.</li>
            <li>Multi-User Screen Sharing-The built-in Screen Sharing feature allows remote users to log into a separate user account from the one that is currently logged in. That means that while one user is logged into a machine, a second user can log into the same machine remotely, seeing their own desktop and user environment.</li>
            <li>Preview gains several features, including full-screen support and the ability to sign a document just by holding a signed piece of paper up to the camera.</li>
            <li>Profile Manager provides several features, including push notification-based management of OS X Lion and above.</li>
            <li>QuickTime re-incorporates some features from QuickTime Pro. New features cited include Copy/Paste, Insert Clip, Crop Video, Rotate Video, Resize, Trim, and more Export options.</li>
            <li>Recovery Partition – Apple has introduced a recovery partition that includes utilities generally found on the OS X discs. This partition permits the user to restore their computer to its original factory state. It also allows for a new copy of OS X Lion to be installed over the internet.</li>
            <li>Resume - Applications resume in the same state when re-opened as already seen in iOS.</li>
            <li>Safari - With full-screen mode and the new WebKit2 layout engine.</li>
            <li>System Information – This feature is a re-design of System Profiler, which has been completely altered with new views which display graphical information on displays, storage devices, memory usage along with other hardware information. The previous layout remains available by clicking "System Report". Early builds of Lion also used System Information as a replacement for "About This Mac", although the final release reinstated the version of this dialog box found in Snow Leopard.</li>
            <li>Terminal has extra features, including full screen mode.</li>
            <li>TextEdit gains a new graphical toolbar with font selection and text highlighting. The new TextEdit also supports Apple's new automatic file saving and versions technologies.</li>
            <li>Versions - Time Machine-like saving and browsing of past versions of documents for applications written to use Versions.</li>
            <li>Vertical text – Lion supports vertical layouts for East Asian languages.</li>
        </ul>
    </div>
</div>