<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Mac OS X Show Leopard'); ?>
        <p><strong>Mac OS X Snow Leopard (version 10.6)</strong> is the seventh major release of <?php echo $this->stencil->addLink('Mac OS X', 'OS'); ?>, <?php echo $this->stencil->addLink('Apple', 'C'); ?>'s desktop and server operating system for <?php echo $this->stencil->addLink('Macintosh', 'ITH'); ?> computers.</p>
        <p>Snow Leopard was publicly unveiled on 8 June 2009 at the Apple Worldwide Developers Conference. On 28 August 2009, it was released worldwide, and was made available for purchase from Apple's website and its retail stores at the price of US$29 for a single-user license. As a result of the low price, initial sales of Snow Leopard were significantly higher than that of its predecessors. The release of Snow Leopard came nearly two years after the introduction of <?php echo $this->stencil->addLink('Mac OS X Leopard', 'OSX'); ?>, the second longest time span between successive Mac OS X releases (the time span between Tiger and Leopard was the longest).</p>
        <p>Unlike those of previous versions of Mac OS X, the goals of Snow Leopard were improved performance, greater efficiency and the reduction of its overall memory footprint. Addition of new end-user features was not a primary consideration: its name was intended to signify its goal to be a refinement of the previous OS X version, Leopard. Much of the software in Mac OS X was extensively rewritten for this release in order to take advantage fully of modern Macintosh hardware. New programming frameworks, such as OpenCL, were created, allowing software developers to use graphics cards in their applications. This is also the first Mac OS release since System 7.1.1 that does not support Macs using PowerPC processors, as Apple now intends to focus on its current line of Intel-based products. As support for Rosetta was dropped in OS X Lion, Snow Leopard is the last version of Mac OS X that is able to run <?php echo $this->stencil->addLink('PowerPC', 'ITH'); ?> only applications.</p>
        <p>Snow Leopard was succeeded by <?php echo $this->stencil->addLink('Mac OS X Lion', 'OSX'); ?> (version 10.7) on 20 July 2011. Since then, Apple has continued to sell Snow Leopard from its online store for the benefit of users that require Snow Leopard in order to upgrade to later versions of OS X, which have all been distributed through the Mac App Store introduced in the Snow Leopard 10.6.6 update.</p>
        <p>Snow Leopard is the last release of Mac OS X to support the 32-bit Intel Core Solo and Intel Core Duo CPUs.</p>

        <p>Mac OS X Snow Leopard is intended to be a release aimed to refine the existing feature set, expand the technological capabilities of the operating system, and improve application efficiency. Many of the changes involve how the system works in the background and are not intended to be seen by the user. For example, the Finder application was completely rewritten in the <?php echo $this->stencil->addLink('Cocoa', 'SD'); ?> application programming interface. Despite significant changes in the software, users will experience almost no changes in the user interface. Snow Leopard includes the following changes:</p>
        <ul>
            <li>Boot Camp now allows Windows partitions to read and copy files from HFS+ partitions. The new version also adds support for advanced features on Cinema Displays and a new command-line version of the Startup Disk Control Panel.</li>
            <li>The Finder has been completely rewritten in Cocoa to take advantage of the new technologies introduced in Snow Leopard.</li>
            <li>A much smaller OS footprint, taking up about 7 GB less space than Mac OS X Leopard. Some of the recovered disk space (~250 MB) is because printer drivers are now downloaded or installed only as needed, rather than being pre-installed. The default install only contains those drivers needed for existing printers and a small subset of popular printers.</li>
            <li>iChat enhancements include greater resolution video chats in iChat Theater and lowered upload bandwidth requirements.</li>
            <li>Microsoft Exchange support is now integrated into the Mail, Address Book, and iCal applications. However, only Microsoft Exchange 2007 is supported and customers using prior versions of Exchange must either upgrade or use Microsoft Entourage.</li>
            <li>Full multi-touch trackpad support has been added to notebooks prior to those introduced in October 2008. While the original MacBook Air and other early multi-touch trackpad enabled notebooks had support for some gestures, they were unable to use four-finger gestures. This limitation has now been removed in Snow Leopard.</li>
            <li>Preview can infer the structure of a paragraph in a PDF document.</li>
            <li>QuickTime X, the next version of QuickTime player and multimedia framework, has been completely rewritten into a full 64-bit Cocoa application and builds on the media technologies in Mac OS X, such as Core Audio, Core Video, and Core Animation, to deliver playback. Apple has redesigned the QuickTime user interface to resemble the full-screen QuickTime view in prior versions, where the entire window displays the video. The titlebar and playback controls fade in and out as needed. QuickTime X also supports HTTP live streaming and takes advantage of ColorSync to provide high-quality color reproduction. If Snow Leopard is installed on a Mac with an nVidia GeForce 9400M, 320M or GT 330M graphics card, QuickTime X will be able to use its video-decoding capabilities to reduce CPU load.</li>
            <li>Safari 4 features Top Sites, Cover Flow, VoiceOver, expanded standards support, and built-in crash resistance, which prevents browser crashes caused by plug-ins by running them in separate processes. Safari 4 is bundled with Snow Leopard but does not require it, as it is available for free for Mac OS X Tiger and Leopard as well as Windows.</li>
            <li>Time Machine connection establishment and backups are now much faster.</li>
            <li>VoiceOver has also been greatly enhanced in Snow Leopard. Reading of web pages is improved with Auto Web Spots — areas of a page automatically designated for quick access. On newer Apple portables, trackpad gestures can be used to control VoiceOver functions, including the "rotor" gesture first seen in VoiceOver for the iPhone 3GS, allowing for the changing of certain VoiceOver navigation options by rotating fingers on the trackpad. Braille Display support is also improved, with Bluetooth displays supported for the first time.</li>
        </ul>

        <p></p>The 10.6.6 update introduced support for the Mac App Store, Apple's digital distribution platform for OS X applications.</p>
    </div>
</div>