<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Mac OS X Tiger'); ?>
        <p><strong>Mac OS X v10.4 Tiger</strong> is the fifth major release of <?php echo $this->stencil->addLink('Mac OS X', 'OS'); ?>, <?php echo $this->stencil->addLink('Apple', 'C'); ?>'s desktop and server operating system for <?php echo $this->stencil->addLink('Mac', 'ITH'); ?> computers. Tiger was released to the public on 29 April 2005 for $129.95 as the successor to <?php echo $this->stencil->addLink('Mac OS X Panther', 'OSX'); ?>. Some of the new features included a fast searching system called Spotlight, a new version of the <?php echo $this->stencil->addLink('Safari', 'WB'); ?> web browser, Dashboard, a new ‘Unified’ theme, and improved support for 64-bit addressing on Power Mac G5s. Tiger shocked executives at <?php echo $this->stencil->addLink('Microsoft', 'C'); ?> by offering a number of features, such as fast file searching and improved graphics processing, that Microsoft had spent several years struggling to add to <?php echo $this->stencil->addLink('Windows', 'OS'); ?> with acceptable performance.</p>
        <p>Tiger was included with all new Macs, and was also available as an upgrade for existing Mac OS X users, or users of supported pre-Mac OS X systems. The server edition, <?php echo $this->stencil->addLink('Mac OS X Server 10.4', 'MSS'); ?>, was also available for some Macintosh product lines. Six weeks after its official release, Apple had delivered 2 million copies of Tiger, representing 16% of all Mac OS X users. Apple claimed that Tiger was the most successful Apple OS release in the company's history. At the WWDC on 11 June 2007, Apple's CEO, <?php echo $this->stencil->addLink('Steve Jobs', 'P'); ?>, announced that out of the 22 million Mac OS X users, more than 67% were using Tiger.</p>
        <p>Apple announced a transition to <?php echo $this->stencil->addLink('Intel x86', 'CPU'); ?> processors during Tiger's lifetime, making it the first Apple operating system to work on Apple–Intel architecture machines. The original Apple TV, released in March 2007, shipped with a customised version of Tiger branded “Apple TV OS” that replaced the usual GUI with an updated version of Front Row.</p>
        <p>Tiger was succeeded by <?php echo $this->stencil->addLink('Mac OS X Leopard', 'OSX'); ?> on 26 October 2007, after 30 months, making Tiger the longest running version of Mac OS X. The last security update released for Tiger users was the 2009-005 update. The next security update, 2009-006 only included support for Leopard and Snow Leopard. The latest supported version of QuickTime is 7.6.4. The latest version of iTunes that can run on Tiger is 9.2.1, because 10.0 only supports Mac OS X Leopard and later. Safari 4.1.3 is the final version for Tiger as of 18 November 2010. Despite not having received security updates since then, Tiger remains popular with Power Mac users and retro computing enthusiasts due to its wide software and hardware compatibility, as it runs on a wide variety of older machines and is the last OS X version that supports Classic Environment, a <?php echo $this->stencil->addLink('Mac OS 9', 'MOS'); ?> compatibility layer.</p>
        <p>Apple advertises that Tiger has over 150 new and improved features, including:</p>
        <ul>
            <li>Spotlight - Spotlight is a full-text and metadata search engine, which can search everything on one's Mac including Microsoft Word documents, iCal calendars and Address Book contact cards. The feature is also used to build the concept of ‘smart folders’ into the Finder. Spotlight will index files as they are saved, so they can be quickly and easily found through a search-as-you-type box in the menu bar. As a side-effect, it adds hidden folders and indexing files to removable media like USB flash drives.</li>
            <li>iChat AV - The new iChat AV 3.0 in Tiger supports up to four participants in a video conference and ten participants in an audio conference. It also now supports communication using the XMPP protocol. A XMPP server called iChat Server is included on Mac OS X Tiger Server.</li>
            <li>Safari RSS - The new Safari 2.0 web browser in Tiger features a built-in reader for RSS and Atom web syndication that can be accessed easily from an RSS button in the address bar of the web browser window. An updated version of Safari, included as part of the free Mac OS X v.10.4.3 update, can also pass the Acid2 web standards test.</li>
            <li>Mail 2 - The new version of Mail.app email client included in Tiger featured an updated interface, "Smart Mailboxes" which utilize the Spotlight search system, parental controls, as well as several other features.</li>
            <li>Dashboard - The Dashboard is a new mini-applications layer based on HTML, CSS, and JavaScript, which returns the desk accessories concept to the Mac OS. These accessories are known as widgets. It comes with several widgets such as Weather, World Clock, Unit Converter, and Dictionary/Thesaurus. More are available for free online. Its similarity to the Konfabulator application caused some criticism.</li>
            <li>Automator - A scripting tool to link applications together to form complex automated workflows (written in AppleScript, Cocoa, or both). Automator comes with a complete library of actions for several applications that can be used together to make a Workflow.</li>
            <li>VoiceOver - accessibility interface that offers the user magnification options, keyboard control and spoken English descriptions of what is happening on screen. VoiceOver enables users with visual impairment the ability to use applications via spoken commands. It also allows a user to work collaboratively with other users on a single Mac by allowing multiple users give voice commands to scroll text, etc. VoiceOver is capable of reading aloud the contents of files including web pages, mail messages and word processing files. The complete keyboard navigation lets the user control the computer with the keyboard rather than mouse, a menu is displayed in a window showing all the available keyboard commands that can be used.</li>
            <li>A complete built-in Dictionary/Thesaurus based on the New Oxford American Dictionary, Second Edition, accessible through an application, Dictionary, a Dashboard widget, and as a system-wide command (see below).</li>
            <li>.Mac syncing - Though this is not a new feature, .Mac syncing in Tiger is much improved over Panther. Syncing tasks in Tiger are now accomplished through the .Mac system preferences pane rather than the iSync application.</li>
            <li>QuickTime 7 - A new version of Apple's multimedia software has support for the new H.264/AVC codec which offers better quality and scalability than other video codecs. This new codec is used by iChat AV for clearer video conferencing. New classes within Cocoa provide full access to QuickTime for Cocoa application developers. The new QuickTime 7 player application bundled with Tiger now includes more advanced audio and video controls as well as a more detailed Information dialog, and the new player has been rebuilt using Apple's Cocoa API to take advantage of the new technologies more easily.</li>
            <li>New Unix features - New versions of cp, mv, and rsync which support files with resource forks. Command-line support for features like the above-mentioned Spotlight are also included.</li>
            <li>Xcode 2.0 - Xcode 2.0, Apple's Cocoa development tool now includes visual modelling, an integrated Apple Reference Library and graphical remote debugging.</li>
            <li>Automator - Automator uses workflows to process repetitive tasks automatically</li>
            <li>Grapher - Grapher is a new application capable of creating 2D and 3D graphs similar to that of Graphing Calculator.</li>
            <li>Dictionary - A dictionary and thesaurus program which uses the New Oxford American Dictionary. It has a fast GUI for displaying the Dictionary, and allows the user to search the dictionary with Spotlight, to print definitions, and to copy and paste text into documents. Dictionary also provides a Dictionary service in the Application menu, and Cocoa and WebKit provides a global keyboard shortcut (ctrl-⌘-D by default) for all applications that display text with them. Its use was furthered in the next version of OS X by providing definitions from Wikipedia. The Dictionary application is a more feature-filled version of the Dictionary widget.</li>
            <li>Quartz Composer - Quartz Composer is a development tool for processing and rendering graphical data.</li>
            <li>AU Lab - AU Lab is a developer application for testing and mixing Audio Units.</li>
        </ul>
    </div>
</div>