<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('iPhone 4'); ?>
        <p>The <strong>iPhone 4</strong> is a smartphone that was designed and marketed by <?php echo $this->stencil->addLink('Apple Inc', 'C'); ?>. Following a number of notable leaks, the iPhone 4 was first unveiled on 7 June 2010, at Apple's Worldwide Developers Conference in San Francisco, and was released on 24 June 2010, in the United States, United Kingdom, France, Germany and Japan. It is the 4th generation of iPhone, succeeding the <?php echo $this->stencil->addLink('iPhone 3GS', 'ITH'); ?> and preceding the very similar <?php echo $this->stencil->addLink('iPhone 4S', 'ITH'); ?>.</p>
        <p>The iPhone 4 introduced a new hardware design to the iPhone line, which Apple's CEO <?php echo $this->stencil->addLink('Steve Jobs', 'P'); ?> touted as the thinnest smartphone in the world at the time; it consisted of an uninsulated stainless steel frame which doubles as an antenna, with internal components situated between chemically strengthened aluminosilicate glass. The iPhone 4 also introduced Apple's new high-resolution "<?php echo $this->stencil->addLink('Retina Display', 'ITH'); ?>"; while maintaining the same physical size and display resolution as its precursors, its liquid crystal display had a pixel density of 326 pixels per inch. The iPhone 4 also introduced Apple's A4 system-on-chip, along with <?php echo $this->stencil->addLink('iOS 4', 'OS'); ?> which notably introduced multitasking functionality and Apple's new FaceTime video chat service. The iPhone 4 was also the first iPhone to include a front-facing camera, and the first to be released in a version for CDMA networks, ending AT&amp;T's period as the exclusive carrier of iPhone products in the United States.</p>
        <p>It was succeeded as Apple's flagship smartphone in 2011 by the iPhone 4S; however, the 4 continued in production until 2013.</p>
        <p>The iPhone 4 received generally positive reception, with critics praising its revamped design and more powerful hardware in comparison to previous models. While it was a market success, with over 600,000 pre-orders within 24 hours, the release of the iPhone 4 was plagued by highly publicised reports that abnormalities in its new antenna design caused the device to lose its cellular signal if held in a certain way.</p>
        <p>The iPhone 4 spent the longest time as Apple's flagship iPhone model at fifteen months, and had the longest lifespan of any iPhone ever produced, spanning close to four years and available in some developing countries until early 2014.</p>
    </div>
</div>