<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Bletchley Park'); ?>
        <p><strong>Bletchley Park</strong> is an estate located in the town of Bletchley, in Milton Keynes, Buckinghamshire, England, and is run by the Bletchley Park Trust as a heritage attraction.</p>
        <p>During the Second World War, Bletchley Park was the site of the United Kingdom's main decryption establishment, the <strong>Government Code and Cypher School (GC&amp;CS)</strong>, where ciphers and codes of several Axis countries were decrypted, most importantly the ciphers generated by the German <strong>Enigma</strong> and <strong>Lorenz</strong> machines.</p>
    </div>
</div>