<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('The GNU Project'); ?>
        <p>The <strong>GNU Project</strong> is a free software, mass collaboration project, announced on 27 September 1983, by <strong>Richard Stallman</strong> at <?php echo $this->stencil->addLink('MIT', 'C'); ?>. Its aim is to give computer users freedom and control in their use of their computers and computing devices, by collaboratively developing and providing software that is based on the following freedom rights: users are free to run the software, share it (copy, distribute), study it and modify it. GNU software guarantees these freedom-rights legally (via its license), and is therefore free software; the use of the word "free" always being taken to refer to freedom.</p>
        <p>In order to ensure that the entire software of a computer grants its users all freedom rights (use, share, study, modify), even the most fundamental and important part, the operating system (including all its numerous utility programs), needed to be written. The founding goal of the project was, in the words of its initial announcement, to develop "<em>a sufficient body of free software [...] to get along without any software that is not free</em>". Stallman decided to call this operating system GNU (a recursive acronym meaning "<strong><em>GNU's not Unix</em><strong>"), basing its design on that of <?php echo $this->stencil->addLink('Unix', 'OS'); ?>; however, in contrast to Unix which was proprietary software, GNU was to be freedom respecting software (free software) that users can use, share, study and modify. Development was initiated in January 1984. The goal of making a completely free software operating system was achieved in 1992 when the third-party Linux kernel was released as free software, under version 2 of the <?php echo $this->stencil->addLink('GNU Public License', 'LIC'); ?>, to be used with the GNU software stack.</p>

        <h2>GNU Manifesto</h2>
        <p>The <?php echo $this->stencil->addLink('GNU Manifesto', 'IT'); ?> was written by <strong>Richard Stallman</strong> to gain support and participation in the GNU Project. In the GNU Manifesto, Stallman listed four freedoms essential to software development: freedom to run a program for any purpose, freedom to study the mechanics of the program and modify it, freedom to redistribute copies, and freedom to improve and change modified versions for public use. To implement these freedoms, users needed full access to code. To ensure code remained free and provide it to the public, Stallman created the <strong>GNU General Public License (<?php echo $this->stencil->addLink('GPL', 'LIC'); ?>)</strong>, which allowed software and the future generations of code derived from it to remain free for public use. Some complications arose, however, when certain software was grandfathered in the law of GPL because of code from which it derived.</p>

        <h2>Copyleft</h2>
        <p><?php echo $this->stencil->addLink('Copyleft', 'LIC'); ?> is what helps maintain free use of this software among other programmers. Copyleft gives the legal right to everyone to use, edit, and redistribute programs or program's code as long as the distribution terms do not change. As a result, any user who obtains the software legally has the same freedoms as the rest of its users do.</p>
        <p>The GNU Project and the <?php echo $this->stencil->addLink('FSF', 'C'); ?> sometimes differentiate between "strong" and "weak" copyleft. "Weak" copyleft programs typically allow distributors to link them together with non-free programs, while "strong" copyleft strictly forbids this practice. Most of the GNU Project's output is released under a strong copyleft, although some is released under a weak copyleft or a permissive free software license.</p>
    </div>
</div>