<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('International Project Management Association (IPMA)'); ?>
        <?php echo $this->stencil->addLogo('IPMA', 'png', 'left'); ?>
        <p>The <strong>International Project Management Association (IPMA)</strong> is a non profit, Swiss registered organization for the promotion of project management internationally. The IPMA is a federation of more than 50 national and internationally oriented project management associations with over 120.000 members world wide as of 2012.</p>
        <p>The association was started in 1965 in Vienna by a European group of managers, and initially established under the name <strong>International Management Systems Association (IMSA)</strong>. It held its first international congress in Vienna in 1967, which was attended by professionals from 30 different countries. In 1979 the association was renamed to International Project Management Association.</p>
        <p></p>IPMA's focus is in the development and promotion of the project management profession. It provides standards and establishes guidelines for the work of project management professionals through the <strong>IPMA Competence Baseline (ICB&reg;)</strong>. The Certification Program is delivered by National Member Associations and/or Certification Bodies in various membership countries. As of 2012 there are more than 150,000 IPMA certified competency based certificates worldwide, which are held by professionals from recognised businesses and organisations around the world.</p>
        <p>With its unique federation approach, IPMA is an umbrella organisation for independent Member Associations from over 50 countries world wide, each of whom represents IPMA in their respective countries.</p>
    </div>
</div>