<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Nokia Corporation'); ?>
        <p><strong>Nokia Corporation</strong> is a Finnish multinational communications and information technology company. Nokia is headquartered in Espoo, Uusimaa, in the greater Helsinki metropolitan area. In 2014, Nokia employed 61,656 people across 120 countries, conducts sales in more than 150 countries and reported annual revenues of around €12.73 billion. Nokia is a public limited liability company listed on the Helsinki Stock Exchange and New York Stock Exchange. It is the world's 274th largest company measured by 2013 revenues according to the Fortune Global 500.</p>
        <p>The company currently focuses on large-scale telecommunications infrastructures, technology development and licensing, and online mapping services. Nokia is also a significant contributor to the mobile telephony industry, having assisted in development of the GSM and LTE standards, and was, for a period, the largest vendor of mobile phones in the world. Nokia's dominance also extended into the smartphone industry through its Symbian platform, but it was soon overshadowed by the growing dominance of Apple's iPhone line and Android devices. Nokia eventually entered into a pact with <?php echo $this->stencil->addLink('Microsoft', 'C'); ?> in 2011 to exclusively use its <?php echo $this->stencil->addLink('Windows Phone', 'OS'); ?> platform on future smartphones.</p>
        <p>In September 2013, Microsoft announced that it would acquire Nokia's mobile phone business as part of an overall deal totalling €5.44 billion (US $7.17 billion). Stephen Elop, Nokia's former CEO, and several other executives joined the new Microsoft Mobile subsidiary of Microsoft as part of the deal, which was completed on 25 April 2014. In November 2014, Nokia began to license product designs and technologies to third-party manufacturers, to enable a continued presence for the Nokia brand in the consumer electronics hardware market.</p>
        <p>On 15 April 2015, Nokia announced that it would acquire the French telecommunications equipment company Alcatel-Lucent for €15.6 billion.</p>
        <p>On 18 June 2015, Nokia's CEO Rajeev Suri revealed that the company plans to re-enter the mobile phone business in 2016.</p>
    </div>
</div>