<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Domain Name'); ?>
        <p>A <strong>domain name</strong> is an identification string that defines a realm of administrative autonomy, authority or control within the <?php echo $this->stencil->addLink('Internet', 'ITN'); ?>. Domain names are formed by the rules and procedures of the <strong>Domain Name System (<?php echo $this->stencil->addLink('DNS', 'IPA'); ?>)</strong>. Any name registered in the DNS is a domain name.</p>
        <p>Domain names are used in various networking contexts and application specific naming and addressing purposes. In general, a domain name represents an <strong>Internet Protocol (<?php echo $this->stencil->addLink('IP', 'IP'); ?>)</strong> resource, such as a personal computer used to access the Internet, a server computer hosting a web site, or the web site itself or any other service communicated via the Internet. In 2014, the number of active domains reached 271 million.</p>
        <p>Domain names are organised in subordinate levels (subdomains) of the DNS root domain, which is nameless. The first-level set of domain names are the <?php echo $this->stencil->addLink('top-level domains', 'ITN'); ?> (TLDs), including the generic top-level domains (gTLDs), such as the prominent domains com, info, net, edu, and org, and the country code top-level domains (ccTLDs). Below these top-level domains in the DNS hierarchy are the second-level and third-level domain names that are typically open for reservation by end-users who wish to connect local area networks to the Internet, create other publicly accessible Internet resources or run web sites. The registration of these domain names is usually administered by domain name registrars who sell their services to the public.</p>
        <p>A <?php echo $this->stencil->addLink('fully qualified domain name', 'ITN'); ?> (FQDN) is a domain name that is completely specified in the hierarchy of the DNS, having no parts omitted.</p>
        <p>Labels in the Domain Name System are case-insensitive, and may therefore be written in any desired capitalisation method, but most commonly domain names are written in lowercase in technical contexts.</p>
    </div>
</div>