<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Voice over IP (VoIP)'); ?>
        <p><strong>Voice over IP (VoIP)</strong> is a methodology and group of technologies for the delivery of voice communications and multimedia sessions over <strong>Internet Protocol (<?php echo $this->stencil->addLink('IP', 'IP'); ?>)</strong> networks, such as the Internet. Other terms commonly associated with VoIP are IP telephony, Internet telephony, broadband telephony, and broadband phone service.</p>
        <p>The term Internet telephony specifically refers to the provisioning of communications services (voice, fax, SMS, voice-messaging) over the public Internet, rather than via the public switched telephone network (PSTN). The steps and principles involved in originating VoIP telephone calls are similar to traditional digital telephony and involve signalling, channel setup, digitisation of the analog voice signals, and encoding. Instead of being transmitted over a circuit-switched network, however, the digital information is packetised, and transmission occurs as IP packets over a packet-switched network. Such transmission entails careful considerations about resource management different from time-division multiplexing (TDM) networks.</p>
        <p>Early providers of voice-over-IP services offered business models and technical solutions that mirrored the architecture of the legacy telephone network. Second generation providers, such as <?php echo $this->stencil->addLink('Skype', 'ITS'); ?>, have built closed networks for private user bases, offering the benefit of free calls and convenience while potentially charging for access to other communication networks, such as the PSTN. This has limited the freedom of users to mix-and-match third-party hardware and software. Third generation providers, such as <?php echo $this->stencil->addLink('Google Talk', 'IM'); ?>, have adopted the concept of federated VoIP which is a departure from the architecture of the legacy networks. These solutions typically allow dynamic interconnection between users on any two domains on the Internet when a user wishes to place a call.</p>
        <p>VoIP systems employ session control and signalling protocols to control the signalling, set-up, and tear-down of calls. They transport audio streams over IP networks using special media delivery protocols that encode voice, audio, video with audio codecs, and video codecs as Digital audio by streaming media. Various codecs exist that optimize the media stream based on application requirements and network bandwidth; some implementations rely on narrowband and compressed speech, while others support high fidelity stereo codecs. Some popular codecs include μ-law and a-law versions of G.711, G.722, a popular open source voice codec known as iLBC, a codec that only uses 8 kbit/s each way called G.729, and many others.</p>
        <p>VoIP is available on many smartphones, personal computers, and on Internet access devices.</p>
    </div>
</div>