<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('iOS'); ?>
        <p><strong>iOS</strong> (originally <strong>iPhone OS</strong>) is a mobile operating system created and developed by <?php echo $this->stencil->addLink('Apple Inc', 'C'); ?> and distributed exclusively for Apple hardware. It is the operating system that presently powers many of the company's mobile devices, including the <?php echo $this->stencil->addLink('iPhone', 'ITH'); ?>, <?php echo $this->stencil->addLink('iPad', 'ITH'); ?>, and <?php echo $this->stencil->addLink('iPod touch', 'ITH'); ?>.</p>
        <p>Originally unveiled in 2007 for the <?php echo $this->stencil->addLink('iPhone', 'ITH'); ?>, it has been extended to support other Apple devices such as the iPod Touch (September 2007), iPad (January 2010), iPad Mini (November 2012) and second generation <?php echo $this->stencil->addLink('Apple TV', 'ITH'); ?> onward (September 2010). As of January 2015, Apple's <?php echo $this->stencil->addLink('App Store', 'MD'); ?> contained more than 1.4 million iOS applications, 725,000 of which are native for iPad. These mobile apps have collectively been downloaded more than 100 billion times. It had a 21% share of the smartphone mobile operating system units shipped in the fourth quarter of 2012, behind <?php echo $this->stencil->addLink('Google', 'C'); ?>'s <?php echo $this->stencil->addLink('Android', 'OS'); ?>. By the middle of 2012, there were 410 million devices activated. At <?php echo $this->stencil->addLink('WWDC', 'IT'); ?> 2014, Tim Cook said 800 million devices had been sold by June 2014. During Apple's quarterly earnings call in 27 January 2015, Apple announced that they have now sold one billion iOS devices.</p>
        <p>The user interface of iOS is based on the concept of direct manipulation, using multi-touch gestures. Interface control elements consist of sliders, switches, and buttons. Interaction with the <?php echo $this->stencil->addLink('OS', 'IT'); ?> includes gestures such as swipe, tap, pinch, and reverse pinch, all of which have specific definitions within the context of the iOS operating system and its multi-touch interface. Internal accelerometers are used by some applications to respond to shaking the device (one common result is the undo command) or rotating it in three dimensions (one common result is switching from portrait to landscape mode).</p>
        <p>iOS shares with <?php echo $this->stencil->addLink('OS X', 'OS'); ?> some frameworks such as Core Foundation and Foundation; however, its UI toolkit is <?php echo $this->stencil->addLink('Cocoa Touch', 'MD'); ?> rather than OS X's <?php echo $this->stencil->addLink('Cocoa', 'IT'); ?>, so that it provides the UIKit framework rather than the AppKit framework. It is therefore not compatible with OS X for applications. Also while iOS also shares the <?php echo $this->stencil->addLink('Darwin', 'LIN'); ?> foundation with OS X, <?php echo $this->stencil->addLink('Unix-like', 'OS'); ?> shell access is not available for users and restricted for apps, making iOS not fully Unix-compatible either.</p>
        <p>Major versions of iOS are released annually. In iOS, there are four abstraction layers: the Core OS layer, the Core Services layer, the Media layer, and the Cocoa Touch layer.</p>
    </div>
</div>