<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Copland Operating System'); ?>
        <p><strong>Copland</strong> was a project at <?php echo $this->stencil->addLink('Apple Computer', 'C'); ?> to create an updated version of the <?php echo $this->stencil->addLink('Macintosh', 'ITH'); ?> operating system. It was to have introduced protected memory, preemptive multitasking and a number of new underlying operating system features, yet still be compatible with existing Mac software. A follow-on known as Gershwin would add multithreading and other advanced features.</p>
        <p>Development began in 1994 and was underway in earnest by 1995, when the system started to be referred to as System 8, and later, Mac OS 8. As the project gathered momentum, a furious round of empire building began. New features began to be added more rapidly than they could be completed, including most of the items originally slated for Gershwin, along with a wide variety of otherwise unrelated projects from within the company. The completion date continued to slip into the future, and several key dates passed with no sign of a release.</p>
        <p>In 1996, Apple's newest CEO, <strong>Gil Amelio</strong>, poached <strong>Ellen Hancock</strong> from <strong>National Semiconductor</strong> and put her in charge of engineering in an effort to try to get development back on track. She decided it was best to cancel the project outright and try to find a suitable third-party system to replace it. Development officially ended in August 1996, and after a short search they announced that Apple was buying NeXT in order to use their <?php echo $this->stencil->addLink('NeXTSTEP', 'OS'); ?> operating system as the basis of a new Mac OS.</p>
        <p>Hancock also suggested that Apple should work on improving the existing <?php echo $this->stencil->addLink('System 7', 'MAC'); ?> while the new system matured. This was released as <?php echo $this->stencil->addLink('Mac OS 8', 'MAC'); ?> in 1997, and was followed by <?php echo $this->stencil->addLink('Mac OS 9', 'MAC'); ?> in 1999. The new operating system based on NeXTSTEP shipped in 2001 as <?php echo $this->stencil->addLink('Mac OS X', 'OS'); ?>.</p>
        <p>In 2008, <strong>PCWorld magazine</strong> named Copland to a list of the biggest project failures in IT history.</p>
    </div>
</div>