<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Commodore 64'); ?>
        <p>The <strong>Commodore 64</strong>, also known as the <strong>C64</strong>, or occasionally <strong>CBM 64</strong> or <strong>VIC-64</strong>, is an 8-bit home computer introduced in January 1982 by <?php echo $this->stencil->addLink('Commodore International', 'C'); ?>. It is listed in the Guinness World Records as the highest-selling single computer model of all time, with independent estimates placing the number sold between 10 and 17 million units.</p>
        <p>Volume production started in early 1982, with machines being released on to the market in August at a price of US$595. Preceded by the <?php echo $this->stencil->addLink('Commodore VIC-20', 'ITH'); ?> and <?php echo $this->stencil->addLink('Commodore PET', 'ITH'); ?>, the C64 takes its name from its 64 kilobytes (65,536 bytes) of RAM, and has technologically superior sound and graphical specifications when compared to some earlier systems such as the <?php echo $this->stencil->addLink('Apple II', 'ITH'); ?> and <?php echo $this->stencil->addLink('Atari 800', 'ITH'); ?>, with multi-color sprites and a more advanced sound processor.</p>
        <p>The C64 dominated the low-end computer market for most of the 1980s. For a substantial period (1983-1986), the C64 had between 30% and 40% share of the US market and two million units sold per year, outselling the <?php echo $this->stencil->addLink('IBM PC compatibles', 'ITH'); ?>, <?php echo $this->stencil->addLink('Apple Inc', 'C'); ?> computers, and the <?php echo $this->stencil->addLink('Atari', 'ITH'); ?> 8-bit family of computers. Sam Tramiel, a later Atari president and the son of Commodore's founder, said in a 1989 interview, "When I was at Commodore we were building 400,000 C64s a month for a couple of years." In the UK market, the 64 faced competition from the <?php echo $this->stencil->addLink('BBC Micro', 'ITH'); ?> and the <?php echo $this->stencil->addLink('Sinclair Spectrum', 'ITH'); ?> but the 64 was still one of the two most-popular computers in the UK.</p>
        <p>Part of the Commodore 64's success is because it was sold in retail stores instead of just electronics and / or computer stores. Commodore produced many of its parts in-house to control costs, including custom IC chips from <?php echo $this->stencil->addLink('MOS Technology', 'C'); ?>. It has been compared to the Ford Model T automobile for its role in bringing a new technology to middle-class households via creative mass-production.</p>
        <p?Approximately 10,000 commercial software titles have been made for the Commodore 64 including development tools, office productivity applications, and games. C64 emulators allow anyone with a modern computer, or a compatible video game console, to run these programs today. The C64 is also credited with popularising the computer demoscene and is still used today by some computer hobbyists. In 2008, 17 years after it was taken off the market, research showed that brand recognition for the model was still at 87%.</p>
    </div>
</div>