<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('IP Address'); ?>
        <p>An <strong>Internet Protocol address (IP address)</strong> is a numerical label assigned to each device (e.g. computer, printer) participating in a computer network that uses the <?php echo $this->stencil->addLink('Internet Protocol', 'IP'); ?> for communication. An IP address serves two principal functions: host or network interface identification and location addressing. Its role has been characterised as follows: "<em>A name indicates what we seek. An address indicates where it is. A route indicates how to get there</em>".</p>
        <p>The designers of the Internet Protocol defined an IP address as a <?php echo $this->stencil->addLink('32-bit', 'IT'); ?> number and this system, known as <strong>Internet Protocol Version 4 (<?php echo $this->stencil->addLink('IPv4', 'IP'); ?>)</strong>, is still in use today. However, because of the growth of the <?php echo $this->stencil->addLink('Internet', 'ITN'); ?> and the predicted depletion of available addresses, a new version of IP (<?php echo $this->stencil->addLink('IPv6', 'IP'); ?>), using 128 bits for the address, was developed in 1995. IPv6 was standardised as <?php echo $this->stencil->addRFCLink('2460'); ?> in 1998, and its deployment has been ongoing since the mid 2000s.</p>
        <p>IP addresses are usually written and displayed in human readable notations, such as <code>172.16.254.1</code> (IPv4), and <code>2001:db8:0:1234:0:567:8:1</code> (IPv6).</p>
        <p>The <strong>Internet Assigned Numbers Authority (<?php echo $this->stencil->addLink('IANA', 'C'); ?>)</strong> manages the IP address space allocations globally and delegates five <strong>regional Internet registries (<?php echo $this->stencil->addLink('RIR', 'C'); ?>s)</strong> to allocate IP address blocks to local Internet registries (Internet service providers) and other entities.</p>

        <h2>IP Versions</h2>
        <p>Two versions of the Internet Protocol (IP) are in use: IP Version 4 and IP Version 6. Each version defines an IP address differently. Because of its prevalence, the generic term IP address typically still refers to the addresses defined by IPv4. The gap in version sequence between IPv4 and IPv6 resulted from the assignment of number 5 to the experimental <strong>Internet Stream Protocol</strong> in 1979, which however was never referred to as IPv5.</p>

        <h3>IPv4 Addresses</h3>
        <p>In IPv4 an address consists of 32-bits which limits the address space to 4294967296 possible unique addresses. IPv4 reserves some addresses for special purposes such as private networks (~18 million addresses) or multicast addresses (~270 million addresses).</p>
        <p>IPv4 addresses are canonically represented in dot-decimal notation, which consists of four decimal numbers, each ranging from 0 to 255, separated by dots, e.g., <code>172.16.254.1</code>. Each part represents a group of 8 bits (<?php echo $this->stencil->addLink('octet', 'IT'); ?>) of the address. In some cases of technical writing, IPv4 addresses may be presented in various <?php echo $this->stencil->addLink('hexadecimal', 'IT'); ?>, <?php echo $this->stencil->addLink('octal', 'IT'); ?>, or binary<?php echo $this->stencil->addLink('binary', 'IT'); ?> representations.</p>

        <h4>Subnetting</h4>
        <p>In the early stages of development of the Internet Protocol, network administrators interpreted an IP address in two parts: network number portion and host number portion. The highest order octet (most significant eight bits) in an address was designated as the network number and the remaining bits were called the rest field or host identifier and were used for host numbering within a network.</p>
        <p>This early method soon proved inadequate as additional networks developed that were independent of the existing networks already designated by a network number. In 1981, the Internet addressing specification was revised with the introduction of classful network architecture.</p>
        <p>Classful network design allowed for a larger number of individual network assignments and fine grained subnetwork design. The first three bits of the most significant octet of an IP address were defined as the class of the address. Three classes (A, B, and C) were defined for universal unicast addressing. Depending on the class derived, the network identification was based on octet boundary segments of the entire address. Each class used successively additional octets in the network identifier, thus reducing the possible number of hosts in the higher order classes (B and C). The following table gives an overview of this now obsolete system.</p>
        <p>Classful network design served its purpose in the startup stage of the Internet, but it lacked scalability in the face of the rapid expansion of the network in the 1990s. The class system of the address space was replaced with <strong>Classless Inter-Domain Routing (CIDR)</strong> in 1993. CIDR is based on <strong>variable length subnet masking (VLSM)</strong> to allow allocation and routing based on arbitrary length prefixes.</p>
        <p></p>Today, remnants of classful network concepts function only in a limited scope as the default configuration parameters of some network software and hardware components (e.g. netmask), and in the technical jargon used in network administrators' discussions.</p>

        <h4>Private Addresses</h4>
        <p>Early network design, when global end-to-end connectivity was envisioned for communications with all Internet hosts, intended that IP addresses be uniquely assigned to a particular computer or device. However, it was found that this was not always necessary as private networks developed and public address space needed to be conserved.</p>
        <p>Computers not connected to the Internet, such as factory machines that communicate only with each other via <?php echo $this->stencil->addLink('TCP/IP', 'IP'); ?>, need not have globally unique IP addresses. Three ranges of IPv4 addresses for private networks were reserved in RFC 1918. These addresses are not routed on the Internet and thus their use need not be coordinated with an IP address registry.</p>
        <p>Today, when needed, such private networks typically connect to the Internet through <strong>network address translation (<?php echo $this->stencil->addLink('NAT', 'IP'); ?>)</strong>.</p>

        <h3>IPv4 Address Exhaustion</h3>
        <p>High levels of demand have decreased the supply of unallocated Internet Protocol Version 4 (IPv4) addresses available for assignment to Internet service providers and end user organisations since the 1980s. This development is referred to as <?php echo $this->stencil->addLink('IPv4 address exhaustion', 'IP'); ?>. IANA's primary address pool was exhausted on 3 February 2011, when the last five blocks were allocated to the five RIRs. APNIC was the first RIR to exhaust its regional pool on 15 April 2011, except for a small amount of address space reserved for the transition to IPv6, intended to be allocated in a restricted process.</p>

        <h3>IPv6 Addresses</h3>
        <p>The rapid exhaustion of IPv4 address space, despite conservation techniques, prompted the <strong>Internet Engineering Task Force (<?php echo $this->stencil->addLink('IETF', 'C'); ?>)</strong> to explore new technologies to expand the addressing capability in the Internet. The permanent solution was deemed to be a redesign of the Internet Protocol itself. This new generation of the Internet Protocol, intended to replace IPv4 on the Internet, was eventually named Internet Protocol Version 6 (IPv6) in 1995. The address size was increased from 32 to 128 bits or 16 octets. This, even with a generous assignment of network blocks, is deemed sufficient for the foreseeable future. Mathematically, the new address space provides the potential for a maximum of 2128, or about 3.403x1038 addresses.</p>
        <p>The primary intent of the new design was not to provide just a sufficient quantity of addresses, but also to allow an efficient aggregation of subnetwork routing prefixes at routing nodes. As a result, routing table sizes are smaller, and the smallest possible individual allocation is a subnet for 264 hosts, which is the square of the size of the entire IPv4 Internet. At these levels, actual address utilisation rates will be small on any IPv6 network segment. The new design also provides the opportunity to separate the addressing infrastructure of a network segment, that is the local administration of the segment's available space, from the addressing prefix used to route external traffic for a network. IPv6 has facilities that automatically change the routing prefix of entire networks, should the global connectivity or the routing policy change, without requiring internal redesign or manual renumbering.</p>
        <p>The large number of IPv6 addresses allows large blocks to be assigned for specific purposes and, where appropriate, to be aggregated for efficient routing. With a large address space, there is no need to have complex address conservation methods as used in CIDR.</p>
        <p>Many modern desktop and enterprise server operating systems include native support for the IPv6 protocol, but it is not yet widely deployed in other devices, such as home networking routers, voice over IP (VoIP) and multimedia equipment, and network peripherals.</p>

        <h4>Private addresses</h4>
        <p>Just as IPv4 reserves addresses for private or internal networks, blocks of addresses are set aside in IPv6 for private addresses. In IPv6, these are referred to as <strong>unique local addresses (ULA)</strong>. <?php echo $this->stencil->addRFCLink('4193'); ?> sets aside the routing prefix <code>fc00::/7</code> for this block which is divided into two <code>/8</code> blocks with different implied policies. The addresses include a 40-bit pseudorandom number that minimizes the risk of address collisions if sites merge or packets are misrouted.</p>
        <p>Early designs used a different block for this purpose (<code>fec0::</code>), dubbed site-local addresses. However, the definition of what constituted sites remained unclear and the poorly defined addressing policy created ambiguities for routing. This address range specification was abandoned and must not be used in new systems.</p>
        <p>Addresses starting with <code>fe80:</code>, called link-local addresses, are assigned to interfaces for communication on the link only. The addresses are automatically generated by the operating system for each network interface. This provides instant and automatic network connectivity for any IPv6 host and means that if several hosts connect to a common hub or switch, they have a communication path via their link-local IPv6 address. This feature is used in the lower layers of IPv6 network administration (e.g. <strong>Neighbour Discovery Protocol</strong>).</p>
        <p>None of the private address prefixes may be routed on the public Internet.</p>
    </div>
</div>