<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Internet Protocol Version 4 (IPv4)'); ?>
        <p><strong>Internet Protocol version 4 (IPv4)</strong> is the fourth version in the development of the <strong>Internet Protocol (<?php echo $this->stencil->addLink('IP', 'IP'); ?>)</strong>. It is one of the core protocols of standards based internetworking methods in the Internet, and was the first version deployed for production in the <?php echo $this->stencil->addLink('ARPANET', 'ITN'); ?> in 1983. It still routes most Internet traffic today, despite the on-going deployment of a successor protocol, <?php echo $this->stencil->addLink('IPV6', 'IP'); ?>. IPv4 is described in <?php echo $this->stencil->addLink('IETF', 'C'); ?> publication <?php echo $this->stencil->addRFCLink('791'); ?> (September 1981), replacing an earlier definition ([RFC 760]<?php echo $this->stencil->addRFCLink('760'); ?>, January 1980).</p>
        <p>IPv4 is a connectionless protocol for use on packet-switched networks. It operates on a best effort delivery model, in that it does not guarantee delivery, nor does it assure proper sequencing or avoidance of duplicate delivery. These aspects, including data integrity, are addressed by an upper layer transport protocol, such as the <strong>Transmission Control Protocol (<?php echo $this->stencil->addLink('TCP', 'IP'); ?>)</strong>.</p>

        <h2>Addressing</h2>
        <p>IPv4 uses <?php echo $this->stencil->addLink('32-bit', 'ITH'); ?> (four-byte) addresses, which limits the address space to 4294967296 addresses. This limitation stimulated the development of IPv6 in the 1990s, which has been in commercial deployment since 2006.</p>
        <p>Because of the demand of the growing Internet, the small address space finally suffered exhaustion on 3 February 2011, after having been significantly delayed by classful network design, Classless Inter-Domain Routing, and <strong>network address translation (<?php echo $this->stencil->addLink('NAT', 'IP'); ?>)</strong>.</p>
        <p>IPv4 reserves special address blocks for private networks (~18 million addresses) and multicast addresses (~270 million addresses).</p>

        <h2>Address Representations</h2>
        <p>IPv4 addresses may be represented in any notation expressing a 32-bit integer value. They are most often written in the dot-decimal notation, which consists of four octets of the address expressed individually in decimal numbers and separated by periods. The CIDR notation standard combines the address with its routing prefix in a compact format, in which the address is followed by a slash character (<code>/</code>) and the count of consecutive 1 bits in the routing prefix (subnet mask).</p>
        <p>For example, the quad-dotted IP address <code>192.0.2.235</code> represents the 32-bit decimal number 3221226219, which in hexadecimal format is <code>0xC00002EB</code>. This may also be expressed in dotted hex format as <code>0xC0.0x00.0x02.0xEB</code>, or with octal byte values as <code>0300.0000.0002.0353</code>.</p>

        <h2>Allocation</h2>
        <p>Originally, an IP address was divided into two parts: the network identifier was the most significant (highest order) octet of the address, and the host identifier was the rest of the address. The latter was therefore also called the rest field. This enabled the creation of a maximum of 256 networks. This was quickly found to be inadequate.</p>
        <p>To overcome this limit, the high order octet of the addresses was redefined to create a set of classes of networks, in a system which later became known as classful networking. The system defined five classes, Class A, B, C, D, and E. The Classes A, B, and C had different bit lengths for the new network identification. The rest of an address was used as previously to identify a host within a network, which meant that each network class had a different capacity to address hosts. Class D was allocated for multicast addressing and Class E was reserved for future applications.</p>
        <p>Starting around 1985, methods were devised to subdivide IP networks. One method that has proved flexible is the use of the <strong>variable-length subnet mask (VLSM)</strong>.</p>
        <p>Based on the IETF standard <?php echo $this->stencil->addRFCLink('1517'); ?> published in 1993, this system of classes was officially replaced with <strong>Classless Inter-Domain Routing (CIDR)</strong>, which expressed the number of bits (from the most significant) as, for instance, <code>/24</code>, and the class-based scheme was dubbed classful, by contrast. CIDR was designed to permit repartitioning of any address space so that smaller or larger blocks of addresses could be allocated to users. The hierarchical structure created by CIDR is managed by the <strong>Internet Assigned Numbers Authority (<?php echo $this->stencil->addLink('IANA', 'C'); ?>)</strong> and the <strong>regional Internet registries (<?php echo $this->stencil->addLink('RIR', 'C'); ?>s)</strong>. Each RIR maintains a publicly searchable WHOIS database that provides information about IP address assignments.</p>

        <h2>Special Use Addresses</h2>
        <p>The Internet Engineering Task Force (IETF) and the Internet Assigned Numbers Authority (IANA) have restricted from general use various reserved IP addresses for special purposes. Some are used for maintenance of routing tables, for multicast traffic, operation under failure modes, or to provide addressing space for public, unrestricted uses on private networks.</p>
    </div>
</div>