<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Internet Protocol Version 6 (IPv6)'); ?>
        <p><strong>Internet Protocol version 6 (IPv6)</strong> is the most recent version of the <strong>Internet Protocol (<?php echo $this->stencil->addLink('IP', 'IP'); ?>)</strong>, the communications protocol that provides an identification and location system for computers on networks and routes traffic across the Internet. IPv6 was developed by the <strong>Internet Engineering Task Force (<?php echo $this->stencil->addLink('IETF', 'C'); ?>)</strong> to deal with the long anticipated problem of <?php echo $this->stencil->addLink('IPv4 address exhaustion', 'IP'); ?>. IPv6 is intended to replace <?php echo $this->stencil->addLink('IPv4', 'IP'); ?>.</p>
        <p>Every device on the Internet is assigned an <?php echo $this->stencil->addLink('IP address', 'ITH'); ?> for identification and location definition. With the rapid growth of the Internet after commercialisation in the 1990s, it became evident that far more addresses than the IPv4 address space has available were necessary to connect new devices in the future. By 1998, the Internet Engineering Task Force (IETF) had formalised the successor protocol. IPv6 uses a <?php echo $this->stencil->addLink('128-bit', 'ITH'); ?> address, allowing 2128, or approximately 3.4x1038 addresses, or more than 7.9x1028 times as many as IPv4, which uses <?php echo $this->stencil->addLink('32-bit', 'ITH'); ?> addresses and provides approximately 4.3 billion addresses. The two protocols are not designed to be interoperable, complicating the transition to IPv6. However, several IPv6 transition mechanisms have been devised to permit communication between IPv4 and IPv6 hosts.</p>
        <p>IPv6 provides other technical benefits in addition to a larger addressing space. In particular, it permits hierarchical address allocation methods that facilitate route aggregation across the Internet, and thus limit the expansion of routing tables. The use of multicast addressing is expanded and simplified, and provides additional optimisation for the delivery of services. Device mobility, security, and configuration aspects have been considered in the design of the protocol.</p>
        <p>IPv6 addresses are represented as eight groups of four hexadecimal digits with the groups being separated by colons, for example <code>2001:0db8:85a3:0042:1000:8a2e:0370:7334</code>, but methods to abbreviate this full notation exist.</p>
        <p>IPv6 is an Internet Layer protocol for packet-switched internetworking and provides end-to-end datagram transmission across multiple IP networks, closely adhering to the design principles developed in the previous version of the protocol, Internet Protocol Version 4 (IPv4). IPv6 was first formally described in Internet standard document <?php echo $this->stencil->addRFCLink('2460'); ?>, published in December 1998. In addition to offering more addresses, IPv6 also implements features not present in IPv4. It simplifies aspects of address assignment (stateless address auto-configuration), network renumbering, and router announcements when changing network connectivity providers. It simplifies processing of packets in routers by placing the responsibility for packet fragmentation into the end points. The IPv6 subnet size is standardised by fixing the size of the host identifier portion of an address to 64 bits to facilitate an automatic mechanism for forming the host identifier from link layer addressing information (<?php echo $this->stencil->addLink('MAC address', 'ITN'); ?>). Network security was a design requirement of the IPv6 architecture, and included the original specification of <strong>IPsec</strong>.</p>
        <p>IPv6 does not specify interoperability features with IPv4, but essentially creates a parallel, independent network. Exchanging traffic between the two networks requires translator gateways employing one of several transition mechanisms, such as NAT64, or a tunneling protocol like 6to4, 6in4, or Teredo.</p>

        <h2>Motivation and Origin</h2>
        <p>Internet Protocol Version 4 <?php echo $this->stencil->addLink('IPv4', 'IP'); ?>) was the first publicly used version of the Internet Protocol. IPv4 was developed as a research project by the <strong>Defense Advanced Research Projects Agency (DARPA)</strong>, a United States Department of Defense agency, before becoming the foundation for the Internet and the <?php echo $this->stencil->addLink('World Wide Web', 'WD'); ?>. It is currently described by <?php echo $this->stencil->addLink('IETF', 'C'); ?> publication <?php echo $this->stencil->addRFCLink('791'); ?> (September 1981), which replaced an earlier definition (<?php echo $this->stencil->addRFCLink('760'); ?>, January 1980). IPv4 included an addressing system that used numerical identifiers consisting of 32 bits. These addresses are typically displayed in quad-dotted notation as decimal values of four <?php echo $this->stencil->addLink('octets', 'IT'); ?>, each in the range 0 to 255, or 8 bits per number. Thus, IPv4 provides an addressing capability of 232 or approximately 4.3 billion addresses. Address exhaustion was not initially a concern in IPv4 as this version was originally presumed to be a test of DARPA's networking concepts. During the first decade of operation of the Internet, it became apparent that methods had to be developed to conserve address space. In the early 1990s, even after the redesign of the addressing system using a classless network model, it became clear that this would not suffice to prevent <?php echo $this->stencil->addLink('IPv4 address exhaustion', 'IP'); ?>, and that further changes to the Internet infrastructure were needed.</p>
        <p>The last unassigned top-level address blocks of 16 million IPv4 addresses were allocated in February 2011 by the <strong>Internet Assigned Numbers Authority (<?php echo $this->stencil->addLink('IANA', 'C'); ?>)</strong> to the five <strong>regional Internet registries (<?php echo $this->stencil->addLink('RIR', 'C'); ?>s)</strong>. However, each RIR still has available address pools and is expected to continue with standard address allocation policies until one <code>/8</code> <strong>Classless Inter-Domain Routing (CIDR)</strong> block remains. After that, only blocks of 1024 addresses (<code>/22</code>) will be provided from the RIRs to a <strong>local Internet registry (LIR)</strong>. As of September 2012, both the Asia-Pacific Network Information Centre (APNIC) and the Réseaux IP Européens Network Coordination Centre (RIPE_NCC) have reached this stage.</p>
    </div>
</div>