<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Cocoa'); ?>
        <p><strong>Cocoa</strong> is <?php echo $this->stencil->addLink('Apple', 'C'); ?>'s native object-oriented application programming interface (<?php echo $this->stencil->addLink('API', 'IT'); ?>) for the <?php echo $this->stencil->addLink('OS X', 'OS'); ?> operating system.</p>
        <p>For <?php echo $this->stencil->addLink('iOS', 'OS'); ?>, there is a similar API called <?php echo $this->stencil->addLink('Cocoa Touch', 'MD'); ?> which includes gesture recognition, animation, and a different user interface library, and is for applications for the iOS operating system, used on Apple devices such as <?php echo $this->stencil->addLink('iPhone', 'ITH'); ?>, <?php echo $this->stencil->addLink('iPad', 'ITH'); ?>, <?php echo $this->stencil->addLink('iPod Touch', 'ITH'); ?> and <?php echo $this->stencil->addLink('Apple TV', 'ITH'); ?>.</p>
        <p>Cocoa consists of the Foundation Kit, Application Kit, and Core Data frameworks, as included by <code>Cocoa.h</code> header file, as well as the libraries and frameworks included by those, such as the <?php echo $this->stencil->addLink('C', 'L'); ?> standard library and the <?php echo $this->stencil->addLink('Objective-C', 'LC'); ?> runtime.</p>
        <p>Cocoa applications are typically developed using the development tools provided by Apple, specifically <?php echo $this->stencil->addLink('Xcode', 'IDE'); ?> (formerly <strong>Project Builder</strong>) and Interface Builder, using the Objective-C language.</p>
        <p>However, the Cocoa programming environment can be accessed using other tools, such as Clozure CL, LispWorks, <?php echo $this->stencil->addLink('Object Pascal', 'L'); ?>, <?php echo $this->stencil->addLink('Python', 'L'); ?>, <?php echo $this->stencil->addLink('Perl', 'L'); ?>, <?php echo $this->stencil->addLink('Ruby', 'L'); ?> and <?php echo $this->stencil->addLink('AppleScript', 'L'); ?> with the aid of bridging mechanisms such as PasCocoa, PyObjC, CamelBones, RubyCocoa and D/Objective-C Bridge.</p>
        <p>For end-users, Cocoa applications are those written using the Cocoa programming environment. Such applications usually have a distinctive feel, since the Cocoa programming environment automates many aspects of an application to comply with Apple's human interface guidelines.</p>
    </div>
</div>