<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Copyright'); ?>
        <p><strong>Copyright</strong> is a legal right created by the law of a country that grants the creator of an original work exclusive rights to its use and distribution, usually for a limited time. The exclusive rights are not absolute; they are limited by limitations and exceptions to copyright law, including fair use.</p>
        <p>Copyright is a form of intellectual property, applicable to any expressed representation of a creative work. Under US copyright law, however, legal protection attaches only to fixed representations in a tangible medium. It is often shared among multiple authors, each of whom holds a set of rights to use or license the work, and who are commonly referred to as rightsholders. These rights frequently include reproduction, control over derivative works, distribution, public performance, and "moral rights" such as attribution.</p>
        <p>Copyrights are territorial, which means that they do not extend beyond the territory of a specific state unless that state is a party to an international agreement. While many aspects of national copyright laws have been standardised through international copyright agreements, copyright laws of most countries have some unique features.</p>
        <p>Typically, the duration of copyright is the author's life plus 50 to 100 years (that is, copyright typically expires 50 to 100 years after the author dies, depending on the country). Some countries require certain copyright formalities to establishing copyright, but most recognise copyright in any completed work, without formal registration. Generally, copyright is enforced as a civil matter, though some jurisdictions do apply criminal sanctions.</p>
        <p>Most jurisdictions recognise copyright limitations, allowing "fair" exceptions to the creator's exclusivity of copyright and giving users certain rights. The development of digital media and computer network technologies have prompted reinterpretation of these exceptions, introduced new difficulties in enforcing copyright, and inspired additional challenges to copyright law's philosophic basis. Simultaneously, businesses with great economic dependence upon copyright, such as those in the music business, have advocated the extension and expansion of their intellectual property rights and sought additional legal and technological enforcement.</p>
    </div>
</div>