<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('GNU General Public License (GPL)'); ?>
        <p>The <strong>GNU General Public License (GNU GPL or GPL)</strong> is the most widely used free software license, which guarantees end users (individuals, organisations, companies) the freedoms to run, study, share (copy), and modify the software. Software that allows these rights is called free software and, if the software is copylefted, requires those rights to be retained. The GPL demands both. The license was originally written by <strong>Richard Stallman</strong> of the <strong>Free Software Foundation (<?php echo $this->stencil->addLink('FSF', 'C'); ?>)</strong> for the <?php echo $this->stencil->addLink('GNU Project', 'C'); ?>.</p>
        <p>In other words, the GPL grants the recipients of a computer program the rights of the Free Software Definition and uses <?php echo $this->stencil->addLink('copyleft', 'LIC'); ?> to ensure the freedoms are preserved whenever the work is distributed, even when the work is changed or added to. The GPL is a copyleft license, which means that derived works can only be distributed under the same license terms. This is in distinction to permissive free software licenses, of which the <?php echo $this->stencil->addLink('BSD licenses', 'LIC'); ?> and the <?php echo $this->stencil->addLink('MIT License', 'LIC'); ?> are the standard examples. GPL was the first copyleft license for general use.</p>
        <p>As of August 2007, the GPL accounted for nearly 65% of the 43,442 free software projects listed on Freecode, and as of January 2006, about 68% of the projects listed on SourceForge.net. Similarly, a 2001 survey of <?php echo $this->stencil->addLink('Red Hat Linux', 'OS'); ?> 7.1 found that 50% of the source code was licensed under the GPL and a 1997 survey of MetaLab, then the largest free software archive, showed that the GPL accounted for about half of the software licensed therein. Prominent free software programs licensed under the GPL include the <?php echo $this->stencil->addLink('Linux', 'OS'); ?> kernel and the GNU Compiler Collection (GCC). Some other free software programs (<?php echo $this->stencil->addLink('MySQL', 'DB'); ?> is a prominent example) are dual-licensed under multiple licenses, often with one of the licenses being the GPL.</p>
        <p>David A. Wheeler argues that the copyleft provided by the GPL was crucial to the success of Linux-based systems, giving the programmers who contributed to the kernel the assurance that their work would benefit the whole world and remain free, rather than being exploited by software companies that would not have to give anything back to the community.</p>
        <p>>On 29 June 2007, the third version of the license (GNU GPLv3) was released to address some perceived problems with the second version (GNU GPLv2) that were discovered during its long-time usage. To keep the license up-to-date, the GPL license includes an optional "any later version" clause, allowing users to choose between the original terms or the terms in new versions as updated by the FSF. Developers can omit it when licensing their software; for instance the Linux kernel is licensed under GPLv2 without the "any later version" clause.</p>
    </div>
</div>