<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Google Hummingbird'); ?>
        <p><strong>Google Hummingbird</strong> is a search algorithm used by <?php echo $this->stencil->addLink('Google', 'C'); ?>.</p>
        <p>Google started using Hummingbird about 30 August 2013, and announced the change on 26 September on the eve of the company's 15th anniversary.</p>
        <p>Gianluca Fiorelli said Hummingbird is about synonyms but also about context. Google always had synonyms, he writes, but with Hummingbird it is also able to judge context - thereby judging the intent of a person carrying out a search, to determine what they are trying to find out. This concept is called semantic search.</p>
        <p>Danny Sullivan said of Hummingbird, "<em>Google said that Hummingbird is paying more attention to each word in a query, ensuring that the whole query - the whole sentence or conversation or meaning - is taken into account</em>". Michelle Hill said Hummingbird is about "<em>understanding intent</em>". Steve Masters wrote, "<em>The Hummingbird approach should be inspirational to anyone managing and planning content - if you aren't already thinking like Hummingbird, you should be. In a nutshell, think about why people are looking for something rather than what they are looking for. A content strategy should be designed to answer their needs, not just provide them with facts</em>".</p>
        <p>The Hummingbird update was the first major update to Google's search algorithm since the 2010 “<em>Caffeine Update</em>”, but even that was limited primarily to improving the indexing of information rather than the sorting of information. Google search chief Amit Singhal stated that Hummingbird is the first major update of its type since 2001.</p>
        <p>Conversational search leverages natural language, semantic search, and more to improve the way search queries are parsed. Unlike previous search algorithms which would focus on each individual word in the search query, Hummingbird considers each word but also how each word makes up the entirety of the query - the whole sentence or conversation or meaning - is taken into account, rather than particular words. The goal is that pages matching the meaning do better, rather than pages matching just a few words.</p>
        <p>Much like an extension of Google's "Knowledge Graph", Hummingbird is aimed at making interactions more human - capable of understanding the concepts and relationships between keywords.</p>
        <p>Hummingbird places greater emphasis on page content making search results more relevant and pertinent and ensuring that Google delivers users to the most appropriate page of a website, rather than to a home page or top level page.</p>
    </div>
</div>