<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Death March'); ?>
        <p>In Project Management, a <strong>Death March</strong> is a project where the members feel it is destined to fail, or requires a stretch of unsustainable overwork.</p>
        <p>The general feel of the project reflects that of an actual death march because the members of the project are forced to continue the project by their superiors against their better judgement.</p>
        <p>The fields whose project management practice first named these related phenomena are software development and software engineering. Other fields have since recognized the same occurrence in their own spheres and have adopted the name.</p>
        <p>Death marches of the destined-to-fail type usually are a result of unrealistic or overly optimistic expectations in scheduling, feature scope, or both, and often include lack of appropriate documentation or relevant training and outside expertise that would be needed to do the task successfully. The knowledge of the doomed nature of the project weighs heavily on the psyche of its participants, as if they are helplessly watching themselves and their coworkers being forced to torture themselves and march toward death. Often, the death march will involve desperate attempts to right the course of the project by asking team members to work especially gruelling hours (14-hour days, 7-day weeks, etc) or by attempting to "throw (enough) bodies at the problem", often causing burnout.</p>
        <p>Often, the discomfort is heightened by the knowledge that "it didn't have to be this way," that is, that if the company wanted to achieve the goal of the project, it could have done so in a successful way if it had been managed competently (such as by devoting the obviously required resources, including bringing all relevant expertise, technology, or applied science to the task rather than just whatever incomplete knowledge a few employees happened to know already). Patent underresourcing is especially offensive at a large corporation with sufficiently deep pockets; at least at small companies, a gap between resources and needs is understandable, but at large, profitable, cash-rich companies, underresourcing is not a necessity and thus feels to most workers like stupidity. Business culture pressures, such as the long-noted phenomenon of corporations pursuing short-term maximization of profits via cost cutting or avoidance that is damaging to long-term best interest, may play a role in addition to mere incompetence.</p>
    </div>
</div>