<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Histogram'); ?>
        <p>A <strong>histogram</strong> is a graphical representation of the distribution of numerical data. It is an estimate of the probability distribution of a continuous variable (quantitative variable) and was first introduced by <strong>Karl Pearson</strong>. To construct a histogram, the first step is to "bin" the range of values that is, divide the entire range of values into a series of intervals and then count how many values fall into each interval. The bins are usually specified as consecutive, non-overlapping intervals of a variable. The bins (intervals) must be adjacent, and are usually equal size.</p>
        <p>If the bins are of equal size, a rectangle is erected over the bin with height proportional to the frequency, the number of cases in each bin. In general, however, bins need not be of equal width; in that case, the erected rectangle has area proportional to the frequency of cases in the bin The vertical axis is not frequency but density: the number of cases per unit of the variable on the horizontal axis. A histogram may also be normalized displaying relative frequencies. It then shows the proportion of cases that fall into each of several categories, with the sum of the heights equaling 1. Examples of variable bin width are displayed on Census bureau data below.</p>
        <p>As the adjacent bins leave no gaps, the rectangles of a histogram touch each other to indicate that the original variable is continuous.</p>
        <p>Histograms give a rough sense of the density of the underlying distribution of the data, and often for density estimation: estimating the probability density function of the underlying variable. The total area of a histogram used for probability density is always normalized to 1. If the length of the intervals on the x-axis are all 1, then a histogram is identical to a relative frequency plot.</p>
        <p>A histogram can be thought of as a simplistic kernel density estimation, which uses a kernel to smooth frequencies over the bins. This yields a smoother probability density function, which will in general more accurately reflect distribution of the underlying variable. The density estimate could be plotted as an alternative to the histogram, and is usually drawn as a curve rather than a set of boxes.</p>
        <p>Another alternative is the average shifted histogram, which is fast to compute and gives a smooth curve estimate of the density without using kernels.</p>
        <p>The histogram is one of the <?php echo $this->stencil->addLink('Seven Basic Tools of Quality Control', 'PM'); ?>.</p>
        <p>Histograms are often confused with bar charts. A histogram is used for continuous data, where the bins represent ranges of data, and the areas of the rectangles are meaningful, while a bar chart is a plot of categorical variables and the discontinuity should be indicated by having gaps between the rectangles, from which only the length is meaningful. Often this is neglected, which may lead to a bar chart being confused for a histogram.</p>
    </div>
</div>