<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('128-bit'); ?>
        <p>In computer architecture, <strong>128-bit</strong> integers, memory addresses, or other data units are those that are at most 128 bits (16 octets) wide. Also, 128-bit CPU and ALU architectures are those that are based on registers, address buses, or data buses of that size.</p>
        <p>While there are currently no mainstream general purpose processors built to operate on 128-bit integers or addresses, a number of processors do have specialised ways to operate on 128-bit chunks of data. The <strong>IBM System/370</strong> could be considered the first simple 128-bit computer, as it used 128-bit floating point registers. Most modern CPUs feature SIMD instruction sets (SSE, AltiVec etc.) where 128-bit vector registers are used to store several smaller numbers, such as four <?php echo $this->stencil->addLink('32-bit', 'ITH'); ?> floating-point numbers. A single instruction can then operate on all these values in parallel. However, these processors do not operate on individual numbers that are 128 binary digits in length, only their registers have the size of 128-bits.</p>
        <p>The <?php echo $this->stencil->addLink('DEC VAX', 'ITH'); ?> supported operations on 128-bit integer ('O' or octaword) and 128-bit floating-point ('H-float' or HFLOAT) datatypes. Support for such operations was an upgrade option rather than being a standard feature. Since the VAX's registers were 32 bits wide, a 128-bit operation used four consecutive registers or four longwords in memory.</p>
        <p>The <strong>ICL 2900</strong> Series provided a 128-bit accumulator, and its instruction set included 128-bit floating point and packed decimal arithmetic.</p>
        <p>In the same way that compilers emulate e.g. <?php echo $this->stencil->addLink('64-bit', 'ITH'); ?> integer arithmetic on architectures with register sizes less than 64-bit, some compilers also support 128-bit integer arithmetic. For example, the <strong>GCC C</strong> compiler has a <code>__int128_t</code> 128-bit integer type. For the <?php echo $this->stencil->addLink('C', 'L'); ?> programming language, this is a compiler specific extension, as C11 itself doesn't guarantee support for 128 bit integers.</p>
    </div>
</div>