<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Ferranti Mark 1'); ?>
        <p>The <strong>Ferranti Mark 1</strong>, also known as the <strong>Manchester Electronic Computer</strong> in its sales literature, and thus sometimes called the <strong>Manchester Ferranti</strong>, was the world's first commercially available general purpose electronic computer.</p>
        <p>It was "<em>the tidied up and commercialised version of the Manchester computer</em>".</p>
        <p>The first machine was delivered to the University of Manchester in February 1951, ahead of the UNIVAC I, which was turned over to the United States Census Bureau on 31 March (but not delivered until late December the following year).</p>
        <p>Based on the <strong>Manchester Mark 1</strong>, which was designed at the University of Manchester by Freddie Williams and Tom Kilburn, the machine was built by <?php echo $this->stencil->addLink('Ferranti', 'C'); ?> of the United Kingdom.</p>
        <p>The Manchester Mark 1 effectively served as a prototype for the Ferranti Mark 1; the main improvements over it were in the size of the primary and secondary storage, a faster multiplier, and additional instructions.</p>
        <p>The Mark 1 used a 20-bit word stored as a single line of dots of electric charges settled on the surface of a Williams tube display, each cathodic tube storing 64 lines of dots.</p>
        <p>Instructions were stored in a single word, while numbers were stored in two words. The main memory consisted of eight tubes, each storing one such page of 64 words. Other tubes stored the single 80-bit accumulator (A), the 40-bit "multiplicand/quotient register" (MQ) and eight "B-lines", or index registers, which was one of the unique features of the Mark 1 design.</p>
        <p>The accumulator could also be addressed as two 40-bit words. An extra 20-bit word per tube stored an offset value into the secondary storage. Secondary storage was provided in the form of a 512-page magnetic drum, storing two pages per track, with about 30 milliseconds revolution time. The drum provided eight times the storage of the original designed at Manchester.</p>
        <p>The instructions, like the Manchester machine, used a single address format in which operands were modified and left in the accumulator. There were about fifty instructions in total. The basic cycle time was 1.2 milliseconds, and a multiplication could be completed in the new parallel unit in about 2.16 milliseconds (about 5 times faster than the original). The multiplier used almost a quarter of the machine's 4,050 vacuum tubes. Several instructions were included to copy a word of memory from one of the Williams tubes to a paper tape machine, or read them back in. Several new instructions were added to the original Manchester design, including a random number instruction and several new instructions using the B-lines.</p>
        <p>The original Mark 1 had to be programmed by entering alphanumeric characters representing a five-bit value that could be represented on the paper tape input. The engineers decided to use the simplest mapping between the paper holes and the binary digits they represented, but the mapping between the holes and the physical keyboard was never meant to be a binary mapping. As a result the characters representing the values from 0–31 (five-bit numbers) looked entirely random. Each instruction was represented by a single character.</p>
        <p>The first machine was delivered to the University of Manchester. Ferranti had high hopes for further sales, and were encouraged by an order placed by the Atomic Energy Research Establishment for delivery in autumn 1952. But a change of government while the machine was being built led to all government contracts over 100,000GBP being cancelled, leaving Ferranti with a partially completed Mark 1. The machine, nicknamed <em>FERUT</em>, was eventually purchased by the University of Toronto at "fire sale" prices, and was extensively used in business, engineering, and academia.</p>
    </div>
</div>