<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('iPhone'); ?>
        <p><strong>iPhone</strong> is a line of <?php echo $this->stencil->addLink('smartphones', 'ITH'); ?> designed and marketed by <?php echo $this->stencil->addLink('Apple Inc', 'C'); ?>. They run Apple's <?php echo $this->stencil->addLink('iOS', 'OS'); ?> mobile operating system. The first generation iPhone was released on 29 June 2007.</p>
        <p>The user interface is built around the device's multi-touch screen, including a virtual keyboard. The iPhone has <?php echo $this->stencil->addLink('Wi-Fi', 'ITN'); ?> and can connect to many cellular networks, including 1xRTT (represented by a 1x on the status bar) and GPRS (shown as GPRS on the status bar), EDGE (shown as a capital E on the status bar), UMTS and EV-DO (shown as 3G), a faster version of UMTS and 4G (shown as a 4G symbol on the status bar), and LTE (shown as LTE on the status bar). An iPhone can shoot video (though this was not a standard feature until the <?php echo $this->stencil->addLink('iPhone 3GS', 'ITH'); ?>), take photos, play music, send and receive email, browse the web, send texts, GPS navigation, record notes, do mathematical calculations, and receive visual voicemail. Other functions video games, reference works, social networking, etc. can be enabled by downloading application programs ("apps"); as of October 2013, the <?php echo $this->stencil->addLink('App Store', 'MD'); ?> offered more than one million apps by Apple and third parties and is ranked as the world's second largest mobile software distribution network of its kind (by number of currently available applications).</p>
        <p>There are eight generations of iPhone models, each accompanied by one of the eight major releases of iOS. The original 1st generation iPhone was a GSM phone and established design precedents, such as a button placement that has persisted throughout all releases and a screen size maintained for the next four iterations. The iPhone 3G added 3G cellular network capabilities and A-GPS location. The iPhone 3GS added a faster processor and a higher resolution camera that could record video at 480p. The <?php echo $this->stencil->addLink('iPhone 4', 'ITH'); ?> featured a higher resolution 960x640 "<?php echo $this->stencil->addLink('Retina display', 'ITH'); ?>", a VGA front facing camera for video calling and other apps, and a 5 megapixel rear facing camera with 720p video capture. The <?php echo $this->stencil->addLink('iPhone 4S', 'ITH'); ?> upgrades to an 8 megapixel camera with 1080p video recording, a dual-core A5 processor, and a natural language voice control system called <?php echo $this->stencil->addLink('Siri', 'IT'); ?>. iPhone 5 features the dual-core A6 processor, increases the size of the Retina display to 4 inches, introduces LTE support and replaces the 30-pin connector with an all-digital Lightning connector. The iPhone 5S features the dual-core 64-bit A7 processor, an updated camera with a larger aperture and dual-LED flash, and the Touch ID fingerprint scanner, integrated into the home button. The iPhone 5C features the same A6 chip as the iPhone 5, along with a new backside illuminated FaceTime camera and a new casing made of polycarbonate. The <?php echo $this->stencil->addLink('iPhone 6', 'ITH'); ?> and <?php echo $this->stencil->addLink('iPhone 6 Plus', 'ITH'); ?> further increased screen size, measuring at 4.7 inches and 5.5 inches, respectively. In addition, they also feature a new A8 chip and M8 motion coprocessor. As of 2013, the iPhone 3GS had the longest production run, 1,181 days; followed by the iPhone 4, produced for 1,174 days.</p>
        <p>The resounding sales of the iPhone, at the time, have been credited with reshaping the smartphone industry and helping make Apple one of the world's most valuable publicly traded companies in 2011 - 12.</p>
        <p>In late 2014, JP Morgan estimated "<em>iPhone percentage of the worldwide smartphone install base has been around 15% since late 2012</em>" being far behind the dominant <?php echo $this->stencil->addLink('Android', 'OS'); ?> based smartphones. In a few mature market countries such as Japan, the iPhone has a majority, an exception to Android's dominance, and Australia where Android is rapidly approaching parity. In March 2014, sales of the iPhone brand had reached 500 million devices. In the last quarter of 2014, there were 74.5 million iPhones sold, a record, compared to 51.0 million in the last quarter of 2013. Tim Cook revealed at the <?php echo $this->stencil->addLink('Apple Watch', 'ITH'); ?> conference on 9 March 2015, that Apple had sold a total of 700 million iPhones to date.</p>
    </div>
</div>