<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('LS-120 SuperDisk'); ?>
        <p>Announced in 1995, the "<strong>SuperDisk</strong>" marketed as the <strong>LS-120 drive</strong>, often seen with the brand names <strong>Matsushita</strong> (Panasonic) and <strong>Imation</strong>, had an initial capacity of 120MB using even higher density "LS-120" disks.</p>
        <p>LS in this case stands for <em>Laser Servo</em>, which used a very low power superluminescent LED that generated light with a small focal spot. This allowed the drive to align its rotation to precisely the same point each time, allowing far more data to be written due to the absence of conventional magnetic alignment marks. The alignment was based on hard coded optical alignment marks, which meant that a complete format could be done. This worked very well at the time and as a result failures associated with magnetic fields wiping the ZIP drive alignment Z tracks were less of a problem.</p>
        <p>It was upgraded (as the "<strong>LS-240</strong>") to 240MB. Not only could the drive read and write 1440kB disks, but the last versions of the drives could write 32MB onto a normal 1440kB disk. Unfortunately, popular opinion held the Super Disk disks to be quite unreliable, though no more so than the [Zip drives] and SyQuest Technology offerings of the same period and there were also many reported problems moving standard floppies between LS-120 drives and normal floppy drives. This belief, true or otherwise, crippled adoption. The <?php echo $this->stencil->addLink('BIOS', 'IT'); ?> of many motherboards even to this day supports LS-120 drives as boot options.</p>
        <p>One suggested improvement to LS-240 was the addition of an optical reader based on low resolution B/W CCD technology, as this would be able to detect disk flaws before they could cause data loss and adjust write strategies accordingly. Also it would allow detection of damage caused by head misalignment before the data surface was compromised. Had this ever been implemented then it would have allowed the LS240 to store nearly 500MB of data. This strategy was later implemented on <?php echo $this->stencil->addLink('HP', 'C'); ?> and <?php echo $this->stencil->addLink('Epson', 'C'); ?> printers to allow photo quality printing on normal non-photo paper.</p>
        <p>LS-120 compatible drives were available as options on many computers, including desktop and notebook computers from <?php echo $this->stencil->addLink('Compaq Computer Corporation', 'C'); ?>. In the case of the Compaq notebooks, the LS-120 drive replaced the standard floppy drive in a multi-bay configuration.</p>
    </div>
</div>