<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Timex Datalink'); ?>
        <p><strong>Timex Datalink</strong> is a line of early smartwatches manufactured by <strong>Timex</strong> and is considered a wristwatch computer. It is the first watch capable of downloading information from a computer. As the name implies datalink watches are capable of data transfer through linking with a computer. The Datalink line was introduced in 1994 and it was co-developed with <?php echo $this->stencil->addLink('Microsoft', 'C'); ?> as a wearable alternative to mainstream <?php echo $this->stencil->addLink('PDA', 'ITH'); ?>s with additional attributes such as water resistance, that PDAs lacked, and easy programmability. The early models included models 50, 70, 150 and model 150s (small size). The model numbers indicated the approximate number of phone numbers that could be stored in the watch memory. These early models were, at the time of their introduction, the only watches to bear the Microsoft logo. The watches have been certified by NASA for space travel and have been used by astronauts and cosmonauts in space missions. There had been an evolution over the years as to the number and type of entries that can be stored in the various watch models as well as the mode of data transfer between computer and watch. At the time of its introduction the watch was considered high-tech.</p>
        <p>There is also the <strong>Timex Beepwear Datalink</strong> series featuring wearable pagers using the Timex datalink platform which also function as electronic organisers.</p>
        <p>Although there are other watches capable of storing all kinds of data, they usually had a small keyboard that could be used to input data. The keyboard was tiny and made data input difficult and tedious and decreased the toughness and water resistance, if any, of the watch. Moreover as soon as the battery expired one had to manually re-input the data.</p>
        <p>The Timex Datalink watches were unique because the watch could synchronise wirelessly through light with the computer and data was transferred from the computer to the watch quickly and easily. Further, since the files were stored in the computer they could be edited in the computer and if the watch battery had to be replaced, loss of files in the watch due to reset was no problem, since they could be easily downloaded as many times as needed.</p>
        <p>The data files were accessible via the Timex-Microsoft co-developed special Datalink interface that resided in the computer. In addition the absence of a keyboard made the watch compact, water resistant and no different at first glance from any other digital watch.</p>
        <p>Upon closer inspection however a small lens at the position of 12 o'clock on the watch face indicated the mode of the wireless data transmission through visible light. Data was transmitted from the <?php echo $this->stencil->addLink('CRT', 'ITH'); ?> of the computer through a series of pulsating horizontal bars, that were then focused by the tiny lens and inputted into the watch <?php echo $this->stencil->addLink('EEPROM', 'ITH'); ?> memory through an optoelectronic transducer operating in the visible light spectrum and employing optical scanning technology.</p>
        <p>The CRT synchronisation was possible only for systems operating on <?php echo $this->stencil->addLink('Windows 95', 'WIN'); ?> and <?php echo $this->stencil->addLink('Windows 98', 'WIN'); ?>. The watch was compatible with <?php echo $this->stencil->addLink('Schedule+', 'ITS'); ?> and for the Datalink 70 model the time needed to download seventy phone numbers was about twenty seconds.</p>
    </div>
</div>