<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Linux'); ?>
        <p><strong>Linux</strong> is a <?php echo $this->stencil->addLink('Unix like', 'OS'); ?> and <?php echo $this->stencil->addLink('POSIX compliant', 'IT'); ?> computer operating system assembled under the model of free and open source software development and distribution.</p>
        <p>The main form of distribution are Linux distributions. The defining component of Linux is the <?php echo $this->stencil->addLink('Linux kernel', 'OS'); ?>, an operating system kernel first released on 5 October 1991, by <?php echo $this->stencil->addLink('Linus Torvalds', 'P'); ?>.</p>
        <p>Because it considers Linux to be a variant of the GNU operating system, initiated in 1983 by Richard Stallman, the Free Software Foundation prefers the name GNU/Linux when referring to the operating system</p>
        <p>Linux was originally developed as a free operating system for <?php echo $this->stencil->addLink('Intel x86', 'CPU'); ?> based personal computers. It has since been ported to more computer hardware platforms than any other operating system. It is a leading operating system on servers and other big iron systems such as mainframe computers and supercomputers. More than 90% of today's 500 fastest supercomputers run some variant of Linux, including the 10 fastest.</p>
        <p>Linux also runs on embedded systems (devices where the operating system is typically built into the firmware and highly tailored to the system) such as mobile phones, tablet computers, network routers, building automation controls, televisions and video game consoles; the <?php echo $this->stencil->addLink('Android', 'OS'); ?> system in wide use on mobile devices is built on the Linux kernel.</p>

        <h2>Naming</h2>
        <p>Linus Torvalds had wanted to call his invention <strong>Freax</strong>, a portmanteau of "free", "freak", and "x" (as an allusion to Unix). During the start of his work on the system, he stored the files under the name "Freax" for about half of a year. Torvalds had already considered the name "Linux," but initially dismissed it as too egotistical.</p>
        <p>In order to facilitate development, the files were uploaded to the <?php echo $this->stencil->addLink('FTP', 'IPA'); ?> server (<code>ftp.funet.fi</code>) of FUNET in September 1991. Ari Lemmke, Torvald's coworker at the Helsinki University of Technology (HUT) who was one of the volunteer administrators for the FTP server at the time, did not think that "Freax" was a good name. So, he named the project "Linux" on the server without consulting Torvalds. Later, however, Torvalds consented to "Linux".</p>
    </div>
</div>