<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Unix-like'); ?>
        <p>A <strong>Unix-like</strong> (sometimes referred to as <strong>UN*X</strong> or <strong>*nix</strong>) <?php echo $this->stencil->addLink('Operating System', 'IT'); ?> is one that behaves in a manner similar to a <?php echo $this->stencil->addLink('Unix', 'OS'); ?> system, while not necessarily conforming to or being certified to any version of the Single UNIX Specification.</p>
        <p>There is no standard for defining the term, and some difference of opinion is possible as to the degree to which a given operating system is "Unix-like".</p>
        <p>The term can include free and open-source operating systems inspired by <?php echo $this->stencil->addLink('Bell Labs', 'C'); ?>' Unix or designed to emulate its features, commercial and proprietary work-alikes, and even versions based on the licensed UNIX source code (which may be sufficiently "Unix-like" to pass certification and bear the "UNIX" trademark).</p>
        <p>The <strong>Open Group</strong> owns the UNIX trademark and administers the Single UNIX Specification, with the "UNIX" name being used as a certification mark. They do not approve of the construction "Unix-like", and consider it a misuse of their trademark. Their guidelines require "UNIX" to be presented in uppercase or otherwise distinguished from the surrounding text, strongly encourage using it as a branding adjective for a generic word such as "system", and discourage its use in hyphenated phrases.</p>
        <p>Other parties frequently treat "Unix" as a generalised trademark. Some add a wildcard character to the name to make an abbreviation like "Un*x" or "*nix", since Unix-like systems often have Unix-like names such as AIX, A/UX, HP-UX, IRIX, Linux, Minix, Ultrix, and Xenix. These patterns do not literally match many system names, but are still generally recognised to refer to any UNIX descendant or work-alike system, even those with completely dissimilar names such as <?php echo $this->stencil->addLink('Solaris', 'OS'); ?> or <?php echo $this->stencil->addLink('FreeBSD', 'OS'); ?>.</p>
        <p>In 2007, <strong>Wayne R. Gray</strong> sued to dispute the status of UNIX as a trademark, but lost his case, and lost again on appeal, with the court upholding the trademark and its ownership.</p>
        <p>"Unix-like" systems started to appear in the late 1970s and early 1980s. Many proprietary versions, such as Idris (1978), UNOS (1982), Coherent (1983), and UniFlex (1985), aimed to provide businesses with the functionality available to academic users of UNIX.</p>
        <p>When AT&amp;T allowed relatively inexpensive commercial binary sub-licensing of UNIX in 1979, a variety of proprietary systems were developed based on it, including AIX, HP-UX, IRIX, SunOS, Tru64, Ultrix, and Xenix. These largely displaced the proprietary clones. Growing incompatibility among these systems led to the creation of interoperability standards, including POSIX<?php echo $this->stencil->addLink('POSIX', 'IT'); ?> and the Single UNIX Specification.</p>
        <p>Meanwhile, the <strong>GNU Project</strong> was launched in 1983 with the goal of making GNU, an operating system which all computer users could freely use, study, modify, and redistribute. Various "Unix-like" operating systems developed alongside GNU, frequently sharing substantial components with it (leading to some disagreement about whether they should be called "GNU" or not). These primarily served as low-cost and unrestricted substitutes for UNIX, and include 4.4BSD, <?php echo $this->stencil->addLink('Linux', 'OS'); ?>, and Minix. Some of these have in turn been the basis for commercial "Unix-like" systems, such as BSD/OS and <?php echo $this->stencil->addLink('OS X', 'OS'); ?>. Notably, <?php echo $this->stencil->addLink('Mac OS X Leopard', 'OSX'); ?> (10.5), <?php echo $this->stencil->addLink('Mac OS X Show Leopard', 'OSX'); ?> (10.6), <?php echo $this->stencil->addLink('OS X Mountain Lion', 'OSX'); ?> (10.8), <?php echo $this->stencil->addLink('OS X Mavericks', 'OSX'); ?> (10.9),[8] and <?php echo $this->stencil->addLink('OS X Yosemite', 'OSX'); ?> (10.10), running on Intel Macs are certified under the Single UNIX Specification.</p>
        <p>The various <?php echo $this->stencil->addLink('BSD', 'OS'); ?> variants are notable in that they are in fact descendants of UNIX, developed by the University of California at Berkeley with UNIX source code from Bell Labs. However, the BSD code base has evolved since then, replacing all of the AT&amp;T code. Since the BSD variants are not certified as compliant with the Single UNIX Specification (except for Mac OS X 10.5 Leopard and later), they are referred to as "UNIX-like".</p>
    </div>
</div>
