<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Layout Engine'); ?>
        <p>A <strong>web browser engine</strong> (also called <strong>layout engine</strong> or <strong>rendering engine</strong>) is a software component that takes marked up content (such as <?php echo $this->stencil->addLink('HTML', 'WD'); ?>, <?php echo $this->stencil->addLink('XML', 'WD'); ?>, image files, etc.) and formatting information (such as <?php echo $this->stencil->addLink('CSS', 'WD'); ?>, <?php echo $this->stencil->addLink('XSL', 'WD'); ?>, etc.) and displays the formatted content on the screen.</p>
        <p>It draws on the content area of a window, which is displayed on a monitor or a printer.</p>
        <p>A layout engine is typically embedded in <?php echo $this->stencil->addLink('Web Browser', 'WD'); ?>, e-mail clients, e-book readers, on-line help systems or other applications that require the displaying of web content.</p>
        <p>Engines may wait for all data to be received before rendering a page, or may begin rendering before all data is received.</p>
        <p>This can result in pages changing as more data is received, such as images being filled in or a flash of unstyled content (<?php echo $this->stencil->addLink('FOUC', 'WD'); ?>) if rendering begins before formatting information is received.</p>
        <p><?php echo $this->stencil->addLink('KDE', 'C'); ?>'s open-source <?php echo $this->stencil->addLink('KHTML', 'web-development/layput-engines'); ?> engine is used in KDE's <?php echo $this->stencil->addLink('Konqueror', 'WB'); ?> Web browser and was the basis for <?php echo $this->stencil->addLink('WebKit', 'web-developer/layout-engines'); ?>, the rendering engine in <?php echo $this->stencil->addLink('Apple', 'C'); ?>'s <?php echo $this->stencil->addLink('Safari', 'WB'); ?> and <?php echo $this->stencil->addLink('Google', 'C'); ?>'s {'Chrome'|link_urls:'w'} <?php echo $this->stencil->addLink('Chrome', 'WB'); ?>web browsers.</p>
        <p>Current versions of Chromium / Chrome (except <?php echo $this->stencil->addLink('iOS', 'OS'); ?> version) and <?php echo $this->stencil->addLink('Opera', 'WB'); ?> are based on <?php echo $this->stencil->addLink('Blink', 'web-development/layout-engines'); ?>, a fork of WebKit.</p>
        <p><?php echo $this->stencil->addLink('gecko', 'web-development/layout-engines'); ?>, the <?php echo $this->stencil->addLink('Mozilla', 'C'); ?> project's open-source web browser engine, is used by a variety of products derived from the Mozilla code base, including the <?php echo $this->stencil->addLink('Firefox', 'WB'); ?> web browser, the <?php echo $this->stencil->addLink('Thunderbird', 'WD'); ?> e-mail client, and <?php echo $this->stencil->addLink('SeaMonkey', 'WB'); ?> internet suite.</p>
        <p><?php echo $this->stencil->addLink('Trident', 'web-development/layout-engines'); ?>, the web browser engine from <?php echo $this->stencil->addLink('Internet Explorer', 'WB'); ?>, is used by many applications on the <?php echo $this->stencil->addLink('Microsoft Windows', 'OS'); ?> platform, such as netSmart, Outlook Express, some versions of <?php echo $this->stencil->addLink('Microsoft Outlook', 'ITS'); ?>, and the mini-browsers in Winamp and RealPlayer.</p>
        <p><?php echo $this->stencil->addLink('Opera', 'WB'); ?> Software's proprietary <?php echo $this->stencil->addLink('Presto', 'web-development/layout-engines'); ?> engine is licensed to a number of other software vendors, and was used in Opera's own web browser.</p>
    </div>
</div>