<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('The Slashdot Effect'); ?>
        <p><strong>The Slashdot effect</strong>, also known as <strong>slashdotting</strong>, occurs when a popular website links to a smaller site, causing a massive increase in traffic. This overloads the smaller site, causing it to slow down or even temporarily become unavailable.</p>
        <p>The name stems from the huge influx of web traffic that would result from the technology news site <?php echo $this->stencil->addLink('Slashdot', 'URL'); ?> linking to websites. However the name is somewhat dated as flash crowds from Slashdot were reported to be diminishing as of 2005 due to competition from similar sites.</p>
        <p>The effect has been associated with other websites or metablogs such as Fark, <?php echo $this->stencil->addLink('Digg', 'URL'); ?>, Drudge Report, Reddit, and <?php echo $this->stencil->addLink('Twitter', 'URL'); ?>, leading to terms such as being Farked or Drudged, being under the Reddit effect, or receiving a "hug of death" from the site in question. Google Doodles, which link to search results on the doodle topic, also result in high increases of traffic from the search results page.</p>
        <p>Typically, less robust sites are unable to cope with the huge increase in traffic and become unavailable – common causes are lack of sufficient data bandwidth, servers that fail to cope with the high number of requests, and traffic quotas. Sites that are maintained on shared hosting services often fail when confronted with the Slashdot effect.</p>
        <p>A <strong>flash crowd</strong> is a more generic term without using any specific name that describes a network phenomenon where a network or host suddenly receives a lot of traffic. This is sometimes due to the appearance of a web site on a blog or news column.</p>
        <p>According to the <strong>Jargon File</strong>, the term "<em>Slashdot effect</em>" refers to phenomenon of a website becoming virtually unreachable because too many people are hitting it after the site was mentioned in an interesting article on the popular Slashdot news service.</p>
        <p>It was later extended to describe any similar effect from being listed on a popular site, similar to the more generic term, <em>flash crowd</em>, which is a more appropriate term.</p>
        <p>The term "<em>flash crowd</em>" was coined in 1973 by <strong>Larry Niven</strong> in his science fiction short story, <strong><em>Flash Crowd</em></strong>. It predicted that a consequence of inexpensive teleportation would be huge crowds materialising almost instantly at the sites of interesting news stories. Twenty years later, the term became commonly used on the Internet to describe exponential spikes in website or server usage when it passes a certain threshold of popular interest. This effect was anticipated years earlier in 1956 in <strong>Alfred Bester</strong>'s novel <strong><em>The Stars My Destination</em></strong>.</p>
    </div>
</div>