<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Web Server'); ?>
        <p>A <strong>Web server</strong> is an information technology that processes requests via <?php echo $this->stencil->addLink('HTTP', 'IPA'); ?>, the basic network protocol used to distribute information on the <?php echo $this->stencil->addLink('World Wide Web', 'WD'); ?>. The term can refer either to the entire computer system, an appliance, or specifically to the software that accepts and supervises the HTTP requests.</p>
        <p>The primary function of a web server is to store, process and deliver web pages to clients. The communication between client and server takes place using the <strong>Hypertext Transfer Protocol (HTTP)</strong>. Pages delivered are most frequently <?php echo $this->stencil->addLink('HTML', 'WD'); ?> documents, which may include images, style sheets and scripts in addition to text content.</p>
        <p>A user agent, commonly a <?php echo $this->stencil->addLink('Web browser', 'WD'); ?> or Web crawler, initiates communication by making a request for a specific resource using HTTP and the server responds with the content of that resource or an error message if unable to do so. The resource is typically a real file on the server's secondary storage, but this is not necessarily the case and depends on how the web server is implemented.</p>
        <p>While the primary function is to serve content, a full implementation of HTTP also includes ways of receiving content from clients. This feature is used for submitting web forms, including uploading of files.</p>
        <p>Many generic web servers also support server-side scripting using <?php echo $this->stencil->addLink('ASP', 'L'); ?>, <?php echo $this->stencil->addLink('PHP', 'L'); ?>, or other scripting languages. This means that the behaviour of the Web server can be scripted in separate files, while the actual server software remains unchanged. Usually, this function is used to generate HTML documents dynamically ("on-the-fly") as opposed to returning static documents. The former is primarily used for retrieving and / or modifying information from databases. The latter is typically much faster and more easily cached but cannot deliver dynamic content.</p>
        <p>Web servers are not always used for serving the World Wide Web. They can also be found embedded in devices such as printers, routers, webcams and serving only a local network. The web server may then be used as a part of a system for monitoring and / or administering the device in question. This usually means that no additional software has to be installed on the client computer, since only a Web browser is required (which now is included with most operating systems).</p>
        <p>In 1989 <?php echo $this->stencil->addLink('Tim Berners-Lee', 'P'); ?> proposed a new project to his employer <?php echo $this->stencil->addLink('CERN', 'C'); ?>, with the goal of easing the exchange of information between scientists by using a hypertext system. The project resulted in Berners-Lee writing two programs in 1990:</p>
        <ul>
            <li>A browser called <?php echo $this->stencil->addLink('WorldWideWeb', 'WB'); ?>.</li>
            <li>The world's first web server, later known as <?php echo $this->stencil->addLink('CERN httpd', 'WS'); ?>, which ran on <?php echo $this->stencil->addLink('NeXTSTEP', 'OS'); ?>.</li>
        </ul>
        <p>Between 1991 and 1994, the simplicity and effectiveness of early technologies used to surf and exchange data through the World Wide Web helped to port them to many different operating systems and spread their use among scientific organisations and universities, and then to industry.</p>
        <p></p>In 1994 Tim Berners-Lee decided to constitute the <strong>World Wide Web Consortium (<?php echo $this->stencil->addLink('W3C', 'C'); ?>)</strong> to regulate the further development of the many technologies involved (HTTP, HTML, etc.) through a standardisation process.</p>
    </div>
</div>