<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Wireless Markup Language (WML)'); ?>
        <p><strong>Wireless Markup Language (WML)</strong>, based on <?php echo $this->stencil->addLink('XML', 'WD'); ?>, is a markup language intended for devices that implement the <strong>Wireless Application Protocol (<?php echo $this->stencil->addLink('WAP', 'ITN'); ?>)</strong> specification, such as mobile phones. It provides navigational support, data input, hyperlinks, text and image presentation, and forms, much like <?php echo $this->stencil->addLink('HTML', 'WD'); ?> (HyperText Markup Language). It preceded the use of other markup languages now used with WAP, such as HTML itself, and <?php echo $this->stencil->addLink('XHTML', 'WD'); ?> (which are gaining in popularity as processing power in mobile devices increases).</p>
        <p>Building on Openwave's <?php echo $this->stencil->addLink('HDML', 'WD'); ?>, Nokia's Tagged Text Markup Language (<?php echo $this->stencil->addLink('TTML', 'WD'); ?>) and Ericsson's proprietary markup language for mobile content, the WAP Forum created the WML 1.1 standard in 1998. WML 2.0 was specified in 2001, but has not been widely adopted. It was an attempt at bridging WML and XHTML Basic before the WAP 2.0 spec was finalised. In the end, XHTML Mobile Profile became the markup language used in WAP 2.0. The newest WML version in active use is 1.3.</p>
        <p>The first company to launch a public WML site was Dutch mobile phone network operator <strong>Telfort</strong> in October 1999 and the first company in the world to launch the Nokia 7110. The Telfort WML site was created and developed as side project to test the device's capabilities by a billing engineer called Christopher Bee and National Deployment Manager, Euan McLeod. The WML site consists of four pages in both Dutch and English that contained many grammatical errors in Dutch as the two developers were unaware the WML was configured on the Nokia 7110 as the home page and neither were native Dutch speakers.</p>
    </div>
</div>

