<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Programming Language'); ?>
        <?php $this->stencil->setDescription('Language used by programmers to write instructions that a computer can understand to do what the programmer (or the computer user) wants.'); ?>
        <?php $this->stencil->meta(array('keywords' => 'Programming Languages, PHP, ASP, BASIC, Pascal, ColdFusion, C')); ?>
        <p>A <strong>programming language</strong> is a formal constructed language designed to communicate instructions to a machine, particularly a computer. Programming languages can be used to create programs to control the behaviour of a machine or to express algorithms.</p>
        <p>The earliest programming languages preceded the invention of the digital computer and were used to direct the behaviour of machines such as Jacquard looms and player pianos. Thousands of different programming languages have been created, mainly in the computer field, and many more still are being created every year. Many programming languages require computation to be specified in an imperative form (i.e., as a sequence of operations to perform), while other languages utilize other forms of program specification such as the declarative form (i.e. the desired result is specified, not how to achieve it).</p>
        <p>The description of a programming language is usually split into the two components of <?php echo $this->stencil->addLink('syntax', 'IT'); ?> (form) and semantics (meaning). Some languages are defined by a specification document (for example, the <?php echo $this->stencil->addLink('C', 'L'); ?> programming language is specified by an <?php echo $this->stencil->addLink('ISO', 'C'); ?> Standard), while other languages (such as <?php echo $this->stencil->addLink('Perl', 'L'); ?>) have a dominant implementation that is treated as a reference.</p>
     </div>
</div>