<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Safari'); ?>
        <p><strong>Safari</strong> is a <?php echo $this->stencil->addLink('Web browser', 'WD'); ?> developed by <?php echo $this->stencil->addLink('Apple Inc', 'C'); ?> and included with the <?php echo $this->stencil->addLink('OS X', 'OS'); ?> and <?php echo $this->stencil->addLink('iOS', 'OS'); ?> operating systems.</p>
        <p>First released as a public beta on 7 January 2003, on the company's OS X operating system, it became Apple's default browser beginning with <?php echo $this->stencil->addLink('Mac OS X v10.3', 'OSX'); ?> "Panther". Safari is also the native browser for iOS.</p>
        <p>A version of Safari for the <?php echo $this->stencil->addLink('Windows', 'OS'); ?> operating system was first released on 11 June 2007, and supported <?php echo $this->stencil->addLink('Windows XP', 'WIN'); ?> Service Pack 2, or later, but it has been discontinued. <?php echo $this->stencil->addLink('Safari 5.1.7', 'WB'); ?>, released on 9 May 2012, is the last version available for Windows.</p>
        <p>Until 1997, <?php echo $this->stencil->addLink('Apple Macintosh', 'ITH'); ?> computers were shipped with the <?php echo $this->stencil->addLink('Netscape Navigator', 'WB'); ?>and <?php echo $this->stencil->addLink('Cyberdog', 'WB'); ?> Web browsers only.</p>
        <p><?php echo $this->stencil->addLink('Internet Explorer for Mac', 'IE'); ?> was later included as the default Web browser for <?php echo $this->stencil->addLink('Mac OS 8.1', 'MOS'); ?> and onwards, as part of a five year agreement between Apple and <?php echo $this->stencil->addLink('Microsoft', 'C'); ?>.</p>
        <p>During that time, Microsoft released three major versions of Internet Explorer for Mac that were bundled with <?php echo $this->stencil->addLink('Mac OS 8', 'MOS'); ?> and <?php echo $this->stencil->addLink('Mac OS 9', 'MOS'); ?>, though Apple continued to include Netscape Navigator as an alternative.</p>
        <p>Microsoft ultimately released a <?php echo $this->stencil->addLink('Mac OS X', 'OS'); ?> edition of Internet Explorer for Mac, which was included as the default browser in all Mac OS X releases from Mac OS X DP4 up to and including Mac OS X v10.2.</p>
        <p>On 7 January 2003, at Macworld San Francisco, <?php echo $this->stencil->addLink('Steve Jobs', 'P'); ?> announced that Apple had developed their own web browser, called Safari. It was based on Apple's internal fork of the <?php echo $this->stencil->addLink('KHTML', 'web-development/layout-engine'); ?> rendering engine, called <?php echo $this->stencil->addLink('WebKit', 'web-development/layout-engines'); ?>. Apple released the first beta version for OS X that day.</p>
        <p>A number of official and unofficial beta versions followed, until version 1.0 was released on 23 June 2003.</p>
        <p>Initially only available as a separate download for <?php echo $this->stencil->addLink('Mac OS X v10.2', 'OSX'); ?>, it was included with the <?php echo $this->stencil->addLink('Mac OS X v10.3', 'OSX'); ?> release on 24 October 2003 as the default browser, with Internet Explorer for Mac included only as an alternative browser.</p>
    </div>
</div>
