<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('SHA-1 Secure Hash Algorithm'); ?>
        <p>In cryptography, <strong>SHA-1</strong> is a cryptographic hash function designed by the United States National Security Agency and is a U.S. Federal Information Processing Standard published by the United States NIST.</p>
        <p>SHA-1 produces a 160-bit (20-byte) hash value known as a message digest. A SHA-1 hash value is typically rendered as a hexadecimal number, 40 digits long.</p>
        <p>SHA stands for "<strong>secure hash algorithm</strong>". The four SHA algorithms are structured differently and are named <?php echo $this->stencil->addLink('SHA-0', 'IT'); ?>, SHA-1, <?php echo $this->stencil->addLink('SHA-2', 'IT'); ?>, and <?php echo $this->stencil->addLink('SHA-3', 'IT'); ?>. SHA-0 is the original version of the 160-bit hash function published in 1993 under the name "SHA": it was not adopted by many applications. Published in 1995, SHA-1 is very similar to SHA-0, but alters the original SHA hash specification to correct alleged weaknesses. SHA-2, published in 2001, is significantly different from the SHA-1 hash function.</p>
        <p>SHA-1 is the most widely used of the existing SHA hash functions, and is employed in several widely used applications and protocols.</p>
        <p>In 2005, cryptanalysts found attacks on SHA-1 suggesting that the algorithm might not be secure enough for ongoing use. NIST required many applications in federal agencies to move to SHA-2 after 2010 because of the weakness. Although no successful attacks have yet been reported on SHA-2, it is algorithmically similar to SHA-1. In 2012, following a long-running competition, NIST selected an additional algorithm, <strong>Keccak</strong>, for standardisation under SHA-3. In November 2013 <?php echo $this->stencil->addLink('Microsoft', 'C'); ?> announced their deprecation policy on SHA-1 according to which <?php echo $this->stencil->addLink('Windows', 'OS'); ?> will stop accepting SHA-1 certificates in SSL by 2017. In September 2014 <?php echo $this->stencil->addLink('Google', 'C'); ?> announced their deprecation policy on SHA-1 according to which <?php echo $this->stencil->addLink('Chrome', 'WB'); ?> will stop accepting SHA-1 certificates in SSL in a phased way by 2017. <?php echo $this->stencil->addLink('Mozilla', 'C'); ?> is also planning to stop accepting SHA-1-based SSL certificates by 2017.</p>
    </div>
</div>