<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('4DOS'); ?>
        <p><strong>4DOS</strong> is a command line interpreter by <strong>JP Software</strong>, designed to replace the default command interpreter <code>COMMAND.COM</code> in <?php echo $this->stencil->addLink('DOS', 'OS'); ?> and <?php echo $this->stencil->addLink('Windows', 'OS'); ?> 95/98/SE/ME. The 4DOS family of programs are meant to replace the default command processor. 4OS2 and 4NT replace <code>CMD.EXE</code> in <?php echo $this->stencil->addLink('OS/2', 'OS'); ?> and <?php echo $this->stencil->addLink('Windows NT', 'WIN'); ?> respectively. 4DOS was written by <strong>Rex Conn</strong> and <strong>Tom Rawson</strong>; it was first released in 1989.</p>
        <p>A graphical version of 4DOS, 4OS2, and 4NT, called <strong>Take Command</strong> was released with a feature set corresponding to version 4DOS 5.5, 4OS2, and 4NT 2.5 and updated after this. Development on this line stopped with the corresponding character-mode versions. There was a graphical program Take Command/16, for <?php echo $this->stencil->addLink('Windows 3.1', 'WIN'); ?>.</p>
        <p>4OS2 is a similar replacement for <?php echo $this->stencil->addLink('IBM', 'C'); ?>'s <?php echo $this->stencil->addLink('OS/2', 'OS'); ?> command interpreter. This was first released at the same time as 4DOS version 4, and has a similar feature set. Like 4DOS, this is released as open source, and is still being actively developed. It appears in the feature set of 2011's eComStation 2.10, and in the freeware os2free project. Take Command for OS/2 is not currently being developed.</p>
        <p>4NT was first released as 4DOS for Windows NT (versions 1.x, 2.x), but became 4NT until the restructure after version 8. The program is a recompile of 4OS2, and continues to have features of OS/2's command processor (<code>CMD.EXE</code>), such as running REXX scripts, and EXTPROC support. A corresponding Take Command/32 exists for this, version 1 corresponding to 4NT 2.5. 4NT and Take Command/32 were released in both ANSI (<?php echo $this->stencil->addLink('Windows 9x', 'WIN'); ?>) and Unicode (Windows NT) forms, with the ANSI version dropped at version 5.</p>
        <p>A new Win32 program <strong>Tabbed Command Interface (TCI)</strong>, was released at the time of 4NT version 7. This program allowed one to attach (thereby reducing screen clutter) and unattach tabbed consoles to a single window. This program requires <?php echo $this->stencil->addLink('Windows XP', 'WIN'); ?> or later.</p>
    </div>
</div>