<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Enhanced Graphics Adapter (EGA)'); ?>
        <p>The <strong>Enhanced Graphics Adapter (EGA)</strong> is an <?php echo $this->stencil->addLink('IBM PC', 'PC'); ?> computer display standard specification which is between <?php echo $this->stencil->addLink('CGA', 'VID'); ?> and <?php echo $this->stencil->addLink('VGA', 'VID'); ?> in terms of colour and space resolution. Introduced in October 1984 by <?php echo $this->stencil->addLink('IBM', 'C'); ?> shortly after (but not exclusively for) its new <?php echo $this->stencil->addLink('PC/AT', 'PC'); ?>, EGA produces a display of 16 simultaneous colours from a palette of 64 at a resolution of up to 640x350 pixels, a bit more than <?php echo $this->stencil->addLink('Tandy', 'VID'); ?> which can do up to 16 simultaneous colours from the same palette at a resolution of up to 320x200 but only 4 colours at 640x200. The EGA card includes a 16KB ROM to extend the system <?php echo $this->stencil->addLink('BIOS', 'IT'); ?> for additional graphics functions, and includes a custom <?php echo $this->stencil->addLink('CRT', 'ITH'); ?> controller that has a backward compatibility mode with <strong>Motorola MC6845</strong> chip.</p>
        <p>Each of the 16 colours can be assigned a unique <?php echo $this->stencil->addLink('RGB', 'IT'); ?> colour code via a palette mechanism in the 640x350 high-resolution mode; the 64 palette colours are a balanced RGB colour set comprising all possible combinations of two bits per pixel for red, green and blue. EGA also includes full 16-colour versions of the <?php echo $this->stencil->addLink('CGA', 'VID'); ?> 640x200 and 320x200 graphics modes; only the 16 CGA/RGBI colours are available in these modes. EGA 4-bit (16 colours) graphic modes are also notable for a sophisticated use of bit planes and mask registers together with CPU bitwise operations, which constitutes an early graphics accelerator inherited by <?php echo $this->stencil->addLink('VGA', 'VID'); ?> and numerous compatible hardware.</p>
        <p>EGA is dual-sync; it scans at 23 kHz when 350-line modes are used and 15 kHz when 200-line modes are used. The original CGA modes are also present, though EGA is not 100% hardware compatible with CGA. EGA can drive an <?php echo $this->stencil->addLink('MDA', 'VID'); ?> monitor by a special setting of switches on the board; only 640x350 high-resolution monochrome graphics and the standard MDA text mode are available in this mode.</p>
        <p>EGA cards use the PC <?php echo $this->stencil->addLink('ISA', 'ITH'); ?> bus and were available starting in 8-bit versions. The original IBM EGA card had 64k of onboard RAM and required a daughterboard to add an additional 64k (cards with 64k are limited to 4 colours when 640x350 mode is used). All third-party cards came with 128k already installed and some even 256k, allowing multiple graphics pages. A few third-party EGA clones (notably the <strong>ATI Technologies</strong> and <strong>Paradise</strong> boards) feature a range of extended graphics modes (e.g., 640x400, 640x480 and 720x540), as well as automatic monitor type detection, and sometimes also a special 400-line interlace mode for use on CGA monitors.</p>
        <p>The EGA standard was made obsolete by the introduction in 1987 of <?php echo $this->stencil->addLink('MCHA', 'VID'); ?> with the <?php echo $this->stencil->addLink('PS/2', 'PC'); ?> computer line and VGA.</p>
    </div>
</div>