<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Monochrome Display Adapter (MDA)'); ?>
        <p>The <strong>Monochrome Display Adapter</strong> (<strong>MDA</strong>, also <strong>MDA card</strong>, <strong>Monochrome Display and Printer Adapter, MDPA</strong>) introduced in 1981 was <?php echo $this->stencil->addLink('IBM', 'C'); ?>'s standard video display card and computer display standard for the <?php echo $this->stencil->addLink('PC', 'PC'); ?>. The MDA did not have any pixel addressable graphics modes. It had only a single monochrome text mode (PC video mode 7), which could display 80 columns by 25 lines of high resolution text characters or symbols useful for drawing forms.</p>
        <p>The standard IBM MDA card was equipped with four kilobytes (kB) of video memory. The MDA's high character resolution (sharpness) was a feature meant to facilitate business and wordprocessing use: Each character was rendered in a box of 9x14 pixels, of which 8x14 made out the character itself (the other pixels being used for space between character columns and lines). Some characters, such as the lowercase "m", were rendered eight pixels across.</p>
        <p>The MDA featured the following character display attributes: invisible, underline, normal, bright (bold), reverse video, and blinking; some of these attributes could be combined, so that e.g. bright, underlined text could be produced.</p>
        <p>The theoretical total screen display resolution of the MDA was 720x350 pixels. This number is arrived at through calculating character width (nine pixels) by columns of text (80) and character height (14 pixels) by rows of text (25). However, the MDA again could not address individual pixels; it could only work in text mode, limiting its choice of display patterns to 256 characters. Its character set is known as code page 437. The character patterns were stored in <?php echo $this->stencil->addLink('ROM', 'IT'); ?> on the card, and so could not be changed by software. The only way to simulate "graphical" screen content was through <?php echo $this->stencil->addLink('ASCII art', 'IT'); ?>.</p>
        <p>Because of the lack of pixel addressable graphics, MDA owners could not play most graphics based games. At least one game, IBM's <strong>One Hundred And One Monochrome Mazes</strong> ("<em>Amazing fun for the whole family</em>"), required MDA. Code page 437 included the standard 127 ASCII characters but also another 127 characters like the aforementioned characters for drawing forms. Some of these shapes would later show up in <?php echo $this->stencil->addLink('Unicode', 'IT'); ?> as box-drawing characters. The characters were also used in early PC games such as early <?php echo $this->stencil->addLink('BBS', 'WD'); ?> door games, or games like <strong>Castle Adventure</strong> by Kevin Bales.</p>
        <p>IBM's original MDA included a parallel printer port (hence its original name of "Monochrome Display and Printer Adapter"), thus avoiding the need for a separate parallel interface on computers fitted with an MDA.</p>
    </div>
</div>