<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Super VGA'); ?>
        <p><strong>Super Video Graphics Array</strong> or <strong>Ultra Video Graphics Array</strong>, almost always abbreviated to <strong>Super VGA</strong>, <strong>Ultra VGA</strong> or just <strong>SVGA</strong> or <strong>UVGA</strong> is a broad term that covers a wide range of computer display standards.</p>
        <p>Originally, it was an extension to the <?php echo $this->stencil->addLink('VGA', 'VID'); ?> standard first released by <?php echo $this->stencil->addLink('IBM', 'C'); ?> in 1987. Unlike VGA a purely IBM defined standard Super VGA was never formally defined. The closest to an "official" definition was in the VBE extensions defined by the <strong>Video Electronics Standards Association (<?php echo $this->stencil->addLink('VESA', 'C'); ?>)</strong>, an open consortium set up to promote interoperability and define standards. In this document, there was simply a footnote stating that "<em>The term 'Super VGA' is used in this document for a graphics display controller implementing any superset of the standard IBM VGA display adapter</em>". When used as a resolution specification, in contrast to VGA or <?php echo $this->stencil->addLink('XGA', 'VID'); ?> for example, the term SVGA normally refers to a resolution of 800x600 pixels.</p>
        <p>Though Super VGA cards appeared in the same year as VGA (1987), it wasn't until 1989 that a standard for programming Super VGA modes was defined by VESA. In that first version, it defined support for (but did not require) a maximum resolution of 800x600 4-bit pixels. Each pixel could therefore be any of 16 different colours. It was quickly extended to 1024x768 8-bit pixels, and well beyond that in the following years.</p>
        <p>Although the number of colours is defined in the VBE specification, this is irrelevant when referring to Super VGA monitors as (in contrast to the old <?php echo $this->stencil->addLink('CGA', 'VID'); ?> and <?php echo $this->stencil->addLink('EGA', 'VID'); ?> standards) the interface between the video card and the VGA or Super VGA monitor uses simple analog voltages to indicate the desired colour. In consequence, so far as the monitor is concerned, there is no theoretical limit to the number of different colours that can be displayed. This applies to any VGA or Super VGA monitor.</p>
        <p>While the output of a VGA or Super VGA video card is analog, the internal calculations the card performs in order to arrive at these output voltages are entirely digital. To increase the number of colours a Super VGA display system can reproduce, no change at all is needed for the monitor, but the video card needs to handle much larger numbers and may well need to be redesigned from scratch. Even so, the leading graphics chip vendors were producing parts for high-colour video cards within just a few months of Super VGA's introduction.</p>
        <p>On paper, the original Super VGA was to be succeeded by <strong>Super XGA</strong>, but in practice the industry soon abandoned the attempt to provide a unique name for each higher display standard, and almost all display systems made between the late 1990s and the early 2000s are classed as Super VGA.</p>
        <p>Monitor manufacturers sometimes advertise their products as XGA or Super XGA. In practice this means little, since all Super VGA monitors manufactured since the later 1990s have been capable of at least XGA and usually considerably higher performance.</p>
        <p>SVGA uses a VGA connector, the same DE-15 (a.k.a. HD-15) as the original standard.</p>
    </div>
</div>