<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('VT100'); ?>
        <p>The <strong>VT100</strong> is a video terminal, introduced in August 1978 by <strong>Digital Equipment Corporation (<?php echo $this->stencil->addLink('DEC', 'C'); ?>)</strong>. It was one of the first terminals to support <?php echo $this->stencil->addLink('ANSI escape codes', 'IT'); ?> for cursor control and other tasks, and added a number of extended codes for special features like controlling the LED lamps on the keyboard. This led to rapid uptake of the ANSI standard, becoming the de facto standard for terminal emulators.</p>
        <p>The VT100s, especially the VT102, was extremely successful in the market, and made DEC the leading terminal vendor for some time. The VT100 series was replaced by the <?php echo $this->stencil->addLink('VT200', 'VT'); ?> series starting in 1983, which proved just as successful. Ultimately, over six million terminals in the VT series would be sold, based largely on the success of the VT100s.</p>
        <p>The VT100 was introduced in August 1978, replacing the VT50 / <?php echo $this->stencil->addLink('VT52', 'VT'); ?> family. Like the earlier models, it communicated with its host system over serial lines using the ASCII character set and control sequences. Unlike the VT52's custom control sequences, the VT100 used sequences standardised by ANSI. The VT100 was also the first Digital mass-market terminal to incorporate "graphic renditions" (blinking, bolding, reverse video, and underlining) as well as 80 or 132 column displays. The VT100 also introduced an additional character set containing various bits of graphics that allowed the drawing of on-screen forms. All setup of the VT100 was accomplished using interactive displays presented on the screen; the setup data was stored in non-volatile memory within the terminal.</p>
        <p>The control sequences used by the VT100 family are based on the ANSI X3.64 standard, also known as ECMA-48 and ISO/IEC 6429. These are sometimes referred to as ANSI escape codes. The VT100 was not the first terminal to be based on X3.64 The <strong>Heath Company</strong> had a microprocessor based video terminal, the <strong>Heathkit H-19</strong>, that implemented a subset of the standard proposed by ANSI in X3.64. In addition, the VT100 provided backwards compatibility for VT52 users, with support for the VT52 control sequences.</p>
        <p>In 1983, the VT100 was replaced by the more-powerful VT200 series terminals such as the <?php echo $this->stencil->addLink('VT220', 'VT'); ?>.</p>
        <p>The VT100 was the first of Digital's terminals to be based on an industry standard microprocessor, the <?php echo $this->stencil->addLink('Intel 8080', 'CPU'); ?>. Options could be added to the terminal to support an external printer, additional graphic renditions, and more memory. The later option, known as <strong>Advanced Video Option</strong> or AVO, allowed the terminal to support a full 24 lines of text in 132 column mode. The VT100 became a platform on which Digital constructed related products.</p>
        <p>The VT101 and VT102 were cost reduced, non-expandable follow on versions. The VT101 was essentially a base model VT100, while the VT102 came standard with the AVO and serial printer port options pre-installed. The VT105 contained a simple graphics subsystem known as waveform graphics which was mostly compatible with same system in the earlier VT55. This system allowed two mathematical functions to be drawn to the screen on top of the normal text display, allowing text and graphics to be mixed to produce charts and similar output. The VT125 added an implementation of the byte efficient <strong>Remote Graphic Instruction Set</strong>, <strong><?php echo $this->stencil->addLink('ReGIS', 'VT'); ?></strong>, which used custom ANSI codes to send the graphics commands to the terminal, rather than requiring the terminal to be set to a separate graphics mode like the VT105.</p>
        <p>The VT100 form factor left significant room in the case for expansion, and DEC used this to produce several all-in-one stand alone minicomputer systems. The VT103 included a cardcage and 4×4 (8-slot) Q-Bus backplane, sufficient to configure a small LSI-11 system within the case, and supported an optional dual TU58 DECtape II block addressable cartridge tape drive which behaves like a very slow disk drive. The VT180 (codenamed "<em>Robin</em>") added a single-board microcomputer using a <?php echo $this->stencil->addLink('Zilog Z80', 'CPU'); ?> to run <?php echo $this->stencil->addLink('CP/M', 'OS'); ?>. The VT278 <?php echo $this->stencil->addLink('DECmate', 'VT'); ?> added a PDP-8 processor, allowing the terminal to run Digital's <?php echo $this->stencil->addLink('WPS-8', 'ITS'); ?> word processing software.</p>
    </div>
</div>