<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('VT220'); ?>
        <p>The <strong>VT220</strong> was an <?php echo $this->stencil->addLink('ANSI standard', 'IT'); ?> computer terminal introduced by <strong>Digital Equipment Corporation (<?php echo $this->stencil->addLink('DEC', 'C'); ?>)</strong> in 1983. The <strong>VT240</strong> added monochrome <?php echo $this->stencil->addLink('ReGIS', 'IT'); ?> vector graphics support to the base model, while the <strong>VT241</strong> did the same in color. The 200 series replaced the successful <?php echo $this->stencil->addLink('VT100', 'VT'); ?> series, providing more functionality in a much smaller unit with a much smaller and lighter keyboard. Among its major upgrades was a number of international characters, as well as the ability to define new character sets.</p>
        <p>The VT200 series was extremely successful in the market. Released at $795, the VT220 offered features, packaging and price that no other serial terminal could touch. In 1986, DEC shipped 165,000 units, giving them a 42% market share, double that of the closest competitor, <?php echo $this->stencil->addLink('Wyse', 'C'); ?>. Competitors adapted by introducing similar models at lower price points, leading DEC to do the same by releasing the less expensive $545 <?php echo $this->stencil->addLink('VT300', 'VT'); ?> series in 1987. By that time, DEC had shipped over one million VT220s.</p>
        <p>The VT220 improved on the earlier VT100 series of terminals with a redesigned keyboard, much smaller physical packaging, and a much faster microprocessor. The VT220 was available with <?php echo $this->stencil->addLink('CRTs', 'IT'); ?> that used white, green, or amber phosphors.</p>
        <p>The VT100s, like the <?php echo $this->stencil->addLink('VT50s', 'VT'); ?> before them, had been packaged in relatively large cases that provided room for expansion systems. The VT200s abandoned this concept, and wrapped the much smaller 1980s era electronics tightly around the CRT. The result was a truncated pyramidal case with the apex at the back, only slightly larger than the CRT. This made it much easier to fit the terminal on a desk. An adjustable stand allowed the angle of the CRT to be adjusted up and down. Because it was lower than head height, the result was an especially ergonomic terminal.</p>
        <p>The <strong>LK201 keyboard</strong> supplied with the VT220 was one of the first full-length, low-profile keyboards available; it was developed at DEC's Roxbury, Massachusetts facility. It was much smaller and lighter than the VT100s version, and connected to the terminal using a lighter and more flexible coiled cable and a telephone jack connector.</p>
        <p>The VT200s were the last DEC terminals to provide a <strong>20mA current loop serial interface</strong>, an older standard originally developed for the telegraph system. A standard 25-pin D-connector was also provided for <?php echo $this->stencil->addLink('RS-232', 'IT'); ?>. Only one of the two ports could be in use at a given time. Later DEC terminals would replace both of these with their proprietary <strong>Modified Modular Jack (MMJ)</strong> connectors.</p>
        <p>The VT220 was designed to be compatible with the VT100, but added features to make it more suitable for an international market. This was accomplished by including a number of different character sets that could be selected among using a series of ANSI commands. The terminal shipped with a total of 288 characters in its ROM, each one formed from a 8 by 10 pixel <?php echo $this->stencil->addLink('glyph', 'IT'); ?> (the character grid was 10 by 10, DEC only used 8 by 10). The characters included the 96 printable ASCII characters, 67 Display Controls, 32 DEC Special Graphics, and an upside-down question mark, used to represent undefined characters.</p>
        <p>The VT200s included the ability to make minor changes to the character set using the <strong><?php echo $this->stencil->addLink('National Replacement Character Set', 'IT'); ?> (NRCS)</strong> concept. When operating on an <?php echo $this->stencil->addLink('8-bit clean', 'IT'); ?> link up to 256 character codes were available, which included a full set of European characters. But when operating on a typical 7-bit link, only 128 were available, and only 96 of these produced display output as the rest were control characters. This was not enough characters to handle all European languages. Most terminals solved this by shipping multiple complete character sets in ROM, but there was a cost in doing so.</p>
        <p>DEC's solution to this problem, NCRS, allowed individual characters glyphs in the base set of 96 7-bit characters to be swapped out. For instance, the British set replaced the US's hash character, # for the pound sign, £. The terminal included 14 such replacement sets. This eliminated the need to ship 14 versions of the terminal, or to include 14 different 7-bit character sets in <?php echo $this->stencil->addLink('ROM', 'IT'); ?>.</p>
        <p>Additionally, the VT200s allowed for another 96 characters in the <strong>Dynamically Redefined Character Set (DRCS)</strong>, which could be downloaded from the host computer. Data for the glyphs was sent by encoding a set of six vertical pixels into a single character code, and then sending many of these Sixels to the terminal, which decoded them into the character set memory. In later models, the same <?php echo $this->stencil->addLink('sixel', 'IT'); ?> concept would be used to send bitmapped graphics as well. Character graphics were a common example of these downloaded sets.</p>
    </div>
</div>