<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('VT320'); ?>
        <p>The <strong>VT320</strong> was an <?php echo $this->stencil->addLink('ANSI standard', 'IT'); ?> computer terminal introduced by <strong>Digital Equipment Corporation (<?php echo $this->stencil->addLink('DEC', 'C'); ?>)</strong> in 1987. The VT320 was the text-only version, while the <strong>VT330</strong> added monochrome <?php echo $this->stencil->addLink('ReGIS', 'IT'); ?>, <?php echo $this->stencil->addLink('Sixel', 'IT'); ?> and <?php echo $this->stencil->addLink('Tektronix 4010', 'ITH'); ?> graphics, and the <strong>VT340</strong> added colour. The VT320 was replaced by the <?php echo $this->stencil->addLink('VT420', 'VT'); ?> in 1990, but the VT340 remained in production until all of these models were replaced by the <?php echo $this->stencil->addLink('VT500', 'VT'); ?> series in 1994.</p>
        <p>The 300 series replaced the earlier <?php echo $this->stencil->addLink('VT200', 'VT'); ?> series, as a lower-cost system better able to compete with a number of VT220 clones that had entered the market. Foremost among these was the <?php echo $this->stencil->addLink('Wyse', 'C'); ?> <strong>WT-60</strong>, introduced in 1986 with a form factor and feature set similar to the VT220, but including 4010 graphics and selling for only $699, compared to $795 for the base model VT220 lacking graphics. The VT320 was introduced at $545, something of a surprise, forcing Wyse to lower their prices to $599.</p>
        <p>The VT300s introduced a number of new features compared to the VT200s. With the great increase in <?php echo $this->stencil->addLink('RAM', 'IT'); ?> available, the 300's added the ability to store several pages of data locally, as well as perform editing on that data entirely within the terminal. The user could scroll up and down among several pages, normally about three, perform edits, and then send all of the changes to the host in a single operation. This required compatible host-side software to work. That memory also meant all of the 300 series were able to store large numbers of sixel-based glyphs, allowing them to be used not only as a user-defined character set as in the earlier 200's, but also to produce full-screen bitmap graphics by storing a separate sixel for each location on the screen.</p>
        <p>Finally, all members of the line could support two sessions, either using two MMJ ports available on some models, or in the case of the VT330 and VT340, using a single serial connection using a system known as <strong>TD/SMP</strong> on the server and <strong>SSU</strong> on the terminals. The TD/SMP protocol was never published, and only worked with DEC's own terminal servers. Using either system, the terminal could display the two sessions "stacked" and switch between them, or by splitting the screen vertically to show them one above the other, or horizontally side-by-side. The serial ports could run up to 19,200 bps, up from 9,600 bps on the VT200s.</p>
        <p>Like the VT200's, the VT300's included a number of alternate character sets for various international uses and basic form graphics. The system shipped with five sets of 94 characters, as well as a single set with 96 graphics characters. The sets were ASCII, ISO Latin and three graphics character sets. Using sixels, any one of these sets could be replaced with user-generated characters. The system also included DEC's unique <?php echo $this->stencil->addLink('National Replacement Character Sets', 'IT'); ?> that allowed single characters in a set to be swapped out to match the layout of a keyboard. For instance, in the UK the # symbol could be swapped out for the £, eliminating the need for custom versions of the terminal for each country. It supported the full range of ANSI escape codes, although some sources state it did not decode standard color sequences even on the VT340.</p>
        <p>The screen itself was a 14 inch <?php echo $this->stencil->addLink('CRT', 'IT'); ?> mounted on a tilt and swivel stand. It offered a resolution of 800 by 500, and a number of different glyphs could be used to produce 25 lines or either 80 or 132 columns of text, the 25th line normally being used to display status codes, like caps lock, generated locally in the terminal. The VT330 had two bit-planes that produced 4 shades of grey, while the VT340 had four bit-planes to produce 16 colours out of a palette of 4096.</p>
        <p>As was the case with all DEC terminals, the VT300 series could emulate previous models. The 300's could be set to <?php echo $this->stencil->addLink('VT100', 'VT'); ?> or <?php echo $this->stencil->addLink('VT52', 'VT'); ?> mode.</p>
    </div>
</div>