<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('VT420'); ?>
        <p>The <strong>VT420</strong> was an <?php echo $this->stencil->addLink('ANSI standard', 'IT'); ?> computer terminal introduced in 1990 by <strong>Digital Equipment Corporation (<?php echo $this->stencil->addLink('DEC', 'C'); ?>)</strong>. The 420 was the only model in the 400 series, replacing the <?php echo $this->stencil->addLink('VT320', 'VT'); ?>. There were no colour or graphics capable 400 series terminals; the VT340 remained in production for those requiring <?php echo $this->stencil->addLink('ReGIS', 'IT'); ?> and <?php echo $this->stencil->addLink('Sixel', 'IT'); ?> graphics and colour support. The entire lineup of VT300s and VT420 was eventually replaced by the relatively unknown <?php echo $this->stencil->addLink('VT500', 'VT'); ?> series starting in 1993.</p>
        <p>The VT420 consisted largely of a combination of the VT320 with the virtual terminal support of the VT330 and VT340. Those two models had included a system known as <strong>TD/SMP</strong> which allowed two sessions to be multiplexed over a single serial connection to a compatible terminal server. Alternately the two sessions could be supported by separate serial connections on those models with multiple <strong>MMJ</strong> ports. Using either method, the VT330/340/420 could either show the two sessions behind each other, using a key sequence to flip back and forth, or split the screen horizontally to display the sessions one above the other, or vertically side-by-side.</p>
        <p>The VT420 also added a number of more minor features. One was to add a number of PC character sets, allowing the terminal to be used with a variety of PC programs. Another allowed the terminal to generate the proper character sequences to produce rectangular area commands. For instance, one could select a rectangular area and fill it with a particular character, or blank it out. This was in addition to the terminal side editing system introduced on the VT300s.</p>
        <p>The VT420 had a total of 5 sets of 94 characters for normal VT operation, another 3 sets of 128 PC characters, and 1 set of 96 characters containing various graphics and math symbols. Like all models since the <?php echo $this->stencil->addLink('VT200', 'VT'); ?> series, the user could also upload a custom character set of their own design using the Sixel system. Likewise, it also supported the <?php echo $this->stencil->addLink('National Replacement Character Set', 'It'); ?> system, which swapped out single characters in 7-bit modes to allow basic changes like swapping the # for the £ for use on UK systems.</p>
        <p>All DEC terminals that came after the <?php echo $this->stencil->addLink('VT100', 'VT'); ?>, including the VT420, are able to emulate their ancestors. The VT420 had VT100 and <?php echo $this->stencil->addLink('VT52', 'VT'); ?> emulating modes.</p>
        <p>The screen itself was a 14" flat <?php echo $this->stencil->addLink('CRT', 'IT'); ?> with a resolution of 800 (horizontal) by 400 (vertical) pixels. A variety of <?php echo $this->stencil->addLink('glyphs', 'IT'); ?> were available that provided 80 or 132 characters across, and 24, 36 or 48 lines of text vertically. The screen had room for 25 lines at normal font sizes, but the last line was normally used for status indications, like ⇪ Caps Lock. The MMJ ports could operate at speeds up to 38,400 bit/s, double that of the VT300s maximum 19,200 bit/s.</p>
    </div>
</div>