<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('VT52'); ?>
        <p>The <strong>VT50</strong> was a <?php echo $this->stencil->addLink('CRT', 'IT'); ?> based computer terminal introduced by <strong>Digital Equipment Corporation (<?php echo $this->stencil->addLink('DEC', 'C'); ?>)</strong> in July 1974. It provided a display with 12 rows and 80 columns of upper-case text, and used an expanded set of control characters and forward only scrolling based on the earlier VT05. DEC documentation of the era refers to the terminals as the <strong>DECscope</strong>, a name that was otherwise almost never seen.</p>
        <p>The VT50 was sold only for a short period before it was replaced by the <strong>VT52</strong> in September 1975. The VT52 provided a screen of 24 rows and 80 columns of text and supported all 95 <?php echo $this->stencil->addLink('ASCII', 'IT'); ?> characters as well as 32 graphics characters, bi-directional scrolling, and an expanded control character system. DEC produced a series of upgraded VT52's with additional hardware for various uses.</p>
        <p>The VT52 family was followed by the much more sophisticated <?php echo $this->stencil->addLink('VT100', 'VT'); ?> in 1978.</p>
        <p>The VT50 supported asynchronous communication at baud rates up to 9600 bits per second and did not require any fill characters. Like other early DEC terminals, the VT50 series were equipped with both an <?php echo $this->stencil->addLink('RS-232', 'ITH'); ?> port as well as a <strong>20mA current loop</strong>, an older serial standard used with teletype machines that was more suitable to long distance transmission over phone lines. Data was read into a small buffer, which the display hardware periodically read to produce the display.</p>
        <p>To interpret the commands being sent in the serial data, it used a primitive central processing unit (<?php echo $this->stencil->addLink('CPU', 'ITH'); ?>) built from small-scale-integration integrated circuits. It examined the data while the display hardware was inactive between raster scan lines, and then triggered the display hardware to take over at the appropriate time. The display system returned control to the CPU when it was complete. The CPU was so basic that addition and subtraction could only be done by repeatedly incrementing or decrementing two registers. Moreover, the time taken by such a loop had to be nearly constant, or text lower on the screen would be displayed in the wrong place during that refresh.</p>
        <p>Characters typed on the keyboard were likewise stored in a buffer and read back over the serial line as quickly as possible. One notable feature of the VT50 was the introduction of a separate function keypad with the "<?php echo $this->stencil->addLink('Gold Key', 'IT'); ?>", which was used for editing programs like <?php echo $this->stencil->addLink('WPS-8', 'ITS'); ?>, KED, and EDT. Pressing the Gold Key and then typing one of the keys on the keyboard sent a command sequence back to the host computer.</p>
        <p>DEC also offered an optional hard-copy device called an electrolytic copier, which fit into the blank panel on the right side of the display. This device was able to print, scan-line by scan-line, an exact replica of the screen onto a damp roll of special paper. It did this by electroplating metal from an electrode into the paper. The paper ran between two electrodes. The electrode on one side was a thin straight bar oriented across the paper width. The electrode on the other side was a thin helical bar wrapped around a rotating drum. One rotation of the drum scanned an intersecting area of the electrodes across the width of the paper. While the copier did an admirable job of capturing the contents of the screen, the output of the copier had an unfortunate resemblance to wet toilet tissue. Digital patented the innovation of having a single character generator provide the text font for both screen and copier.</p>
        <p>The basic layout of the terminal, with the screen and main keyboard on the left and the blank area on the right, was intended to allow the system to be upgraded. The printer was one such upgrade, but over time DEC offered a number of other options. The large size of the cabinet was deliberate, to avoid a cooling fan. The two circuit boards with processor and memory at the base of the terminal, and a single board with power-supply and monitor electronics at the rear, were cooled by convection. The large, flat top of the terminal frequently accommodated large volumes of DEC documentation, which could block the vents and cause overheating.</p>
    </div>
</div>