<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('IBM System/360'); ?>
        <p>The <strong>IBM System/360</strong> was a mainframe computer system family announced by <?php echo $this->stencil->addLink('IBM', 'C'); ?> on 7 April 1964, and delivered between 1965 and 1978. It was the first family of computers designed to cover the complete range of applications, from small to large, both commercial and scientific. The design made a clear distinction between architecture and implementation, allowing IBM to release a suite of compatible designs at different prices. All but the incompatible model 44 and the most expensive systems used microcode to implement the instruction set, which featured 8-bit byte addressing and binary, decimal and (hexadecimal) floating-point calculations.</p>
        <p>The slowest System/360 model announced in 1964, the Model 30, could perform up to 34,500 instructions per second, with memory from 8 to 64KB. High performance models came later. The 1967 System 360 Model 91 could do up to 16.6 million instructions per second. The larger 360 models could have up to 8MB of internal main memory, though main memory that big was unusual a more typical large installation might have as little as 256KB of main storage, but 512KB, 768KB or 1024KB was more common. Up to 8 megabytes of slower (8 microsecond) Large Capacity Storage (LCS) was also available.</p>
        <p></p>System/360 was extremely successful in the market, allowing customers to purchase a smaller system with the knowledge they would always be able to migrate upward if their needs grew, without reprogramming of application software or replacing peripheral devices. Many consider the design one of the most successful computers in history, influencing computer design for years to come.</p>
        <p>The chief architect of System/360 was <strong>Gene Amdahl</strong>, and the project was managed by <?php echo $this->stencil->addLink('Fred Brooks', 'P'); ?>, responsible to Chairman <strong>Thomas J. Watson Jr</strong>. The commercial release was piloted by another of Watson's lieutenants, John R. Opel, who managed the launch of IBM’s System 360 mainframe family in 1964.</p>
        <p>Application level compatibility (with some restrictions) for System/360 software is maintained to present day with the System z servers.</p>
    </div>
</div>