<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Miva Script'); ?>
        <p><strong>Miva Script</strong> is a proprietary computer scripting language mainly used for internet applications such as <?php echo $this->stencil->addLink('e-commerce', 'WD'); ?>.</p>
        <p>Today it is developed by <?php echo $this->stencil->addLink('Miva Inc', 'C'); ?>, based in San Diego, California. Although quite a number of web hosting companies support Miva Script on their servers, it is significantly less widespread than its popular competitor <?php echo $this->stencil->addLink('PHP', 'L'); ?>.</p>
        <p>The language was first developed under the name <strong>htmlscript</strong> by <strong>Joe Austin</strong> and others in 1995, and a company, htmlscript corporation, was formed the following year.</p>
        <p>Miva Script is currently owned and maintained by <strong>Miva Merchant</strong>. The origins of Miva Script began in 1993 when David Haldy and Joseph Austin built the first version of HTMLScript. The first version was written in the <?php echo $this->stencil->addLink('Perl', 'L'); ?> programming language, which was called <strong>LEHTML (Logic Enhanced HTML)</strong>. Joseph Austin wrote a wrapper for it in the <?php echo $this->stencil->addLink('C', 'L'); ?> programming language that let it start off as a root process and then downgrade itself immediately to the ownership and permissions of the owner of the script file. This wrapper made it suitable for use with his hosting service which was called Volant Turnpike at the time. Joseph Austin eventually sold Volant Turnpike to Dave Haldy. Perl allowed self-executing code, so LEHTML did not have its own expression analyzer and just parsed the expression into Perl syntax and then passed it into Perl. Volant Turnpike users liked using LEHTML, so Joseph Austin and Ron Ahern wrote an expression analyser and re-implemented the LEHTML syntax in the C programming language. Joseph Austin called the end result HTMLScript and registered the name with the USPTO. Joseph Austin, Troy McCasland and Derek Finley were the founders of the company called HTMLScript Corporation.</p>
        <p>HTMLScript did not have the concept of a "WHILE" or "FOR" loop because of the low server processing power at the time. It would be enough to bring the whole server down if even one program ran away. So, Joseph Austin did not implement a loop in order to make it impossible for an HTMLScript server process to run away. Additionally, he implemented the "macro" in the first version of HTMLScript so that it would allow self-executing code. The macro was powerful, but it eventually had some security issues.</p>
        <p>In 1997, Jon Burchmore extensively rewrote the language to make it more syntactically consistent, although the new engine supported both old htmlscript and new (named mivascript) syntaxes. Jon Burchmore re-wrote HTMLScript with syntax that Joe developed with the help of SoftQuad, using the emerging <?php echo $this->stencil->addLink('XML', 'WD'); ?> standard. Jon Burchmore wrote the replacement for KoolKat which then became Miva Merchant. The new end-product supported both the old HTMLScript syntax and new (named Miva Script) syntaxes.</p>
        <p>On 14 October 1997, HTMLScript’s name was changed to Miva Script and the company name was changed to Miva. Shortly thereafter, Miva Merchant followed suit for the name of the product. The name “Miva” comes from the Egyptian hieroglyphics for the word "cat". The word for "cat" is a combination of two symbols: milk basin followed by a quail. The milk basin is pronounced "Mee" and the quail is pronounced "Waa" which combined is how you say cat. Joseph Austin thought this was clever, as they had called KoolKat "an electronic (cat)alog." Joseph showed it to his German friend who could not pronounce the "Waa" sound and instead kept on pronouncing it as "Va". Joseph Austin registered the domain Miva.com and filed the trademark.</p>
        <p></p>In 1998, the company was renamed Miva Corporation. In 1998, the first version of Miva Merchant came out. In 2002, the Miva Script compiler was delivered, and the HTMLScript syntax and macros were dropped from the engine. Miva Corporation was sold in 2003 to a mid-cap, public company called FindWhat. Subsequently, FindWhat bought the name Miva.</p>
        <p></p>In 2007, Russell Carroll and a group of investors bought the original Miva technologies and customer base from Miva and started Miva Merchant, Inc.</p>
    </div>
</div>

<?php if (!$this->stencil->getIsSub()): ?>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <h2>Implementations</h2>
            <h3>Miva Merchant Empresa</h3>
            <p>Empresa is the underlying engine for Miva Script. In versions numbered less than 4.0, Miva Merchant Empresa is a script interpreter available for web servers running *nix and Microsoft Windows operating systems. The most recent interpreter version is 3.9705. Interpreted Miva Script is still widely supported by many web hosts. Versions numbered 3.9x are a transitional form of the language, implementing some (but not all) of the new features found in version 4, such as arrays.</p>
            <p></p>Since 4.0, Miva Merchant Empresa is a Virtual Machine for running compiled MIVA Script, again available in versions for *nix and Microsoft Windows.</p>
            <p>The current version level 5.x added new language constructs, native SQL support, a new access-methodology for dbase3 tables, called MIVA-SQL, as well as a new templating syntax that the Empresa virtual machine can compile on the fly. Version 5.08 and later support the GD Graphics Library.</p>

            <h3>Miva Merchant Mia</h3>
            <p>Miva Merchant Mia is a version of the Empresa engine designed to run on a Windows PC as a localhost server watching a specified port. (usually 8000 or 8080). No other server software is required unless the POP and SMTP functions are required. This provides a portable, stand-alone development environment.</p>
            <p>Miva Merchant Mia is updated with each Miva Merchant Empresa release. Like Empressa, versions prior to 4 are interpreters while 4.0+ only work with compiled script. There are a few minor differences between.</p>

            <h3>Miva Merchant Script Compiler</h3>
            <p>Miva Merchant Script Compiler was introduced in mid-2002, claiming to offer better performance and the closure of application source code. Comparability required some changes to the language, with support for the old htmlscript syntax and macros evaluated at runtime (often considered a security risk) dropped. The compiler produces a platform-independent bytecode which runs on the Miva Merchant Empresa and Miva Merchant Mia Virtual Machines (There are minor variations between Empresa and Mia virtual machines).</p>
            <p>In May 2005, MIVA Corporation made the Script Compiler available free. In 2011 the built in licensing code was removed simplifying installation.</p>
            <p>In August 2007, Miva Merchant was separated from its parent company as a result of a management buy-out.</p>
            <p>February 2011 introduced the new MivaScript.com website fully documenting the latest version of the language, including the GD Graphics Library.</p>
        </div>
    </div>
<?php endif; ?>