<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Swift Programming Language'); ?>
        <p><strong>Swift</strong> is a multi-paradigm, compiled programming language created by <?php echo $this->stencil->addLink('Apple Inc', 'C'); ?> for <?php echo $this->stencil->addLink('iOS', 'OS'); ?> and <?php echo $this->stencil->addLink('OS X', 'OS'); ?> development.</p>
        <p>Swift is designed to work with Apple's <?php echo $this->stencil->addLink('Cocoa', 'MD'); ?> and <?php echo $this->stencil->addLink('Cocoa Touch', 'MD'); ?> frameworks and the large body of existing <?php echo $this->stencil->addLink('Objective-C', 'LC'); ?> (Obj-C) code written for Apple products. Swift is intended to be more resilient to erroneous code ("safer") than Objective-C, and also more concise. It is built with the LLVM compiler framework included in <?php echo $this->stencil->addLink('Xcode', 'SWI'); ?> 6, and uses the Objective-C runtime, allowing C, Objective-C, C++ and Swift code to run within a single program.</p>
        <p>Swift supports the core concepts that made Obj-C flexible, notably dynamic dispatch, widespread late binding, extensible programming and similar features. These features also have well known performance and safety trade-offs, which Swift was designed to address. For safety, Swift introduced a system that helps address common programming errors like null pointers, as well as introducing syntactic sugar to avoid the pyramid of doom that can result. For performance issues, Apple has invested considerable effort in aggressive optimisation that can flatten out method calls and accessors to eliminate this overhead. More fundamentally, Swift has added the concept of protocol extensibility, an extensibility system that can be applied to types, structs and classes, Apple promotes this as a real change in programming paradigms they refer to as protocol-oriented programming.</p>
        <p>Swift was introduced at Apple's 2014 Worldwide Developers Conference (WWDC), It underwent a upgrade to version 1.2 during 2014, and a more major upgrade to Swift 2 at WWDC 2015. Initially a proprietary language, it was announced that Swift 2 would become open source later that year, supporting <?php echo $this->stencil->addLink('iOS', 'OS'); ?>, <?php echo $this->stencil->addLink('OS X', 'OS'); ?> and <?php echo $this->stencil->addLink('Linux', 'OS'); ?>.</p>
    </div>
</div>
