<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('TypeScript'); ?>
        <p><strong>TypeScript</strong> is a free and open source programming language developed and maintained by <?php echo $this->stencil->addLink('Microsoft', 'C'); ?>. It is a strict superset of <?php echo $this->stencil->addLink('JavaScript', 'L'); ?>, and adds optional static typing and class-based object-oriented programming to the language. <strong>Anders Hejlsberg</strong>, lead architect of <?php echo $this->stencil->addLink('C#', 'LC'); ?> and creator of <?php echo $this->stencil->addLink('Delphi', 'L'); ?> and <?php echo $this->stencil->addLink('Turdo Pascal', 'L'); ?>, has worked on the development of TypeScript. TypeScript may be used to develop JavaScript applications for client-side or server-side (<?php echo $this->stencil->addLink('Node.js', 'JS'); ?>) execution.</p>
        <p>TypeScript is designed for development of large applications and transcompiles to JavaScript. As TypeScript is a superset of JavaScript, any existing JavaScript programs are also valid TypeScript programs.</p>
        <p>TypeScript supports header files which can contain type information of existing JavaScript libraries, enabling other programs to use objects defined in the header files as if they were strongly typed TypeScript objects. There are third-party header files for popular libraries like <?php echo $this->stencil->addLink('jQuery', 'JS'); ?>, <?php echo $this->stencil->addLink('MongoDB', 'DB'); ?>, <?php echo $this->stencil->addLink('D3.js', 'JS'); ?>. TypeScript headers for the Node.js basic modules are also available, allowing development of Node.js programs within TypeScript.</p>
        <p>The TypeScript compiler is itself written in JavaScript, and licensed under the <?php echo $this->stencil->addLink('Apache 2 license', 'LIC'); ?>.</p>
        <p>TypeScript is included as a first-class programming language in <?php echo $this->stencil->addLink('Microsoft Visual Studio', 'ITS'); ?> 2013 Update 2 and later, beside C# and other Microsoft languages. An official extension allows Visual Studio 2012 to support TypeScript as well.</p>
    </div>
</div>
