<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('ASCII Table'); ?>
        <p>The <strong>American Standard Code for Information Interchange</strong> (<strong>ASCII</strong>) is a character-encoding scheme originally based on the English alphabet that encodes 128 specified characters - the numbers 0-9, the letters a-z and A-Z, some basic punctuation symbols, some control codes that originated with Teletype machines, and a blank space - into the 7-bit binary integers.</p>
        <table class="table table-bordered table-hover table-striped">
            <tr>
                <th>Dec</th><th>Oct</th><th>Hex</th><th>char</th>
                <td rowspan="33"></td>
                <th>Dec</th><th>Oct</th><th>Hex</th><th>Char</th>
                <td rowspan="33"></td>
                <th>Dec</th><th>Oct</th><th>Hex</th><th>Char</th>
                <td rowspan="33"></td>
                <th>Dec</th><th>Oct</th><th>Hex</th><th>Char</th>
            </tr>
            <tr>
                <td>0</td>
                <td>0</td>
                <td>00</td>
                <td><strong>NUL</strong> (null)</td>
                <td>32</td>
                <td>40</td>
                <td>20</td>
                <td> (space)</td>
                <td>64</td>
                <td>100</td>
                <td>40</td>
                <td><strong>@</strong></td>
                <td>96</td>
                <td>140</td>
                <td>60</td>
                <td><strong>`</strong></td>
            </tr>
            <tr>
                <td>1</td>
                <td>1</td>
                <td>01</td>
                <td><strong>SOH</strong> (start of header)</td>
                <td>33</td>
                <td>41</td>
                <td>21</td>
                <td><strong>!</strong></td>
                <td>65</td>
                <td>101</td>
                <td>41</td>
                <td><strong>A</strong></td>
                <td> 97</td>
                <td>141</td>
                <td>61</td>
                <td><strong>a</strong>
            </tr>
            <tr>
                <td>2</td>
                <td>2</td>
                <td>02</td>
                <td><strong>STX</strong> (start of text)</td>
                <td>34</td>
                <td>42</td>
                <td>22</td>
                <td><strong>"</strong></td>
                <td>66</td>
                <td>102</td>
                <td>42</td>
                <td><strong>B</strong></td>
                <td> 98</td>
                <td>142</td>
                <td>62</td>
                <td><strong>b</strong>
            </tr>
            <tr>
                <td>3</td>
                <td>3</td>
                <td>03</td>
                <td><strong>ETX</strong> (end of text)</td>
                <td>35</td>
                <td>43</td>
                <td>23</td>
                <td><strong>#</strong></td>
                <td>67</td>
                <td>103</td>
                <td>43</td>
                <td><strong>C</strong></td>
                <td> 99</td>
                <td>143</td>
                <td>63</td>
                <td><strong>c</strong>
            </tr>
            <tr>
                <td>4</td>
                <td>4</td>
                <td>04</td>
                <td><strong>EOT</strong> (end of transmission)</td>
                <td>36</td>
                <td>44</td>
                <td>24</td>
                <td><strong>$</strong></td>
                <td>68</td>
                <td>104</td>
                <td>44</td>
                <td><strong>D</strong></td>
                <td>100</td>
                <td>144</td>
                <td>64</td>
                <td><strong>d</strong>
            </tr>
            <tr>
                <td>5</td>
                <td>5</td>
                <td>05</td>
                <td><strong>ENQ</strong> (enquiry)</td>
                <td>37</td>
                <td>45</td>
                <td>25</td>
                <td><strong>%</strong></td>
                <td>69</td>
                <td>105</td>
                <td>45</td>
                <td><strong>E</strong></td>
                <td>101</td>
                <td>145</td>
                <td>65</td>
                <td><strong>e</strong>
            </tr>
            <tr>
                <td>6</td>
                <td>6</td>
                <td>06</td>
                <td><strong>ACK</strong> (acknowledge)</td>
                <td>38</td>
                <td>46</td>
                <td>26</td>
                <td><strong>&amp;</strong></td>
                <td>70</td>
                <td>106</td>
                <td>46</td>
                <td><strong>F</strong></td>
                <td>102</td>
                <td>146</td>
                <td>66</td>
                <td><strong>f</strong>
            </tr>
            <tr>
                <td>7</td>
                <td>7</td>
                <td>07</td>
                <td><strong>BEL</strong> (bell)</td>
                <td>39</td>
                <td>47</td>
                <td>27</td>
                <td><strong>'</strong></td>
                <td>71</td>
                <td>107</td>
                <td>47</td>
                <td><strong>G</strong></td>
                <td>103</td>
                <td>147</td>
                <td>67</td>
                <td><strong>g</strong>
            </tr>
            <tr>
                <td>8</td>
                <td>10</td>
                <td>08</td>
                <td><strong>BS</strong> (backspace)</td>
                <td>40</td>
                <td>50</td>
                <td>28</td>
                <td><strong>(</strong></td>
                <td>72</td>
                <td>110</td>
                <td>48</td>
                <td><strong>H</strong></td>
                <td>104</td>
                <td>150</td>
                <td>68</td>
                <td><strong>h</strong>
            </tr>
            <tr>
                <td>9</td>
                <td>11</td>
                <td>09</td>
                <td><strong>HT</strong> (horizontal tab)</td>
                <td>41</td>
                <td>51</td>
                <td>29</td>
                <td><strong>)</strong></td>
                <td>73</td>
                <td>111</td>
                <td>49</td>
                <td><strong>I</strong></td>
                <td>105</td>
                <td>151</td>
                <td>69</td>
                <td><strong>i</strong>
            </tr>
            <tr>
                <td>10</td>
                <td>12</td>
                <td>0a</td>
                <td><strong>LF</strong> (line feed - new line)</td>
                <td>42</td>
                <td>52</td>
                <td>2a</td>
                <td><strong>*</strong></td>
                <td>74</td>
                <td>112</td>
                <td>4a</td>
                <td><strong>J</strong></td>
                <td>106</td>
                <td>152</td>
                <td>6a</td>
                <td><strong>j</strong>
             </tr>
            <tr>
                <td>11</td>
                <td>13</td>
                <td>0b</td>
                <td><strong>VT</strong> (vertical tab)</td>
                <td>43</td>
                <td>53</td>
                <td>2b</td>
                <td><strong>+</strong></td>
                <td>75</td>
                <td>113</td>
                <td>4b</td>
                <td><strong>K</strong></td>
                <td>107</td>
                <td>153</td>
                <td>6b</td>
                <td><strong>k</strong>
            </tr>
            <tr>
                <td>12</td>
                <td>14</td>
                <td>0c</td>
                <td><strong>FF</strong> (form feed - new page)</td>
                <td>44</td>
                <td>54</td>
                <td>2c</td>
                <td><strong>,</strong></td>
                <td>76</td>
                <td>114</td>
                <td>4c</td>
                <td><strong>L</strong></td>
                <td>108</td>
                <td>154</td>
                <td>6c</td>
                <td><strong>l</strong>
            </tr>
            <tr>
                <td>13</td>
                <td>15</td>
                <td>0d</td>
                <td><strong>CR</strong> (carriage return)</td>
                <td>45</td>
                <td>55</td>
                <td>2d</td>
                <td><strong>-</strong></td>
                <td>77</td>
                <td>115</td>
                <td>4d</td>
                <td><strong>M</strong></td>
                <td>109</td>
                <td>155</td>
                <td>6d</td>
                <td><strong>m</strong>
            </tr>
            <tr>
                <td>14</td>
                <td>16</td>
                <td>0e</td>
                <td><strong>SO</strong> (shift out)</td>
                <td>46</td>
                <td>56</td>
                <td>2e</td>
                <td><strong>.</strong></td>
                <td>78</td>
                <td>116</td>
                <td>4e</td>
                <td><strong>N</strong></td>
                <td>110</td>
                <td>156</td>
                <td>6e</td>
                <td><strong>n</strong>
            </tr>
            <tr>
                <td>15</td>
                <td>17</td>
                <td>0f</td>
                <td><strong>SI</strong> (shift in)</td>
                <td>47</td>
                <td>57</td>
                <td>2f</td>
                <td><strong>/</strong></td>
                <td>79</td>
                <td>117</td>
                <td>4f</td>
                <td><strong>O</strong></td>
                <td>111</td>
                <td>157</td>
                <td>6f</td>
                <td><strong>o</strong>
            </tr>
            <tr>
                <td>16</td>
                <td>20</td>
                <td>10</td>
                <td><strong>DLE</strong> (data link escape)</td>
                <td>48</td>
                <td>60</td>
                <td>30</td>
                <td><strong>0</strong></td>
                <td>80</td>
                <td>120</td>
                <td>50</td>
                <td><strong>P</strong></td>
                <td>112</td>
                <td>160</td>
                <td>70</td>
                <td><strong>p</strong>
            </tr>
            <tr>
                <td>17</td>
                <td>21</td>
                <td>11</td>
                <td><strong>DC1</strong> (device control 1)</td>
                <td>49</td>
                <td>61</td>
                <td>31</td>
                <td><strong>1</strong></td>
                <td>81</td>
                <td>121</td>
                <td>51</td>
                <td><strong>Q</strong></td>
                <td>113</td>
                <td>161</td>
                <td>71</td>
                <td><strong>q</strong>
            </tr>
            <tr>
                <td>18</td>
                <td>22</td>
                <td>12</td>
                <td><strong>DC2</strong> (device control 2)</td>
                <td>50</td>
                <td>62</td>
                <td>32</td>
                <td><strong>2</strong></td>
                <td>82</td>
                <td>122</td>
                <td>52</td>
                <td><strong>R</strong></td>
                <td>114</td>
                <td>162</td>
                <td>72</td>
                <td><strong>r</strong>
            </tr>
            <tr>
                <td>19</td>
                <td>23</td>
                <td>13</td>
                <td><strong>DC3</strong> (device control 3)</td>
                <td>51</td>
                <td>63</td>
                <td>33</td>
                <td><strong>3</strong></td>
                <td>83</td>
                <td>123</td>
                <td>53</td>
                <td><strong>S</strong></td>
                <td>115</td>
                <td>163</td>
                <td>73</td>
                <td><strong>s</strong>
            </tr>
            <tr>
                <td>20</td>
                <td>24</td>
                <td>14</td>
                <td><strong>DC4</strong> (device control 4)</td>
                <td>52</td>
                <td>64</td>
                <td>34</td>
                <td><strong>4</strong></td>
                <td>84</td>
                <td>124</td>
                <td>54</td>
                <td><strong>T</strong></td>
                <td>116</td>
                <td>164</td>
                <td>74</td>
                <td><strong>t</strong>
            </tr>
            <tr>
                <td>21</td>
                <td>25</td>
                <td>15</td>
                <td><strong>NAK</strong> (negative acknowledge)</td>
                <td>53</td>
                <td>65</td>
                <td>35</td>
                <td><strong>5</strong></td>
                <td>85</td>
                <td>125</td>
                <td>55</td>
                <td><strong>U</strong></td>
                <td>117</td>
                <td>165</td>
                <td>75</td>
                <td><strong>u</strong>
            </tr>
            <tr>
                <td>22</td>
                <td>26</td>
                <td>16</td>
                <td><strong>SYN</strong> (synchronous idle)</td>
                <td>54</td>
                <td>66</td>
                <td>36</td>
                <td><strong>6</strong></td>
                <td>86</td>
                <td>126</td>
                <td>56</td>
                <td><strong>V</strong></td>
                <td>118</td>
                <td>166</td>
                <td>76</td>
                <td><strong>v</strong>
            </tr>
            <tr>
                <td>23</td>
                <td>27</td>
                <td>17</td>
                <td><strong>ETB</strong> (end of transmission block)</td>
                <td>55</td>
                <td>67</td>
                <td>37</td>
                <td><strong>7</strong></td>
                <td>87</td>
                <td>127</td>
                <td>57</td>
                <td><strong>W</strong></td>
                <td>119</td>
                <td>167</td>
                <td>77</td>
                <td><strong>w</strong>
            </tr>
            <tr>
                <td>24</td>
                <td>30</td>
                <td>18</td>
                <td><strong>CAN</strong> (cancel)</td>
                <td>56</td>
                <td>70</td>
                <td>38</td>
                <td><strong>8</strong></td>
                <td>88</td>
                <td>130</td>
                <td>58</td>
                <td><strong>X</strong></td>
                <td>120</td>
                <td>170</td>
                <td>78</td>
                <td><strong>x</strong>
            </tr>
            <tr>
                <td>25</td>
                <td>31</td>
                <td>19</td>
                <td><strong>EM</strong> (end of medium)</td>
                <td>57</td>
                <td>71</td>
                <td>39</td>
                <td><strong>9</strong></td>
                <td>89</td>
                <td>131</td>
                <td>59</td>
                <td><strong>Y</strong></td>
                <td>121</td>
                <td>171</td>
                <td>79</td>
                <td><strong>y</strong>
            </tr>
            <tr>
                <td>26</td>
                <td>32</td>
                <td>1a</td>
                <td><strong>SUB</strong> (substitute)</td>
                <td>58</td>
                <td>72</td>
                <td>3a</td>
                <td><strong>:</strong></td>
                <td>90</td>
                <td>132</td>
                <td>5a</td>
                <td><strong>Z</strong></td>
                <td>122</td>
                <td>172</td>
                <td>7a</td>
                <td><strong>z</strong>
            </tr>
            <tr>
                <td>27</td>
                <td>33</td>
                <td>1b</td>
                <td><strong>ESC</strong> (escape)</td>
                <td>59</td>
                <td>73</td>
                <td>3b</td>
                <td><strong>;</strong></td>
                <td>91</td>
                <td>133</td>
                <td>5b</td>
                <td><strong>[</strong></td>
                <td>123</td>
                <td>173</td>
                <td>7b</td>
                <td><strong>{</strong>
            </tr>
            <tr>
                <td>28</td>
                <td>34</td>
                <td>1c</td>
                <td><strong>FS</strong> (file separator)</td>
                <td>60</td>
                <td>74</td>
                <td>3c</td>
                <td><strong>&lt;</strong></td>
                <td>92</td>
                <td>134</td>
                <td>5c</td>
                <td><strong>\</strong></td>
                <td>124</td>
                <td>174</td>
                <td>7c</td>
                <td><strong>&#124;</strong>
            </tr>
            <tr>
                <td>29</td>
                <td>35</td>
                <td>1d</td>
                <td><strong>GS</strong> (group separator)</td>
                <td>61</td>
                <td>75</td>
                <td>3d</td>
                <td><strong>=</strong></td>
                <td>93</td>
                <td>135</td>
                <td>5d</td>
                <td><strong>]</strong></td>
                <td>125</td>
                <td>175</td>
                <td>7d</td>
                <td><strong>}</strong>
            </tr>
            <tr>
                <td>30</td>
                <td>36</td>
                <td>1e</td>
                <td><strong>RS</strong> (record separator)</td>
                <td>62</td>
                <td>76</td>
                <td>3e</td>
                <td><strong>&gt;</strong></td>
                <td>94</td>
                <td>136</td>
                <td>5e</td>
                <td><strong>^</strong></td>
                <td>126</td>
                <td>176</td>
                <td>7e</td>
                <td><strong>~</strong>
            </tr>
            <tr>
                <td>31</td>
                <td>37</td>
                <td>1f</td>
                <td><strong>US</strong> (unit separator)</td>
                <td>63</td>
                <td>77</td>
                <td>3f</td>
                <td><strong>?</strong></td>
                <td>95</td>
                <td>137</td>
                <td>5f</td>
                <td><strong>_</strong></td>
                <td>127</td>
                <td>177</td>
                <td>7f</td>
                <td><strong>DEL</strong> (delete)</td>
            </tr>
        </table>
    </div>
</div>