<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('GNOME'); ?>
        <p><strong>GNOME</strong> is a desktop environment which is composed entirely of free and open-source software. Its target operating system is <?php echo $this->stencil->addLink('Linux', 'OS'); ?>, but it is also supported on most derivatives of <?php echo $this->stencil->addLink('BSD', 'OS'); ?>.</p>
        <p>GNOME is developed by <strong>The GNOME Project</strong>, which is composed of both volunteers and paid contributors, the largest corporate contributor being <?php echo $this->stencil->addLink('Red Hat', 'C'); ?>. It is an international project that aims to develop software frameworks for the development of software, to program end-user applications based on these frameworks, and to coordinate efforts for internationalisation and localisation and accessibility of that software.</p>

        <h2>GNOME 2</h2>
        <p>GNOME 2 was very similar to a conventional desktop interface, featuring a simple desktop in which users could interact with virtual objects, such as windows, icons, and files. GNOME 2 used <strong>Metacity</strong> as its default window manager. The handling of windows, applications, and files in GNOME 2 is similar to that of contemporary desktop operating systems. In the default configuration of GNOME 2, the desktop has a launcher menu for quick access to installed programs and file locations; open windows may be accessed by a taskbar along the bottom of the screen, and the top-right corner features a notification area for programs to display notices while running in the background. However, these features can be moved to almost any position or orientation the user desires, replaced with other functions or removed altogether.</p>

        <h2>GNOME 3</h2>
        <p>Before GNOME 3, GNOME used the traditional desktop metaphor, but in GNOME 3 this was replaced with GNOME Shell, a more abstract metaphor where switching between different tasks and virtual workspaces takes place in a separate area called Overview. Also, since Mutter replaced Metacity as the default window manager, the minimize and maximize buttons no longer appear on the titlebar by default. Adwaita replaced Clearlooks as the default theme. Many GNOME Core Applications also went through redesigns to provide a more consistent user experience.</p>
        <p>These major changes initially evoked widespread criticism. The <strong>MATE</strong> desktop environment forked from the GNOME 2 codebase with the intent of retaining the traditional GNOME 2 interface while keeping it compatible with modern Linux technology, such as <?php echo $this->stencil->addLink('GTK+', 'IT'); ?> 3. The Linux Mint team addressed the issue in another way by developing the "Mint GNOME Shell Extensions," extensions that ran on top of GNOME 3. These extensions allowed GNOME 3 to be used via the traditional desktop metaphor. This eventually led to the creation of the Cinnamon user interface, which was forked from the GNOME 3 codebase.</p>
        <p>As of 2015, critical reception is much more positive. <?php echo $this->stencil->addLink('Debian', 'OS'); ?>, a Linux distribution that had historically used GNOME 2, switched to <?php echo $this->stencil->addLink('XFCE', 'it/desktop-enviroments'); ?> when GNOME 3 was released. However, Debian developers are planning to switch back to GNOME 3 with their next release. <?php echo $this->stencil->addLink('Linus Torvalds', 'P'); ?>, the creator of the Linux kernel, switched back to GNOME 3 in 2013.</p>
    </div>
</div>