<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('TCP - Transmission Control Protocol'); ?>
        <p>The <strong>Transmission Control Protocol</strong> (<strong>TCP</strong>) is one of the core protocols of the <?php echo $this->stencil->addLink('Internet Protocol Suite', '/it/networks/'); ?>, and is so common that the entire suite is often called <?php echo $this->stencil->addLink('TCP/IP', '/it/networks/internet-protocol-suite'); ?>.</p>
        <p>TCP provides reliable, ordered and error-checked delivery of a stream of octets between programs running on computers connected to a local area network, <?php echo $this->stencil->addLink('intranet', '/it/networks'); ?> or the <?php echo $this->stencil->addLink('Internet', '/it/networks'); ?>.</p>
        <p>It resides at the <?php echo $this->stencil->addLink('Transport Layer', '/it/networks/internet-protocol-suite'); ?>.</p>
        <p><?php echo $this->stencil->addLink('Web browsers', 'WD'); ?> use TCP when they connect to servers on the <?php echo $this->stencil->addLink('World Wide Web', 'WD'); ?>, and it is used to deliver <?php echo $this->stencil->addLink('email', 'WD'); ?> and transfer files from one location to another.</p>
        <p><?php echo $this->stencil->addLink('HTTP', '/it/networks/internet-protocol-suite/application'); ?>, <?php echo $this->stencil->addLink('HTTPS', '/it/networks/internet-protocol-suite/application'); ?>, <?php echo $this->stencil->addLink('SMTP', '/it/networks/internet-protocol-suite/application'); ?>, <?php echo $this->stencil->addLink('POP3', '/it/networks/internet-protocol-suite/application'); ?>, <?php echo $this->stencil->addLink('IMAP', '/it/networks/internet-protocol-suite/application'); ?>, <?php echo $this->stencil->addLink('SSH', '/it/networks/internet-protocol-suite/application'); ?>, <?php echo $this->stencil->addLink('FTP', '/it/networks/internet-protocol-suite/application'); ?>, <?php echo $this->stencil->addLink('Telnet', '/it/networks/internet-protocol-suite/application'); ?> and a variety of other protocols are typically encapsulated in TCP.</p>
        <p>Applications that do not require the reliability of a TCP connection may instead use the connectionless User Datagram Protocol (<?php echo $this->stencil->addLink('UDP', '/it/networks/internet-protocol-suite/application'); ?>), which emphasizes low-overhead operation and reduced latency rather than error checking and delivery validation.</p>
    </div>
</div>