<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('TCP - Transmission Control Protocol'); ?>
        <p>The <strong>Transmission Control Protocol</strong> (<strong>TCP</strong>) is one of the core protocols of the <?php echo $this->stencil->addLink('Internet Protocol Suite', 'ITN'); ?>, and is so common that the entire suite is often called <?php echo $this->stencil->addLink('TCP/IP', 'ITN'); ?>.</p>
        <p>TCP provides reliable, ordered and error-checked delivery of a stream of <?php echo $this->stencil->addLink('octets', 'IT'); ?> between programs running on computers connected to a local area network, <?php echo $this->stencil->addLink('intranet', 'ITN'); ?> or the <?php echo $this->stencil->addLink('Internet', 'ITN'); ?>.</p>
        <p>It resides at the <?php echo $this->stencil->addLink('Transport Layer', 'IPS'); ?>.</p>
        <p><?php echo $this->stencil->addLink('Web browsers', 'WD'); ?> use TCP when they connect to servers on the <?php echo $this->stencil->addLink('World Wide Web', 'WD'); ?>, and it is used to deliver <?php echo $this->stencil->addLink('email', 'WD'); ?> and transfer files from one location to another.</p>
        <p><?php echo $this->stencil->addLink('HTTP', 'IPA'); ?>, <?php echo $this->stencil->addLink('HTTPS', 'IPA'); ?>, <?php echo $this->stencil->addLink('SMTP', 'IPA'); ?>, <?php echo $this->stencil->addLink('POP3', 'IPA'); ?>, <?php echo $this->stencil->addLink('IMAP', 'IPA'); ?>, <?php echo $this->stencil->addLink('SSH', 'IPA'); ?>, <?php echo $this->stencil->addLink('FTP', 'IPA'); ?>, <?php echo $this->stencil->addLink('Telnet', 'IPA'); ?> and a variety of other protocols are typically encapsulated in TCP.</p>
        <p>Applications that do not require the reliability of a TCP connection may instead use the connectionless User Datagram Protocol (<?php echo $this->stencil->addLink('UDP', 'IPA'); ?>), which emphasizes low-overhead operation and reduced latency rather than error checking and delivery validation.</p>
    </div>
</div>