<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('YUI - Yahoo! User Interface Library'); ?>
        <p>The <strong>Yahoo! User Interface Library (YUI)</strong> is a discontinued open-source <?php echo $this->stencil->addLink('JavaScript', 'L'); ?> library for building richly interactive web applications using techniques such as <?php echo $this->stencil->addLink('AJAX', 'WD'); ?>, <?php echo $this->stencil->addLink('DHTML', 'WD'); ?>, and DOM scripting. YUI includes several core <?php echo $this->stencil->addLink('CSS', 'WD'); ?> resources. It is available under a BSD License. Development on YUI began in 2005 and <?php echo $this->stencil->addLink('Yahoo!', 'C'); ?> properties such as My Yahoo! and the Yahoo! front page began using YUI in the summer of that year. YUI was released for public use in February 2006. It was actively developed by a core team of Yahoo! engineers.</p>
        <p>In September 2009, Yahoo! released YUI 3, a new version of YUI rebuilt from the ground up to modernize the library and incorporate lessons learned from YUI 2. Among the enhancements are a CSS selector driven engine, like <?php echo $this->stencil->addLink('jQuery', 'JS'); ?>, for retrieving DOM elements, a greater emphasis on granularity of modules, a smaller seed file that loads other modules when necessary, and a variety of syntactic changes intended to make writing code faster and easier.</p>
        <p>The YUI Library project at Yahoo! was founded by <strong>Thomas Sha</strong> and sponsored internally by Yahoo! co-founder <strong>Jerry Yang</strong>; its principal architects have been Sha, Adam Moore, and Matt Sweeney. The library's developers maintain the YUIBlog; the YUI community discusses the library and implementations in its community forum.</p>
        <p>On 29 August 2014, it was announced that active development of YUI by Yahoo! would end, citing the evolution of the JavaScript standards, steadily decreasing interest in large JavaScript libraries by developers, and the proliferation of server-side solutions. Future development will be limited to maintenance releases addressing issues which are "absolutely critical to Yahoo properties".</p>
    </div>
</div>

