<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('VisiCalc'); ?>
        <p><strong>VisiCalc</strong> was the first spreadsheet computer program, originally released for the <?php echo $this->stencil->addLink('Apple II', 'ITH'); ?>.</p>
        <p>It is often considered the application that turned the microcomputer from a hobby for computer enthusiasts into a serious business tool, and is considered the Apple II's killer app.</p>
        <p>VisiCalc sold over 700,000 copies in six years, and as many as 1 million copies over its history.</p>
        <p>VisiCalc was ported to numerous platforms, both 8-bit and some of the early 16-bit systems. In order to do this, the company developed porting platforms that produced bug compatible versions.</p>
        <p>The company took the same approach when the <?php echo $this->stencil->addLink('IBM PC', 'PC'); ?> was launched, producing a product that was essentially identical to the original 8-bit Apple II version.</p>
        <p>Sales were initially brisk, with about 300,000 copies sold.</p>
        <p>When <?php echo $this->stencil->addLink('Lotus 1-2-3', 'SS'); ?> was launched in 1983, taking full advantage of the expanded memory and screen of the PC, VisiCalc sales practically ended overnight. Sales imploded so rapidly that the company was soon insolvent.</p>
        <p><?php echo $this->stencil->addLink('Lotus Development', 'C'); ?> purchased the company in 1985, and immediately ended sales of VisiCalc and the company's other products.</p>
        <p>VisiCalc traces its history to a presentation that <strong>Dan Bricklin</strong> was watching while attending Harvard Business School.</p>
        <p>The professor was creating a financial model on a blackboard that was ruled with lines to create a table, and formulas and data were being written into the cells.</p>
        <p>When the professor found an error or wanted to change a parameter, he had to erase and rewrite a number of sequential entries in the table.</p>
        <p>Bricklin realized that he could replicate the process on a computer using an "<em>electronic spreadsheet</em>" to view results of underlying formulae.</p>
        <p>Bricklin was joined by <strong>Bob Frankston</strong>, and the pair worked on VisiCalc for two months during the winter of 1978 - 79, forming <strong>Software Arts</strong>. Bricklin wrote, "<em>With the years of experience we had at the time we created VisiCalc, we were familiar with many row/column financial programs. In fact, Bob had worked since the 1960s at Interactive Data Corporation, a major timesharing utility that was used for some of them and I was exposed to some at Harvard Business School in one of the classes</em>".</p>
        <p>Bricklin is referring to the variety of report generators that were in use at that time, including <strong>Business Planning Language (BPL)</strong> from <strong>International Timesharing Corporation (ITS)</strong> and <strong>Foresight</strong>, from <strong>Foresight Systems</strong>. However, these earlier timesharing programs were not completely interactive, nor did they run on personal computers.</p>
        <p>Their original intention was to fit the program into 16k, but this proved impossible and 32k became necessary. Some additional features they wanted like a split text/graphics screen still had to be omitted for space reasons. However, Apple eventually began shipping all Apple IIs with 48k following a drop in RAM prices and so this was no longer an issue.</p>
        <p>The initial release supported cassette storage, but that was quickly dropped.</p>
        <p>Distribution was taken up by <strong>Personal Software</strong> (later named <strong>VisiCorp</strong>), and VisiCalc appeared on the market in mid 1979 after an official launch on 4 June at the National Computer Conference.</p>
        <p>The power of the VisiCalc concept was noticed immediately. <strong>Ben Rosen</strong> speculated in July 1979 that "<em>VisiCalc could someday become the software tail that wags (and sells) the personal computer dog</em>".</p>
        <p>For the first 12 months it was only available for the Apple II computer, and became that platform's killer app.</p>
        <p>There are widespread stories of people buying $2000 computers to run the $100 software.</p>
        <p>VisiCalc was unusually easy to use; Apple's developer documentation cited it as an example of software with a simple user interface.</p>
        <p>Bricklin and Frankston developed ports for the <strong><?php echo $this->stencil->addLink('Atari 800', 'ITH'); ?></strong> and <strong><?php echo $this->stencil->addLink('Commodore PET', 'ITH'); ?></strong>, both of which could be done easily because those computers used the same <?php echo $this->stencil->addLink('6502', 'CPU'); ?> CPU as the Apple II, and large portions of code could be reused.</p>
        <p>The PET version, which contained two separate executables for 40 and 80 column models, was widely criticized for having a very small amount of worksheet space due to the developers' insistence on including their own custom DOS which used a large amount of memory (the PET only had 32k versus the Apple II's 48k).</p>
        <p>Other ports followed for the HP-150 and TRS-80 Model I and II. The TRS-80 Model I port was the only version of Visicalc that did not have any copy protection. On most versions, this was disk-based, but the PET Visicalc came with a ROM chip that the user had to install in one of the motherboard's expansion ROM sockets (the chip contained an ID string that the program looked for on start-up).</p>
        <p>Another, more complex, port was made to the <?php echo $this->stencil->addLink('IBM PC', 'ITH'); ?>, and it was one of the first commercial packages available when it shipped in 1981.</p>
        <p>It quickly became a best-seller on this platform, in spite of being severely limited to be compatible with the versions from the 8-bit platforms.</p>
        <p>It is estimated that 300,000 copies were sold on the PC, bringing total sales to about 1 million copies.</p>
        <p>Several competitors appeared in the market, notably <?php echo $this->stencil->addLink('SuperCalc', 'SS'); ?> and <?php echo $this->stencil->addLink('Multiplan', 'SS'); ?>, each of which added more features and corrected deficiencies in Visicalc, but could not overcome its market dominance.</p>
        <p>A more dramatic change occurred with the 1983 launch of <?php echo $this->stencil->addLink('Lotus 1-2-3', 'SS'); ?>, written by a former VisiCalc employee.</p>
        <p>Unlike the PC version of VisiCalc, 1-2-3 was written to take full advantage of the PC's increased memory, screen and performance. Yet it deliberately attempted to remain as compatible as possible with VisiCalc, including copying its menu structure as far as possible to allow VisiCalc users to easily migrate to 1-2-3.</p>
        <p>The program was an immediate runaway success, and sales of VisiCalc evaporated almost overnight.</p>
        <p>By 1985 VisiCorp was insolvent, and sold Software Arts to their competitor, <?php echo $this->stencil->addLink('Lotus Development', 'C'); ?>. Lotus immediately ended sales of the product.</p>
    </div>
</div>