<div class="row">
    <div class="col-lg-12 col-md-12">
        <?php echo $this->stencil->setHeadline('Nginx Web Server'); ?>
        <p><strong>Nginx</strong> (pronounced "<em>engine-x</em>") is an open source reverse proxy server for <?php echo $this->stencil->addLink('HTTP', 'IPA'); ?>, <?php echo $this->stencil->addLink('HTTPS', 'IPA'); ?>, <?php echo $this->stencil->addLink('SMTP', 'IPA'); ?>, <?php echo $this->stencil->addLink('POP3', 'IPA'); ?>, and <?php echo $this->stencil->addLink('IMAP', 'IPA'); ?> protocols, as well as a load balancer, HTTP cache, and a web server (origin server).</p>
        <P>The nginx project started with a strong focus on high concurrency, high performance and low memory usage.</P>
        <P>It is licensed under the 2-clause BSD-like license and it runs on <?php echo $this->stencil->addLink('Linux', 'OS'); ?>, <?php echo $this->stencil->addLink('BSD', 'OS'); ?> variants, <?php echo $this->stencil->addLink('Mac OS X', 'OS'); ?>, <?php echo $this->stencil->addLink('Solaris', 'OS'); ?>, AIX, HP-UX, as well as on other <?php echo $this->stencil->addLink('*nix', 'OS'); ?> flavours. It also has a proof of concept port for <?php echo $this->stencil->addLink('Microsoft Windows', 'OS'); ?>.</p>
        <p>Nginx can be deployed to serve dynamic HTTP content on the network using FastCGI, SCGI handlers for scripts, WSGI application servers or Phusion Passenger module, and it can serve as a software load balancer.</p>
        <p>Its development started in 2002 by <strong>Igor Sysoev</strong>. In July 2011, a company was formed as <strong>Nginx, Inc</strong>. Its principal place of business is San Francisco, California. The company offered commercial support in February 2012, and paid NGINX Plus subscription in August 2013. An investment of $10 million led by New Enterprise Associates was reported in October 2013. Other investors reportedly included Aaron Levie. WordPress developer Automattic and Content Delivery Network provider MaxCDN have become funding partners for an update to Google's SPDY version 3.1, slated for early 2014.</p>
        <p>Nginx uses an asynchronous event-driven approach to handling requests, instead of the <?php echo $this->stencil->addLink('Apache', 'WS'); ?> HTTP Server model that defaults to a threaded or process-oriented approach, where the Event MPM is required for asynchronous processing. Nginx's modular event-driven architecture can provide more predictable performance under high loads.</p>
        <p>Originally, nginx was developed to fill the needs of websites including Rambler, for which it was serving 500 million requests per day by September 2008. According to Netcraft's August 2014 Web Server Survey, nginx was found to be the second most widely used web server across all "active" sites (14.47% of surveyed sites) and for the top million busiest sites (19.60% of surveyed sites). According to W3Techs, it was used by 24.6% of the top 1 million websites, 32.9% of the top 100,000 websites, and by 41.1% of the top 1,000 websites. According to BuiltWith, it is used on 23.8% of the top 10,000 websites, and its growth within the top 10k, 100k and 1 million segments increased. <?php echo $this->stencil->addLink('Wikipedia', 'URL'); ?> uses nginx as its SSL termination proxy. As of OpenBSD release 5.2 (1 November 2012), nginx became part of the OpenBSD base system, providing an alternative to the system's fork of Apache 1.3, which it was intended to replace. Eventually, Apache was removed from the base system.</p>
        <br />
        <p><strong>Official Nginx Web Server website:<?php echo $this->stencil->addExternalLink('nginx.org', 'http://nginx.org/'); ?></p>
    </div>
</div>
